
services:
  postgres:
    image: postgres:18
    container_name: pharma_smart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2802"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-pharma-smart.sql:/docker-entrypoint-initdb.d/init-pharma-smart.sql:ro
    restart: unless-stopped

volumes:
  postgres_data:
