export const enum Params {
  APP_GESTION_STOCK = 'APP_GESTION_STOCK',
  APP_CASH_FUND = 'APP_CASH_FUND',
  APP_QTY_MAX = 'APP_QTY_MAX',
  APP_SANS_NUM_BON = 'APP_SANS_NUM_BON',
  APP_GESTION_LOT = 'APP_GESTION_LOT',
  APP_MODE_REGL_NUMBER = 'APP_MODE_REGL_NUMBER',


}
