-- Table de traçabilité des réceptions de lots
-- Permet de lier un lot à toutes les commandes qui l'ont livré (même lot sur plusieurs BL)
CREATE TABLE lot_reception
(
  id                  integer generated by default as identity primary key,
  lot_id              INTEGER   NOT NULL REFERENCES lot (id),
  order_line_id       INTEGER   NOT NULL,
  commande_order_date DATE      NOT NULL,
  quantity_received   INTEGER   NOT NULL,
  free_qty            INTEGER   NOT NULL DEFAULT 0,
  prix_achat          INTEGER   NOT NULL DEFAULT 0,
  receipt_date        DATE,
  created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_lot_reception_order_line
    FOREIGN KEY (order_line_id, commande_order_date)
      REFERENCES order_line (id, order_date)
);

CREATE INDEX lot_reception_lot_id_idx ON lot_reception (lot_id);
CREATE INDEX lot_reception_order_line_idx ON lot_reception (order_line_id, commande_order_date);

INSERT INTO app_configuration (name, value, description, value_type)
VALUES ('APP_RECEPTION_MIN_EXPIRY_DAYS', '90',
        'Durée minimale (en jours) de validité d''un lot à la réception. Tout lot dont la date de péremption est inférieure à ce seuil est refusé.',
        'NUMBER') ON CONFLICT (name) DO NOTHING;

CREATE TABLE fournisseur_produit_price_history
(
  id                     integer generated by default as identity primary key,
  fournisseur_produit_id INTEGER   NOT NULL REFERENCES fournisseur_produit (id),
  old_prix_achat         INTEGER   NOT NULL,
  new_prix_achat         INTEGER   NOT NULL,
  old_prix_uni           INTEGER   NOT NULL,
  new_prix_uni           INTEGER   NOT NULL,
  changed_at             TIMESTAMP NOT NULL DEFAULT NOW(),
  changed_by_id          INTEGER REFERENCES app_user (id),
  commande_id            INTEGER,
  receipt_reference      VARCHAR(20)
);

CREATE INDEX fp_price_history_fp_id_idx ON fournisseur_produit_price_history (fournisseur_produit_id);
CREATE INDEX fp_price_history_changed_at_idx ON fournisseur_produit_price_history (changed_at);

ALTER TABLE commande
  ADD COLUMN IF NOT EXISTS original_commande_id INTEGER;


CREATE TABLE pharmaml_envoi
(
  id                 integer generated by default as identity primary key,
  commande_id        INTEGER     NOT NULL,
  commande_date      DATE        NOT NULL,
  fournisseur_id     INTEGER     NOT NULL,
  statut             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  ref_message        VARCHAR(30),
  tentatives         INTEGER     NOT NULL DEFAULT 0,
  derniere_tentative TIMESTAMP,
  xml_requete_path   VARCHAR(255),
  xml_reponse_path   VARCHAR(255),
  total_lignes       INTEGER,
  lignes_acceptees   INTEGER,
  lignes_rupture     INTEGER,
  created_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_pharmaml_commande
    FOREIGN KEY (commande_id, commande_date)
      REFERENCES commande (id, order_date)
);

CREATE INDEX idx_pharmaml_envoi_commande ON pharmaml_envoi (commande_id, commande_date);
CREATE INDEX idx_pharmaml_envoi_statut ON pharmaml_envoi (statut);


CREATE TABLE substitution_proposee
(
  id                integer generated by default as identity primary key,
  commande_id       INTEGER     NOT NULL,
  commande_date     DATE        NOT NULL,
  commande_order_date     DATE        NOT NULL,
  order_line_id     INTEGER     NOT NULL,
  fournisseur_id    INTEGER     NOT NULL,
  cip_propose       VARCHAR(13) NOT NULL,
  designation       VARCHAR(255),
  type_codification VARCHAR(10),
  quantite          INTEGER     NOT NULL,
  statut            VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE',
  created_at        TIMESTAMP   NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_substitution_commande
    FOREIGN KEY (commande_id, commande_order_date)
      REFERENCES commande (id, order_date),
  CONSTRAINT fk_substitution_order_line
    FOREIGN KEY (order_line_id, commande_date)
      REFERENCES order_line (id, order_date)
);

CREATE INDEX idx_substitution_commande ON substitution_proposee (commande_id, commande_order_date);
CREATE INDEX idx_substitution_statut ON substitution_proposee (statut);


ALTER TABLE commande
  ADD COLUMN IF NOT EXISTS reliquat_de_commande_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_commande_reliquat
  ON commande (reliquat_de_commande_id);
