CREATE TABLE planification_facturation (
    id                   INTEGER       generated by default as identity primary key,
    libelle              VARCHAR(100) NOT NULL,
    periodicite          VARCHAR(20)  ,
    heure_declenchement  TIME         NOT NULL DEFAULT '09:00:00',
    categorie_tiers      VARCHAR(20),
    facture_provisoire   BOOLEAN      NOT NULL DEFAULT FALSE,
    actif                BOOLEAN      NOT NULL DEFAULT TRUE,
    prochaine_execution  TIMESTAMP,
    derniere_execution   TIMESTAMP,
    dernier_statut       VARCHAR(20),
    dernier_message      VARCHAR(500),
    created              TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated              TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE historique_planification (
    id               bigint   generated by default as identity primary key,
    planification_id INTEGER     NOT NULL REFERENCES planification_facturation(id),
    execution_debut  TIMESTAMP   NOT NULL,
    execution_fin    TIMESTAMP,
    statut           VARCHAR(20) NOT NULL,
    generation_code  INTEGER,
    nombre_factures  INTEGER,
    message          VARCHAR(500)
);
