CREATE TABLE avoir_tiers_payant (
    id                   bigint     generated by default as identity primary key,
    num_avoir            VARCHAR(30)   NOT NULL UNIQUE,
    facture_origine_id   BIGINT        NOT NULL,
    facture_origine_date DATE          NOT NULL,
    tiers_payant_id      INTEGER       NOT NULL REFERENCES tiers_payant(id),
    montant_avoir        NUMERIC(15,2) NOT NULL,
    montant_tva          NUMERIC(15,2) NOT NULL DEFAULT 0,
    montant_ht           NUMERIC(15,2) NOT NULL DEFAULT 0,
    motif                VARCHAR(500),
    avoir_date           DATE          NOT NULL,
    statut               VARCHAR(10)   NOT NULL DEFAULT 'DRAFT',
    user_id              INTEGER       NOT NULL REFERENCES app_user(id),
    created              TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated              TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_avoir_facture_origine
        FOREIGN KEY (facture_origine_id, facture_origine_date)
        REFERENCES facture_tiers_payant(id, invoice_date)
);

CREATE TABLE avoir_line (
    id             bigint     generated by default as identity primary key,
    avoir_id       BIGINT        NOT NULL REFERENCES avoir_tiers_payant(id),
    sale_line_id   BIGINT        NOT NULL,
    sale_line_date DATE          NOT NULL,
    montant_avoir  NUMERIC(15,2) NOT NULL,
    motif_rejet    VARCHAR(200),
    CONSTRAINT fk_avoir_line_sale_line
        FOREIGN KEY (sale_line_id, sale_line_date)
        REFERENCES third_party_sale_line(id, sale_date)
);

CREATE SEQUENCE avoir_numero_seq START 1;
