-- ============================================================
-- V1.4.6 — Périodicité organisme + refonte planification
-- ============================================================

-- 1. Périodicité + flag facturation auto sur les organismes
ALTER TABLE tiers_payant         ADD COLUMN IF NOT EXISTS periodicite_facture_definitive             VARCHAR(20) DEFAULT 'MENSUEL';
ALTER TABLE tiers_payant         ADD COLUMN IF NOT EXISTS inclure_facturation_auto_definitive BOOLEAN    NOT NULL DEFAULT TRUE;

ALTER TABLE groupe_tiers_payant  ADD COLUMN IF NOT EXISTS periodicite_facture_definitive             VARCHAR(20) DEFAULT 'MENSUEL';
ALTER TABLE groupe_tiers_payant  ADD COLUMN IF NOT EXISTS inclure_facturation_auto_definitive BOOLEAN    NOT NULL DEFAULT TRUE;
ALTER TABLE tiers_payant
  ADD COLUMN IF NOT EXISTS periodicite_facture_provisoire       VARCHAR(20),
  ADD COLUMN IF NOT EXISTS inclure_facturation_auto_provisoire  BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE groupe_tiers_payant
  ADD COLUMN IF NOT EXISTS periodicite_facture_provisoire       VARCHAR(20),
  ADD COLUMN IF NOT EXISTS inclure_facturation_auto_provisoire  BOOLEAN NOT NULL DEFAULT TRUE;
-- 2. Ajouter derniere_periode_fin
ALTER TABLE planification_facturation
  ADD COLUMN IF NOT EXISTS derniere_periode_fin DATE;

-- 3. Contrainte unicité : une seule planification par (périodicité + type provisoire/définitif)
ALTER TABLE planification_facturation
  ADD CONSTRAINT uq_planification_periodicite_provisoire UNIQUE (periodicite, facture_provisoire);


INSERT INTO planification_facturation
  (libelle, periodicite, heure_declenchement,
   actif, facture_provisoire, derniere_periode_fin, created, updated)
VALUES
  (
    'Facturation mensuelle', 'MENSUEL', '09:00:00', FALSE, FALSE,
    (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE,
    NOW(), NOW()
  ),
  (
    'Facturation quinzainière', 'QUINZAINE', '09:00:00',  FALSE, FALSE,
    CASE
      WHEN EXTRACT(DAY FROM CURRENT_DATE) <= 15
        THEN (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE   -- fin du mois précédent
      ELSE
        (date_trunc('month', CURRENT_DATE) + INTERVAL '14 days')::DATE      -- 15 du mois courant
    END,
    NOW(), NOW()
  ),
  (
    'Facturation bimensuelle', 'BIMENSUEL', '09:00:00', FALSE, FALSE,
    (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE,
    NOW(), NOW()
  ),
  -- Factures PROVISOIRES (même logique de dates)
  (
    'Facturation mensuelle (provisoire)', 'MENSUEL', '09:00:00',  FALSE, TRUE,
    (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE,
    NOW(), NOW()
  ),
  (
    'Facturation quinzainière (provisoire)', 'QUINZAINE', '09:00:00',  FALSE, TRUE,
    CASE
      WHEN EXTRACT(DAY FROM CURRENT_DATE) <= 15
        THEN (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE
      ELSE
        (date_trunc('month', CURRENT_DATE) + INTERVAL '14 days')::DATE
    END,
    NOW(), NOW()
  ),
  (
    'Facturation bimensuelle (provisoire)', 'BIMENSUEL', '09:00:00',  FALSE, TRUE,
    (date_trunc('month', CURRENT_DATE) - INTERVAL '1 day')::DATE,
    NOW(), NOW()
  )
ON CONFLICT (periodicite, facture_provisoire) DO NOTHING;



CREATE TABLE planification_certification_fne (
                                               id                     INTEGER       generated by default as identity primary key,
                                               libelle             VARCHAR(100)    NOT NULL,
                                               heure_declenchement TIME            NOT NULL DEFAULT '09:00:00',
                                               actif               BOOLEAN         NOT NULL DEFAULT FALSE,
                                               prochaine_execution TIMESTAMP,
                                               derniere_execution  TIMESTAMP,
                                               dernier_statut      VARCHAR(20),
                                               dernier_message     VARCHAR(500),
                                               created             TIMESTAMP       NOT NULL,
                                               updated             TIMESTAMP       NOT NULL
);

-- 2. Historique des exécutions
CREATE TABLE historique_certification_fne (
                                            id                 bigint       generated by default as identity primary key,
                                            planification_id INTEGER     REFERENCES planification_certification_fne(id),
                                            execution_debut  TIMESTAMP,
                                            execution_fin    TIMESTAMP,
                                            statut           VARCHAR(20),
                                            nb_certifiees    INTEGER     NOT NULL DEFAULT 0,
                                            nb_echecs        INTEGER     NOT NULL DEFAULT 0,
                                            message          VARCHAR(1000)
);

CREATE INDEX idx_historique_certif_fne_plan ON historique_certification_fne(planification_id);


INSERT INTO planification_certification_fne
(libelle, heure_declenchement, actif, prochaine_execution, created, updated)
VALUES
  ('Certification FNE automatique', '09:00:00', FALSE,
   (CURRENT_DATE + INTERVAL '1 day')::TIMESTAMP + TIME '02:00:00',
   NOW(), NOW());
ALTER TABLE facture_tiers_payant
  ADD COLUMN IF NOT EXISTS origine_generation VARCHAR(20) NOT NULL DEFAULT 'MANUELLE';

CREATE INDEX IF NOT EXISTS idx_facture_origine ON facture_tiers_payant(origine_generation);
