-- ═══════════════════════════════════════════════════════════════════════════════
-- Refactoring avoir fournisseur :
--   - Suppression de reponse_retour_bon / reponse_retour_bon_item
--   - Remplacement du lien reponse_retour_bon_id par retour_bon_id direct
--   - Création de avoir_fournisseur_line
--   - Ajout du statut ANNULE
-- ═══════════════════════════════════════════════════════════════════════════════

-- 1. Créer la table des lignes d'avoir fournisseur
CREATE TABLE IF NOT EXISTS avoir_fournisseur_line (
    id                    integer generated by default as identity PRIMARY KEY,
    avoir_fournisseur_id  integer NOT NULL REFERENCES avoir_fournisseur(id),
    retour_bon_item_id    integer NOT NULL REFERENCES retour_bon_item(id),
    qty_mvt               integer NOT NULL,
    prix_achat            bigint  NOT NULL,
    commentaire           varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_avf_line_avoir   ON avoir_fournisseur_line (avoir_fournisseur_id);
CREATE INDEX IF NOT EXISTS idx_avf_line_item    ON avoir_fournisseur_line (retour_bon_item_id);

-- 2. Ajouter la colonne retour_bon_id sur avoir_fournisseur
ALTER TABLE avoir_fournisseur ADD COLUMN IF NOT EXISTS retour_bon_id integer REFERENCES retour_bon(id);

-- 3. Migrer les données existantes : résoudre retour_bon_id via reponse_retour_bon
UPDATE avoir_fournisseur af
SET retour_bon_id = rrb.retour_bon_id
FROM reponse_retour_bon rrb
WHERE af.reponse_retour_bon_id = rrb.id
  AND af.retour_bon_id IS NULL;

-- 4. Passer retour_bon_id NOT NULL (après migration des données)
ALTER TABLE avoir_fournisseur ALTER COLUMN retour_bon_id SET NOT NULL;

-- 5. Supprimer l'ancienne colonne reponse_retour_bon_id
ALTER TABLE avoir_fournisseur DROP CONSTRAINT IF EXISTS avoir_fournisseur_reponse_retour_bon_id_key;
ALTER TABLE avoir_fournisseur DROP COLUMN IF EXISTS reponse_retour_bon_id;

-- 6. Mettre à jour la contrainte de statut pour inclure ANNULE
ALTER TABLE avoir_fournisseur DROP CONSTRAINT IF EXISTS avoir_fournisseur_statut_check;
ALTER TABLE avoir_fournisseur ADD CONSTRAINT avoir_fournisseur_statut_check
    CHECK (statut IN ('EN_ATTENTE', 'REMBOURSE', 'IMPUTE', 'ANNULE'));

-- 7. Supprimer les tables devenues inutiles (ordre : enfant avant parent)
DROP TABLE IF EXISTS reponse_retour_bon_item;
DROP TABLE IF EXISTS reponse_retour_bon;

CREATE INDEX IF NOT EXISTS idx_avoir_fournisseur_retour_bon ON avoir_fournisseur (retour_bon_id);
