-- ═══════════════════════════════════════════════════════════════════════════
-- AvoirClient : document de clôture d'avoir client
--   Créé automatiquement lors d'une réception de commande (StockEntry)
--   lorsque des produits reçus ont des SalesLine avec quantityAvoir > 0.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE avoir_client (
    id                  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(30)  NOT NULL UNIQUE,
    created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
    cloture_le          TIMESTAMP,
    statut              VARCHAR(15)  NOT NULL DEFAULT 'OUVERT',
    mode_cloture        VARCHAR(30),
    quantite            INTEGER      NOT NULL,
    montant             INTEGER       NOT NULL,
    commentaire         VARCHAR(500),
    customer_id         INTEGER      REFERENCES customer(id),
    produit_id          INTEGER      NOT NULL REFERENCES produit(id),
    sales_line_id       BIGINT,
    sales_line_date     DATE,
    commande_id         INTEGER,
    commande_order_date DATE,
    created_by_id       INTEGER      NOT NULL REFERENCES app_user(id),
    closed_by_id        INTEGER      REFERENCES app_user(id),
    CONSTRAINT fk_avoir_client_sales_line
        FOREIGN KEY (sales_line_id, sales_line_date)
        REFERENCES sales_line(id, sale_date),
    CONSTRAINT fk_avoir_client_commande
        FOREIGN KEY (commande_id, commande_order_date)
        REFERENCES commande(id, order_date)
);

CREATE INDEX idx_avoir_client_statut   ON avoir_client (statut);
CREATE INDEX idx_avoir_client_produit  ON avoir_client (produit_id);
CREATE INDEX idx_avoir_client_customer ON avoir_client (customer_id);
