
ALTER TABLE produit
    ADD COLUMN statut_legal VARCHAR(20) NOT NULL DEFAULT 'SANS_LISTE';

UPDATE produit
SET statut_legal = 'LISTE_I'
WHERE scheduled = true;

ALTER TABLE produit
    DROP COLUMN scheduled;
ALTER TABLE retour_client_line
  ADD COLUMN IF NOT EXISTS montant_tp INT NOT NULL DEFAULT 0;

INSERT INTO app_configuration (name, value, description, created, updated,value_type)
VALUES
  ('APP_NOTIF_AVOIR_EMAIL_ENABLED', '0',
   'Activer la notification email au client lorsque ses produits en avoir sont disponibles au comptoir (0=désactivé, 1=activé)',
   NOW(), NOW(),'BOOLEAN'),
  ('APP_NOTIF_AVOIR_SMS_ENABLED', '0',
   'Activer la notification SMS au client lorsque ses produits en avoir sont disponibles au comptoir (0=désactivé, 1=activé)',
   NOW(), NOW(),'BOOLEAN')
  ON CONFLICT (name) DO NOTHING;


ALTER TABLE avoir_client ADD COLUMN IF NOT EXISTS date_expiration DATE;

-- Paramètre de délai de validité d'un avoir client (en jours)
INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES (
         'APP_DELAI_VALIDITE_AVOIR', '90',
         'Délai de validité d''un avoir client en jours (défaut : 90 jours). Passé ce délai, l''avoir passe automatiquement au statut EXPIRE.',
         NOW(), NOW(), 'NUMBER'
       )
  ON CONFLICT (name) DO NOTHING;

-- Paramètre du délai maximum (jours) entre la vente et le retour client avant avertissement
INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES (
         'APP_DELAI_RETOUR_CLIENT', '30',
         'Délai maximum en jours entre la date de vente et la date du retour client avant avertissement au pharmacien. La décision reste laissée au pharmacien.',
         NOW(), NOW(), 'NUMBER'
       )
  ON CONFLICT (name) DO NOTHING;
ALTER TABLE retour_client_line
  ADD COLUMN IF NOT EXISTS emballage_intact     BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS num_lot_lisible      BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS date_peremption_valide BOOLEAN NOT NULL DEFAULT TRUE;

-- Colonne montant_utilise sur avoir_client (cumul des utilisations partielles)
ALTER TABLE avoir_client
  ADD COLUMN IF NOT EXISTS montant_utilise INT NOT NULL DEFAULT 0;

-- Historique des utilisations partielles d'un avoir
CREATE TABLE IF NOT EXISTS avoir_client_utilisation (
                                                      id               integer generated by default as identity,
                                                      avoir_client_id  INT          NOT NULL REFERENCES avoir_client(id),
  montant_utilise  INT          NOT NULL,
  utilise_le       TIMESTAMP    NOT NULL DEFAULT NOW(),
  commentaire      VARCHAR(500),
  utilise_par_id   INT       NOT NULL REFERENCES app_user(id)
  );

CREATE INDEX IF NOT EXISTS idx_avu_avoir_client_id ON avoir_client_utilisation(avoir_client_id);

ALTER TABLE retour_client
  ADD COLUMN IF NOT EXISTS avec_echange    BOOLEAN     NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS echange_sale_ref VARCHAR(50);
