

INSERT INTO nav_item (code, libelle, titre_long, icon, router_link, parent_id, ordre, niveau, actif, created, updated)
SELECT
    'dci',
    'DCI',
    'Dénominations Communes Internationales',
    'pi pi-bookmark',
    '/dci',
    p.id,
    -- Se place après le dernier enfant existant du module.
    COALESCE((SELECT MAX(c.ordre) FROM nav_item c WHERE c.parent_id = p.id), 0) + 1,
    2,
    TRUE,
    NOW(),
    NOW()
FROM nav_item p
WHERE p.code = 'referentiel'
  AND NOT EXISTS (SELECT 1 FROM nav_item x WHERE x.code = 'dci');

-- Droits : alignés sur les autres référentiels produit du module.
INSERT INTO nav_item_role (
    nav_item_id, role_name,
    can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute
)
SELECT n.id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
FROM nav_item n
WHERE n.code = 'dci'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Référentiel des Dénominations Communes Internationales
--
-- Source : export du référentiel produit. Reprise en syntaxe PostgreSQL :
--   * les identifiants entre accents graves (syntaxe MySQL) ont été retirés ;
--   * les apostrophes, échappées par une barre oblique inverse en MySQL, sont
--     désormais doublées : avec standard_conforming_strings actif — le défaut
--     depuis PostgreSQL 9.1 — la barre oblique est un caractère littéral, et
--     l'apostrophe qui la suit aurait clos la chaîne ;
--   * les libellés en double ont été écartés : dci.libelle est UNIQUE, et une
--     seule ligne peut donc subsister par molécule ;
--   * les codes vides ou dépassant varchar(20) ont été dérivés du libellé,
--     selon la même règle que DciServiceImpl.
--
-- Une insertion multi-lignes remplace les 1100 INSERT unitaires d'origine :
-- un aller-retour au lieu de plusieurs centaines.
-- ---------------------------------------------------------------------------
INSERT INTO dci (code, libelle) VALUES
    ('DOXYLAMINEPYRIDO', 'DOXYLAMINE/PYRIDOXINE'),
    ('B1B', 'BETA ALANINE'),
    ('1YA', 'BENZOATE DE BENZYLE'),
    ('1N9', 'BETAXOLOL'),
    ('6R1', 'CLARITHROMYCINE'),
    ('2G1', 'ACIDE FOLIQUE'),
    ('2D1', 'MYRTECAINE/AMINO ACIDE/ GALACT'),
    ('1C4', 'ACIDE  ACETYLSALICYLIQUE'),
    ('1Q3', 'RANITIDINE'),
    ('1R2', 'AMOXICILLINE/ACIDE CLAVULANIQU'),
    ('1D8', 'ATTAPULGITE DE MORMOIRON'),
    ('2I4', 'DEANOL/MAGNES/VIT C'),
    ('1P1', 'ACECLOFENAC'),
    ('Y01', 'aceclofenac+paracetamol'),
    ('3N8', 'QUINAPRIL'),
    ('2MD', 'PIDOLATE DE MAGNESIUM'),
    ('3N1', 'QUINAPRIL/HYDROCHLOROTHIAZIDE'),
    ('2C0', 'NEFOPAM'),
    ('1RA', 'ACICLOVIR'),
    ('1UC', 'PAPAVERINE/CHARBON'),
    ('4N5', 'NIFEDIPINE'),
    ('1LD', 'LEVONORGESTREL/ETHINYLESTRADIO'),
    ('2S6', 'DOXORUBICINE'),
    ('1F7', 'DESLORATADINE'),
    ('2R9', 'OFLOXACINE'),
    ('YY0', 'lidocaine+sulfate de zinc'),
    ('2F2', 'LORATADINE'),
    ('1Z5', 'ALBENDAZOLE'),
    ('1ID', 'SPIRONOLACTONE/ALTIZIDE'),
    ('1IC', 'SPIRONOLACTONE'),
    ('4N8', 'METHYLDOPA'),
    ('1M2', 'PHENOBARBITAL/CAFEINE'),
    ('YB6', 'cefaclor'),
    ('1B8', 'AC SALICYLIQUE/DIETHYLAMINE/MY'),
    ('1F4', 'AZELASTINE'),
    ('1KN', 'BETAMETHASONE'),
    ('1F6', 'CETIRIZINE'),
    ('2F4', 'PROMETHAZINE'),
    ('4F3', 'CROMOGLYCATE DE SODIUM'),
    ('3C2', 'PARACETAMOL/CAFEINE'),
    ('1Z3', 'ALLOPURINOL'),
    ('4F6', 'LODOXAMIDE'),
    ('1VI', 'CETYLPYRIDINIUM/CHLOROBUTANOL/'),
    ('1P9', 'NAPROXENE'),
    ('2D6', 'HYDROXYDE D''ALUM ET DE MAGNES'),
    ('9RB', 'SULFAMETHOXAZOLE/TRIMETHOPRIME'),
    ('2I8', 'COMPLEXE VITAMINIQUE ET OLIGOE'),
    ('YA1', 'candesartan cilexetil+hydrochl'),
    ('4N1', 'AMLODIPINE'),
    ('1MG', 'POLYVITAMINES ET OLIGOELEMENTS'),
    ('1ZD', 'SULFADOXINE/PYRIMETHAMINE'),
    ('1V9', 'GLIMEPIRIDE'),
    ('YQ1', 'glimepiride+metformine'),
    ('1TJ', 'AMBROXOL'),
    ('2R5', 'METRONIDAZOLE'),
    ('1ZM', 'BETA-ARTEMETHER'),
    ('2G9', 'FER/ACIDE FOLIQUE/VIT B12'),
    ('1R1', 'AMOXICILLINE'),
    ('2N4', 'ATENOLOL/AMLODIPINE'),
    ('Y53', 'amlodipine+losartan'),
    ('Y52', 'amlodipine+lisinopril'),
    ('2R4', 'SECNIDAZOLE'),
    ('1R4', 'AMPICILLINE'),
    ('9RF', 'METRONIDAZOLE/NYSTATINE'),
    ('5R6', 'TINIDAZOLE'),
    ('1WJ', 'CHLORURE DE SODIUM'),
    ('1WA', 'IRGASAN'),
    ('YFF', 'paracetamol+dextromethorphane+'),
    ('1U3', 'CLOMIPRAMINE'),
    ('1C0', 'METAMIZOLE(NORAMIDOPYRINE)'),
    ('1FI', 'TESTOSTERONE UNDECANOATE'),
    ('1A7', 'LIDOCAINE/PRILOCAINE'),
    ('1VS', 'HEXETIDINE / ACIDE PROPIONIQUE'),
    ('1VM', 'DEQUALINIUM CHLORIDE/HYDROCORT'),
    ('1N3', 'LOSARTAN'),
    ('1EB', 'THIAMINE/PYRIDOXINE/CYANOCOBAL'),
    ('7R8', 'OXACILLINE'),
    ('1P6', 'FLURBIPROFENE'),
    ('1Q1', 'CIMETIDINE'),
    ('1B4', 'IBUPROFENE'),
    ('YGD', 'paracetamol+tramadol'),
    ('3RZ', 'POLYMYXINE B/NEOMYCINE/FLUOCIN'),
    ('4C1', 'PARACETAMOL/CODEINE/CAFEINE/VI'),
    ('D2D', 'CYPROHEPTADINE'),
    ('2C6', 'PARACETAMOL'),
    ('J2A', 'HYDROCORTISONE/NEOMYCINE/BENZO'),
    ('YAH', 'multi-antioxydants'),
    ('J6J', 'OXYDE DE ZINC ET DE BISMUTH'),
    ('YL6', 'extrait acqueux de,adhatoda va'),
    ('YEB', 'pantethine+carnitine+cyprohept'),
    ('2R6', 'NIFUROXAZIDE'),
    ('8R9', 'FLUMEQUINE'),
    ('1N4', 'VALSARTAN'),
    ('2I7', 'SULBUTIAMINE'),
    ('1ZK', 'ARTEMISININE/NAPHTOQUINE'),
    ('1NA', 'ARGININE CHLORHYDRATE'),
    ('1I5', 'ARGININE/THIAMINE/PYRIDOXINE'),
    ('Y60', 'anastrozole'),
    ('1ZJ', 'ARTEMETHER/LUMEFANTRINE'),
    ('1B9', 'ARNICA'),
    ('YL4', 'exemestane'),
    ('2G3', 'VIT B12/ACIDE PHOSPHERIQUE/CAL'),
    ('1ZP', 'QUININE'),
    ('1ZF', 'ARTESUNATE/MEFLOQUINE'),
    ('1ZI', 'ARTEMETHER'),
    ('1ZE', 'ARTESUNATE/AMODIAQUINE'),
    ('1ZL', 'ARTESUNATE'),
    ('Y65', 'artemisinine+piperaquine+trime'),
    ('Y56', 'amodiaquine+artesunate'),
    ('2P4', 'SULINDAC'),
    ('YI1', 'diclofenac+misoprostol'),
    ('4R4', 'CHLORETETRACYCLINE'),
    ('1R3', 'AMOXICILLINE/CLOXACILLINE'),
    ('1KB', 'PHENAZONE/LIDOCAINE CHLORHYDRA'),
    ('1S5', 'BEVACIZUMAB'),
    ('H5A', 'VIRUS HEPATITE A INACTIVE ADSO'),
    ('9R3', 'MOXIFLOXACINE'),
    ('J5J', 'EXTRAIT DE PLANTES HOMEOPATHIQ'),
    ('2V3', 'ROSIGLITAZONE'),
    ('1J9', 'FLUTICASONE'),
    ('2N2', 'PROPRANOLOL'),
    ('1B5', 'KETOPROFENE'),
    ('5R9', 'AZITHROMYCINE'),
    ('Y18', 'acide azelaique'),
    ('1Y8', 'BRINZOLAMIDE'),
    ('8R5', 'BACITRACINE/COLISTIMETHATE/HYD'),
    ('3R2', 'IMIPENEM/CILASTATINE'),
    ('8R7', 'CIPROFLOXACINE'),
    ('1TP', 'BROMHEXINE/SULFAMETHOXAZOLE TR'),
    ('YC2', 'cethexonium'),
    ('1R8', 'GENTAMICINE'),
    ('1YB', 'BENZOATE DE BENZYLE/SULFIRAME'),
    ('1TG', 'SALBUTAMOL/BROMHEXINE/GUAÏFENE'),
    ('1C1', 'ACETYLSALICYLATE DE LYSINE'),
    ('8R4', 'BACITRACINE/NEOMYCINE'),
    ('2B6', 'SALICYLATE DE METHYLE'),
    ('2B5', 'SALICYLATE D''AMYLE/CAMPHRE/LEV'),
    ('2B0', 'ESSENCE D''EUCALYPTUS/CAMPHRE/M'),
    ('1MK', 'VIT B1 B6 B13'),
    ('1ML', 'VITAMINES B1,B2,B5,B6/CALCIUM'),
    ('1J7', 'BECLOMETASONE'),
    ('1D6', 'MONTMORILLONITE BEIDELLITIQUE'),
    ('1MI', 'RIBOFLAVINE'),
    ('1Q6', 'OMEPRAZOLE'),
    ('4F1', 'BENZODODECINIUM BROMURE'),
    ('7R6', 'BENZATHINE/BENZYLPENICILLINE'),
    ('9RJ', 'POVIDONE IODEE'),
    ('1SB', 'BETAHISTINE'),
    ('4R1', 'CEFTAZIDIME'),
    ('J07', 'sulfate de zinc+vitamines B1+'),
    ('1YM', 'TROLAMINE'),
    ('YD1', 'chlorhydrate de diphenhydramin'),
    ('G3G', 'BICARBONATE DE SODIUM'),
    ('6R7', 'SPIRAMYCINE/METRONIDAZOLE'),
    ('1C5', 'ACIDE ACETYLSALICYLIQUE/ACIDE'),
    ('3R3', 'CEFADROXIL'),
    ('1Z4', 'PRAZIQUANTEL'),
    ('2TC', 'PHOLCODEINE/GAÏACOL/CINEOLE'),
    ('1H9', 'EXTRAITES HOMEOPATHIQUES'),
    ('8R8', 'FLUCLOXACILLINE'),
    ('1G7', 'FER/POLYMALTOSE'),
    ('1G3', 'FER ELEMENTAIRE'),
    ('1I8', 'KOLA/ACIDE PHOSPHERIQUE/INOSIT'),
    ('1G2', 'CITRATE D''ALU FERRIQUE/CYANOCO'),
    ('3N4', 'PERINDOPRIL/INDAPAMIDE'),
    ('Y35', 'acides amines+fer'),
    ('2I0', 'AC ASCORBIQUE/ACIDES AMINES'),
    ('Y39', 'acides amines+vitamines'),
    ('J04', 'retinol'),
    ('J03', 'acides amines'),
    ('YMF', 'sulfamethoxy pyrazine+pyrimeth'),
    ('1N5', 'CANDESARTAN'),
    ('1D4', 'POVIDONE'),
    ('2S1', 'ACIDE IBANDRONIQUE MONOSODIQUE'),
    ('F8G', 'HYDROXYZINE'),
    ('2N3', 'ATENOLOL'),
    ('C5C', 'ATORVASTATINE'),
    ('9RK', 'TENONITROZOLE'),
    ('1PG', 'ATROPINE'),
    ('2JA', 'OXYMETAZOLINE'),
    ('Y84', 'brimonidine'),
    ('1MM', 'CALCIUM/VIT B1/B2/B6/B12'),
    ('3R7', 'CEFIXIME'),
    ('1JR', 'CINEOL/GAIACOL/ESS DE PIN'),
    ('2TB', 'CHLORPHENAMINE/PHOLCODINE'),
    ('3I2', 'ACIDE ASCORBIQUE/CALCIUM'),
    ('3N5', 'AMLODIPINE/ATORVASTATINE'),
    ('Y94', 'calcium+levure saccharomyces c'),
    ('F2H', 'BROMO-GALACTOGLUCONATE DE CALC'),
    ('1MU', 'CALCIUM GLUCONOLACTATE/CARBONA'),
    ('1MN', 'CALCIUM/VIT B6 C D'),
    ('1MV', 'CALCIUM/VIT D3'),
    ('5R3', 'CALENDULA/EXTR HOMEOPATHIQUES'),
    ('1TD', 'PIMETHIXENE'),
    ('1MP', 'CALCIUM/VIT C'),
    ('YC3', 'cetylpyridinium+lysozyme'),
    ('2TJ', 'DEXTROMETHORPHANE'),
    ('2S4', 'IRINOTECAN'),
    ('YTJ', 'multivitamines+mineraux'),
    ('1X4', 'CLOTRIMAZOLE'),
    ('1TQ', 'CARBOCISTEINE'),
    ('3X1', 'ITRACONAZOLE'),
    ('1X5', 'CLOTRIMAZOLE/BECLOMETHASONE'),
    ('4R3', 'CLOTRIMAZOLE/CHLORAMPHENICOL/B'),
    ('2X9', 'FLUCONAZOLE'),
    ('1QC', 'SILDENAFIL'),
    ('3B6', 'CAPTOPRIL'),
    ('1A4', 'LIDOCAINE'),
    ('1FV', 'MINOXIDIL/PROGESTERONE/BIOTINE'),
    ('Y86', 'bromhexine+peru balsam+sodium'),
    ('YRI', 'vitamineBcomplexe'),
    ('1J5', 'SALBUTAMOL'),
    ('2P9', 'NIMESULIDE'),
    ('2N9', 'CAPTOPRIL/HYDROCHLOROTHIAZIDE'),
    ('1D1', 'CHARBON ACTIVE'),
    ('1D2', 'CHARBON ACTIVE/DIMETICONE'),
    ('1D7', 'CHARBON ACTIVE/LEVURE'),
    ('1Z7', 'MEBENDAZOLE'),
    ('1M3', 'CARBAMAZEPINE'),
    ('2FF', 'DOXAZOSINE'),
    ('Y63', 'anti oxydants+carotenoides+aci'),
    ('1Y4', 'CARTEOLOL'),
    ('1MC', 'GLUCOSAMINE/CA/VIT D'),
    ('1E3', 'ERYTHROMYCINE'),
    ('Y79', 'bicalutamide'),
    ('1PE', 'INOSINE'),
    ('1P4', 'DICLOFENAC'),
    ('4N7', 'CLONIDINE'),
    ('2R2', 'NEOMYCINE/POLYMYXINE B'),
    ('1A0', 'OXYBUPROCAÏNE'),
    ('1SC', 'PIRACETAM'),
    ('3R4', 'CEFALEXINE'),
    ('4R2', 'CEFTRIAXONE'),
    ('3I1', 'ACIDE ASCORBIQUE'),
    ('1KJ', 'BETAMETHASONE/DEXCHLORPHENIRAM'),
    ('2P7', 'CELECOXIB'),
    ('3C9', 'ACIDE ACETYLSALICYLIQUE/CAFEIN'),
    ('3R9', 'CEFPODOXIME'),
    ('1YT', 'OXYDE DE ZINC/PHENAZONE/PHENOL'),
    ('3P2', 'IBUPROFENE/PARACETAMOL'),
    ('1VE', 'TETRACAINE'),
    ('2TH', 'CHLORPHENIRAMINE/DEXTROMETHORP'),
    ('4F5', 'DEXAMETHASONE/NEOMYCINE'),
    ('6R8', 'NORFLOXACINE'),
    ('YGJ', 'phenobarbital+ephedrine+theoph'),
    ('8R2', 'CHLORAMPHENICOL'),
    ('1NE', 'ARTICHAUT'),
    ('1A8', 'CHLORURE D''ETHYLENE'),
    ('1YH', 'CHLOROCRESOL/ VIT E/ ALLANTOIN'),
    ('1WK', 'CALENDULA OFFICINALIS/HYPERICU'),
    ('YNC', 'tadalafil'),
    ('1W1', 'LOPERAMIDE'),
    ('1L4', 'DOMPERIDONE'),
    ('9R8', 'CIPROFLOXACINE/TINIDAZOLE'),
    ('9R9', 'RIFAMYCINE'),
    ('YI2', 'didecyl'),
    ('C8C', 'SIMVASTATINE'),
    ('3R8', 'CEFOTAXIME'),
    ('1FF', 'ESTRADIOL/CYPROTERONE'),
    ('2B1', 'IBUPROFENE/LEVOMENTHOL'),
    ('1FQ', 'CLOMIFENE'),
    ('1ZH', 'ARTESUNATE/SULFAMETOPYRAZINE/P'),
    ('3C5', 'PARACETAMOL/CODEINE'),
    ('1Z2', 'COLCHICINE/TIEMONIUM/OPIUM'),
    ('1Z1', 'COLCHICINE'),
    ('J13', 'chlorpheniramine+phenylephrine'),
    ('1JU', 'XYLENE'),
    ('1VR', 'HEXETIDINE'),
    ('1WG', 'CHLORHEXIDINE'),
    ('1PA', 'METHYLTHIONINIUM HYDROXYDE/NAP'),
    ('1YP', 'CETRIMIDE'),
    ('1VQ', 'HEXAMIDINE/LIDOCAÏNE'),
    ('J12', 'myristoleate de cetyl + acide'),
    ('YGU', 'amlodipine+perindopril'),
    ('F7G', 'CAPTODIAMINE'),
    ('Y75', 'benzydamine chlorhydrate'),
    ('4N6', 'PERINDOPRIL'),
    ('YKA', 'rosuvastatine calcique'),
    ('1E4', 'ISOTRETINOINE'),
    ('3R6', 'CEFUROXIME'),
    ('1WI', 'TRICLORCARBAN'),
    ('J8J', 'EXTRAITS VEGETAUX/AC ASCORBIQU'),
    ('1B6', 'PIROXICAM'),
    ('YOG', 'tricholine citrate'),
    ('1MD', 'CYSTINE/PYRIDOXINE'),
    ('1WM', 'HEXAMIDINE/CHLORHEXIDINE/CHLOR'),
    ('1PB', 'AC BORIQUE/BORATE DE SODIUM'),
    ('J9J', 'FLAVONOIDES'),
    ('1WL', 'CALCIPROTRIOL'),
    ('Y91', 'calcipotriol+dexamethasone'),
    ('1WB', 'HYPOCHLORITE DE SODIUM'),
    ('2X1', 'MICONAZOLE'),
    ('1FW', 'DANAZOL'),
    ('6R2', 'CLINDAMYCINE'),
    ('1V7', 'GLIBENCLAMIDE'),
    ('2X5', 'ACSALICYLIQUE/ACIDE BENZOIQUE'),
    ('YN9', 'fluconazole+azithromycine+secn'),
    ('1UI', 'TRIMEBUTINE'),
    ('1ZG', 'DIHYDROARTEMISININE/PIPERAQUIN'),
    ('2B4', 'MEPHENESINE/NICOTINATE'),
    ('1G6', 'FER/VITAMINES/COMPLEXE MINERAL'),
    ('Y04', 'acetazolamide'),
    ('1YL', 'OXYDE DE ZINC/DIOXYDE DE TITAN'),
    ('1VF', 'TAMARIN'),
    ('1KD', 'METHYLPREDNISOLONE'),
    ('1LB', 'MEDROXYPROGESTERONE'),
    ('2G2', 'HYDROXOCOBALAMINE'),
    ('1JW', 'PREDNISOLONE/NAPHAZOLINE'),
    ('1WT', 'OXYQUINOL/AC SALICYLIQUE'),
    ('1KH', 'BETAMETHASONE/NEOMYCINE'),
    ('2X2', 'SERTACONAZOLE'),
    ('1KL', 'BETAMETHASONE/ACIDE SALICYLIQU'),
    ('1WH', 'CHLORHEXIDINE/BENZALKONIUM CHL'),
    ('1U8', 'PAROXETINE'),
    ('2R7', 'HEXAMIDINE'),
    ('YEA', 'oxymetazoline+prednisolone'),
    ('YQ9', 'glycerol+paraffine liquide+vas'),
    ('2KG', 'NEOMYCINE DEXAMETHASONE'),
    ('1V8', 'GLICLAZIDE'),
    ('1E2', 'ETHINYLESTRADIOL/CYPROTERONE'),
    ('2TA', 'BELLADONE/EPHEDRINE/ETHYLMORPH'),
    ('1V2', 'METFORMINE/GLIPIZIDE'),
    ('2V1', 'GLIPIZIDE'),
    ('1UH', 'PINAVERIUM BROMURE'),
    ('3P1', 'DICLOFENAC/PARACETAMOL'),
    ('1HC', 'ETAMSYLATE'),
    ('1H4', 'DIGOXINE'),
    ('1M4', 'PHENYTOINE'),
    ('1J1', 'THEOPHYLLINE'),
    ('J4A', 'MYRTILLE/BETA-CAROTENE'),
    ('1F5', 'BROMPHENIRAMINE'),
    ('2TD', 'PHOLCODINE'),
    ('J7J', 'DIOSMINE'),
    ('1A1', 'PROPOFOL'),
    ('2FE', 'OESTRADIOL/PROGESTERONE'),
    ('2B9', 'CAMPHRE/MENTHOL/SALICYLATE DE'),
    ('YX6', 'levosulpiride'),
    ('YFJ', 'paracetamol+metocarbamol'),
    ('1IB', 'INDAPAMIDE'),
    ('A4A', 'SULPIRIDE'),
    ('2C7', 'TRAMADOL'),
    ('3F1', 'PARACETAMOL/PSEUDOEPHEDRINE'),
    ('YEG', 'paracetamol+acide ascorbique+p'),
    ('YY4', 'losartan+hydrochlorothiazide'),
    ('2FB', 'CHLORQUINALDOL / PROMESTRIENE'),
    ('2FC', 'PROMESTRIENE'),
    ('3C0', 'ACIDE ACETYLSALICYLIQUE/CODEIN'),
    ('6R6', 'SPIRAMYCINE'),
    ('Y21', 'acide gadoterique'),
    ('1EF', 'THIOCOLCHICOSIDE'),
    ('4R5', 'DOXYCYCLINE'),
    ('1Z8', 'PYRANTEL'),
    ('2C1', 'PARACETAMOL/ACIDE ASCORBIQUE'),
    ('1VL', 'CHLORHEXIDRINE/TETRACAINE'),
    ('1JH', 'EXTRAITS HOMEOPATHIQUES'),
    ('1ZB', 'AMODIAQUINE/SULFAMETOPYRAZINE/'),
    ('1Y7', 'MBS/AC PARAHYDROXYCINNAMIQUE'),
    ('1FK', 'DYDROGESTERONE'),
    ('1GG', 'LACTULOSE'),
    ('YZ1', 'mebeverine'),
    ('3I5', 'ASPARTATE D''ARGININE/ALPHACETO'),
    ('YWE', 'vitamineE'),
    ('1WQ', 'PEROXYDE D''HYDROGENE'),
    ('G6G', 'EPPI'),
    ('1E1', 'PEROXYDE DE BENZOYLE'),
    ('1X6', 'ECONAZOLE'),
    ('1B1', 'ACIDE NIFLUMIQUE'),
    ('1GL', 'TARTRATE  AC DE POTASSIUM/BICA'),
    ('YA7', 'carbonate de calcium+cholecalc'),
    ('1U1', 'VENLAXAFINE'),
    ('1H0', 'ETILEFRINE'),
    ('1U2', 'AMITRIPTYLINE'),
    ('1W6', 'TEINTURE D''OPIUM BENZOIQUE'),
    ('1S2', 'OXALOPLATINE'),
    ('1VK', 'CHLORHEXIDINE/CHLOROBUTAMOL'),
    ('YK2', 'enalapril'),
    ('1S1', 'CYCLOPHOSPHAMIDE'),
    ('YK4', 'enalapril+nitrendipine'),
    ('H7A', 'ANTIGENE DE SURFACE RECOMBINAN'),
    ('YAC', 'metronidazole+furoate de dilox'),
    ('YLI', 'sprores de bacillus clausii'),
    ('1KR', 'DIFLUPREDNATE'),
    ('1FH', 'ETHINYLESTRADIOL/NORGESTREL'),
    ('1GA', 'BISACODYL'),
    ('1M5', 'ACIDE VALPROIQUE'),
    ('3B1', 'EXTRAITS VEGETAUX'),
    ('1H2', 'AMIODARONE'),
    ('1KF', 'PREDNISONE'),
    ('1KT', 'HYDROCORTISONE'),
    ('YG7', 'delta-cortisone'),
    ('2H2', 'LINSIDOMINE'),
    ('2F6', 'EPHEDRINE/AC ACETYLSALICYLIQUE'),
    ('2F8', 'EXTRAITS VEGETAUX ET HOMEOPATH'),
    ('1N2', 'VALSARTAN/HYDROCHLOROTHIAZIDE'),
    ('Y37', 'acides amines+multivitamines'),
    ('3P8', 'MELILOT/HEPARINE SODIQUE'),
    ('1Q4', 'ESOMEPRAZOLE'),
    ('1JS', 'CINEOL/LEVOMENTHOL/GAIACOL'),
    ('YW9', 'letrozole'),
    ('1YN', 'DIMETHINDENE MALEATE'),
    ('1G9', 'HYDROXYDE POLYMALTOSE DE FER'),
    ('2G7', 'FER/AC FOLIQUE/VIT C'),
    ('YM9', 'fer+acide folique+cyanocobalam'),
    ('1GX', 'FER/CALCIUM'),
    ('YN2', 'fer+vitamines B1 B2 B3 B6 B12'),
    ('1FE', 'ESTRADIOL'),
    ('2G0', 'FER/ACIDE FOLIQUE/VIT B12/VIT'),
    ('1YE', 'LINDANE'),
    ('9RC', 'SULFADIAZINE'),
    ('1P3', 'ACIDE TIAPROFENIQUE'),
    ('J17', 'ibuprofene+methocarbamol'),
    ('1VB', 'BETA ESCINE'),
    ('YI0', 'diclofenac+cholestyramine'),
    ('1Z6', 'FLUBENDAZOLE'),
    ('2KC', 'FLUOROMETHOLONE'),
    ('1U6', 'FLUOXETINE'),
    ('YF8', 'cromoglycate de sodium+fluorom'),
    ('1TC', 'MEGLUMINE/POLYSORBATE 20/ PROM'),
    ('2TP', 'CODEINE/ERYSIMUM'),
    ('1VN', 'ERYSIMUM'),
    ('1J4', 'FORMOTEROL'),
    ('1GH', 'MACROGOL 4000'),
    ('1YW', 'CROTAMITON'),
    ('YG5', 'deanol acetoglutamate+heptamin'),
    ('YDE', 'omega3'),
    ('1JM', 'ESSENCES DE PLANTES/CAMPHRE'),
    ('1HA', 'ACIDE TRANEXAMIQUE'),
    ('J18', 'sulfate de glycine ferreux+chl'),
    ('YG4', 'dalteparine sodique'),
    ('2R1', 'FRAMYCETINE/DEXAMETHASONE'),
    ('1T4', 'NADROPARINE CALCIQUE'),
    ('1GN', 'PICOSULFATE DE SODIUM'),
    ('5R2', 'ACIDE FUSIDIQUE'),
    ('YO7', 'fumarate ferreux'),
    ('YO8', 'fumarate ferreux+acide folique'),
    ('1IA', 'FUROSEMIDE'),
    ('1FR', 'GALEGA/MALT/CALCIUM'),
    ('B7B', 'MAGNESIUM GLUTAMATE /GABA /GAB'),
    ('9RD', 'SULFAGUANIDINE'),
    ('1M1', 'PHENOBARBITAL'),
    ('1D9', 'ATTAPULGITE DE MORMOIRON / ALU'),
    ('YW1', 'lansoprazole+clarithromycine+t'),
    ('1PF', 'CARBOMERE'),
    ('G9G', 'GELATINE FLUIDE MODIFIEE'),
    ('1RD', 'OSELTAMIVIR PHOSPHATE'),
    ('3N9', 'RAMIPRIL'),
    ('2KF', 'GENTAMICINE/BETAMETHASONE'),
    ('3D1', 'SIMETHICONE/SEL ADSORBANT'),
    ('YM5', 'fer ferreux(sulfate)+oligoelem'),
    ('J1A', 'GINKGO BILOBA/HEPTAMINOL/TROXE'),
    ('1SD', 'GINKGO BILOBA'),
    ('1VT', 'HEXETIDINE/CHOLINE/CHLOROBUTAM'),
    ('1V1', 'METFORMINE/BLIBENCLAMIDE'),
    ('9R2', 'LEVOFLOXACINE'),
    ('1V4', 'ACARBOSE'),
    ('1V6', 'METFORMINE'),
    ('G1G', 'GLUCOSE ANHYDRE OU MONOHYDRATE'),
    ('2V2', 'GLIQUIDONE'),
    ('YE5', 'cineole+levomenthol+benzoate d'),
    ('1GC', 'GLYCERINE'),
    ('1JF', 'ESSENCE DE GOMENOL'),
    ('2FD', 'HORMONE GONADOTROPHINE CHORION'),
    ('3X4', 'GRISEOFULVINE'),
    ('1IE', 'HYDROCHLOROTHIAZIDE/AMILORIDE'),
    ('1I7', 'GLUCURONAMIDE/VIT C/CAFEINE'),
    ('9RG', 'METRONIDAZOLE/NEOMYCINE/NYSTAT'),
    ('Y54', 'amlodipine+valsartan'),
    ('1UG', 'PHLOROGLUCINOL'),
    ('2G5', 'FER ELEMENTAIRE/AC FOLIQUE/VIT'),
    ('A6A', 'HALOPERIDOL'),
    ('H6A', 'VIRUS INACTIVE HbA'),
    ('1TX', 'HELICIDINE'),
    ('1R5', 'AMOXICILLINE/METRONIDAZOLE'),
    ('1X1', 'CHLORHYDRATE DE NAFTIFINE/AC B'),
    ('1T3', 'HEPARINE SODIQUE'),
    ('1GK', 'SORBITOL/AC CITRIQUE/ARGININE'),
    ('1WF', 'HEXACHLOROPHENE'),
    ('2H1', 'HEPTAMINOL'),
    ('1TI', 'ACETYLCYSTEINE'),
    ('1S8', 'TRASTUZUMAB'),
    ('E6E', 'IOXOGLATE DE SODIUM/IOXOGLATE'),
    ('1VH', 'BICLOTYMOL/LYSOZYME/ENOXOLONE'),
    ('1VG', 'BICLOTYMOL'),
    ('1TB', 'BICLOTYMOL/PHOLCODINE/CHLORPHE'),
    ('3N2', 'LISINOPRIL/AMLODIPINE'),
    ('3N7', 'LISINOPRIL'),
    ('2VZ', 'ACONITUM NAPELLUS'),
    ('1L6', 'EXTRAITS DE PLANTES ET HUILES'),
    ('J23', 'Acide borique, Benjoin teintur'),
    ('1JG', 'HUILES DE GOMENOL ET D''OLIVE'),
    ('1VD', 'BENZALKONIUM/LIDOCAINE'),
    ('3F2', 'PARACETAMOL/PSEUDOEPHEDRINE/CH'),
    ('1MF', 'COMPLEXE VITAMINIQUE'),
    ('1N1', 'RILMENIDINE'),
    ('YA2', 'candesartan+hydrochlorothiazid'),
    ('2C3', 'PARACETAMOL/IBUPROFENE/CAFEINE'),
    ('4N2', 'ISRADIPINE'),
    ('2P5', 'INDOMETACINE'),
    ('4C2', 'FLOCTAFENINE'),
    ('7R4', 'POLYVINYL ALCOHOL ET POVIDONE'),
    ('1S4', 'ALPHA INTERFERON'),
    ('J24', 'echinacea sec+vitamine c+sulfa'),
    ('1ZA', 'HYDROXYCHLOROQUINE'),
    ('1FY', 'EXTRAIT DE SOJA/ISOFLAVONES'),
    ('2B7', 'SALICYLATE DE METHYLE/CAMPHRE'),
    ('J3A', 'MARRAONNIER D''INDE/METESCULETO'),
    ('1V5', 'INSULINE'),
    ('1Q2', 'FAMOTIDINE'),
    ('2S7', 'EPIRUBICINE'),
    ('2JB', 'XYLOMETAZOLINE CHLORHYDRATE'),
    ('3F4', 'PHENIRAMINE/PARACETAMOL/VIT C'),
    ('3X7', 'ISOCONAZOLE'),
    ('2F0', 'PARACETAMOL/CAFEINE/PSEUDOEPHE'),
    ('YM7', 'fer+acide folique'),
    ('2G4', 'SULFATE FERREUX /AC FOLIQUE'),
    ('YMD', 'sulfaguanidine+alverine'),
    ('2R3', 'TILIQUINOL/TILBROQUINOL'),
    ('YK1', 'ebastine'),
    ('YX1', 'levetiracetam'),
    ('YH5', 'dexketoprofene'),
    ('1X9', 'KETOCONAZOLE'),
    ('1KP', 'DEXAMETHASONE'),
    ('F5F', 'BROMAZEPAM'),
    ('J25', 'paracetamel+promethazine'),
    ('1L2', 'GRANISETRON'),
    ('1PZ', 'CARBOMERE 974'),
    ('1W2', 'LACTOBACILUS ACIDOPHILUS'),
    ('1X2', 'TERBINAFINE'),
    ('YU7', 'insuline glargine'),
    ('F2F', 'CHLORPROMAZINE'),
    ('2N8', 'METHYLCLOTHIAZIDE/TRIAMTERENE'),
    ('1R7', 'FRAMYCETINE'),
    ('1YV', 'AC SALICYLIQUE /ACIDE ACETIQUE'),
    ('1KE', 'PREDNISOLONE'),
    ('1NZ', 'SILYMARINE'),
    ('J27', 'methylergonovine'),
    ('C6C', 'FLUVASTATINE'),
    ('1WR', 'MEQUINOL'),
    ('1QD', 'VARDENAFIL'),
    ('YX3', 'levocarbastine'),
    ('1LA', 'LEVONORGESTREL'),
    ('F3F', 'CHLORDIAZEPOXIDE/CLIDINIUM BRO'),
    ('2G8', 'FER/AC FOLIQUE/VIT B12/LYSINE'),
    ('5R8', 'LINCOMYCINE'),
    ('C3C', 'CIPROFIBRATE'),
    ('C4C', 'FENOFIBRATE'),
    ('1PY', 'CARBOMERE 980'),
    ('YFB', 'paracetamol+cafeine+phenylephr'),
    ('YE3', 'chlorzoxazone+paracetamol'),
    ('1E6', 'TRETINOINE'),
    ('1KU', 'DESONIDE'),
    ('1N7', 'BISOPROLOL/HYDROCHLOROTHIAZIDE'),
    ('1X7', 'FENTICONAZOLE'),
    ('1Q5', 'LANSOPRAZOLE'),
    ('YDA', 'nitroscanate'),
    ('1T2', 'ENOXAPARINE SODIQUE'),
    ('4N4', 'NICARDIPINE'),
    ('YGI', 'pheniramine+tetryzoline+thiome'),
    ('1FL', 'NOMEGESTEROL'),
    ('1FJ', 'CHLORMADINONE'),
    ('J50', 'pregabaline'),
    ('F5G', 'PRAZEPAM'),
    ('J60', 'acide salicylique+camphre+reso'),
    ('1VX', 'LYSOZYME/PYRIDOXINE'),
    ('3D3', 'SIMETHICONE/SELS METALLOIDES'),
    ('1M6', 'PREGABALINE'),
    ('1S7', 'RITUXIMAB'),
    ('1YU', 'HYDROCOTYLE'),
    ('2MC', 'MAGNESIUM/PYRIDOXINE'),
    ('1MZ', 'MAGNESIUM'),
    ('1ZN', 'ATOVAQUONE/PROGUANIL'),
    ('2MA', 'MAGNESIUM HYDROXYDE/CALCIUM/AL'),
    ('1JX', 'EAU DE MER'),
    ('1KZ', 'DEXAMETHASONE/NEOMYCINE/POLYMY'),
    ('3P6', 'ALPHA AMYLASE'),
    ('7R2', 'POLYMIXINE B/NEOMYCINE/DEXAMET'),
    ('1WS', 'METHOXSALENE'),
    ('F3G', 'MEXAZOLAM'),
    ('1LC', 'DESOGESTREL/ETHINYLESTRADIOL'),
    ('YZ5', 'meloxicam'),
    ('1ZC', 'MEFLOQUINE'),
    ('3B3', 'MENTHOL/GAIACOL/EUCALYPTUS/TER'),
    ('YCJ', 'nicotinate de methyle+glycol m'),
    ('YYD', 'meropenem'),
    ('YME', 'sulfamethoxypyrazine+pyrimetha'),
    ('YHA', 'phloroglucinol+simeticone'),
    ('1UB', 'ALVERINE/SIMETICONE'),
    ('1HB', 'METHYLERGOMETRINE'),
    ('6R4', 'JOSAMYCINE'),
    ('1I1', 'EXTRAITS VEGETAUX ET HUILES ES'),
    ('3I3', 'POLIVITAMINES ET OLIGOELEMENTS'),
    ('2I3', 'COMPLEXES VITAMINIQUES ET DE P'),
    ('1MX', 'CHLORURE DE POTASSIUM'),
    ('E3E', 'SULFATE DE BARYUM'),
    ('1KC', 'TRIAMCINOLONE'),
    ('2J2', 'MOMETASONE'),
    ('3C3', 'PARACETAMOL/CAFEINE/CODEINE'),
    ('2S8', 'VINORELBINE DITARTRATE'),
    ('1K1', 'MECLOZINE/PYRIDOXINE'),
    ('2TS', 'CODEINE/SULFOGAIACOL'),
    ('2TM', 'CODEINE'),
    ('2TN', 'CODEINE/BENZOATE DE SODIUM'),
    ('1TL', 'BENZOATE DE SODIUM/EXTRAITS VE'),
    ('1KG', 'ACETATE DE METHYL /PREDNISOLON'),
    ('1FB', 'CARBIMAZOLE'),
    ('2KH', 'PREDNISOLONE/NÉOMYCINE'),
    ('1KQ', 'DIFLUCORTOLONE'),
    ('YN7', 'filgastrim'),
    ('1XC', 'PARAFFINE LIQUIDE/VASELINE/CIR'),
    ('YWD', 'vitamines B1 B2 B6 B12'),
    ('1C9', 'ERGOTAMINE/CAFEINE/PARACETAMOL'),
    ('YW8', 'leontopodium alpinum+mentha pi'),
    ('Y95', 'calendula officinalis+leontopo'),
    ('3I4', 'CALCIUM/VITC/MAGNESIUM/NICOTIN'),
    ('2P3', 'MORNIFLUMATE'),
    ('YAF', 'minoxidil'),
    ('1S3', 'TAMOXIFENE'),
    ('F1F', 'NIAPRAZINE'),
    ('1GF', 'DIHYDROGENOPHOSPHATE DE SODIUM'),
    ('1Y5', 'TIMOLOL'),
    ('9R5', 'NORFLOXACINE/TINIDAZOLE'),
    ('1UF', 'DROTAVERINE'),
    ('YJ1', 'drotaverine+paracetamol+cafein'),
    ('7R3', 'POLYMYXINE B/NEOMYCINE/GRAMICI'),
    ('YT9', 'hydroxypolymaltose ferrique'),
    ('A1A', 'LEVOMEPROMAZINE'),
    ('1EG', 'URIDINE/CYTIDINE'),
    ('YF3', 'clopidogrel'),
    ('J80', 'Méthoxy polyéthylène glycol-ép'),
    ('1YJ', 'HUILE DE FOIE DE POISSON/OXYDE'),
    ('YOC', 'tobramycine'),
    ('1NG', 'FUMETERRE'),
    ('4F7', 'OLOPATADINE'),
    ('YJ2', 'eau de Bleuet PH neutre'),
    ('YY3', 'lomefloxacine'),
    ('2TK', 'NOSCAPINE/PROMETHAZINE'),
    ('YU0', 'hypromellose'),
    ('A2A', 'PIMOZIDE'),
    ('1W7', 'CITRATE TRISODIQUE DIHYDRATE'),
    ('2FA', 'LYNESTRENOL'),
    ('1G8', 'HYDROXYDE FER/ACIDE FOLIQUE'),
    ('1MY', 'LACTATE ET CITRATE DE MAGNESIU'),
    ('A7A', 'FLUPHENAZINE'),
    ('1JD', 'LYSAT D''ANANAS BARBARIAE'),
    ('2B3', 'LIDOCAINE/SULFATE DE MAGNESIUM'),
    ('YLJ', 'SRO(solute de rehydratation or'),
    ('F4G', 'NITRAZEPAM'),
    ('8R1', 'PHENOXYMETHYLPENICILLINE'),
    ('3P7', 'PHENAZONE/LIDOCAINE'),
    ('1FG', 'ESTRIOL'),
    ('1J2', 'BAMBUTEROL'),
    ('1NC', 'BOLDINE/SELS DE SODIUM'),
    ('1YK', 'OXYDE DE ZINC'),
    ('1TU', 'TEREBENTHINE'),
    ('3F5', 'PHENYLEPHRINE/DIPHENYLDRAMINE/'),
    ('9R1', 'FOSFOMYCINE'),
    ('3R1', 'POLYMYXINE B/NEOMYCINE/FLUDROC'),
    ('YEC', 'pantoprazole'),
    ('YFA', 'paracetamol+cafeine+chlorpheni'),
    ('1W5', 'OPIUM/AC BENZOIQUE/ANIS'),
    ('2I6', 'L-ASPARTATE DE L-ARGININE'),
    ('1FS', 'BROMOCRIPTINE'),
    ('1TN', 'BROMHEXINE CHLORHYDRATE/SULFOG'),
    ('1TK', 'BENZOATE DE NA /SULFOGAIACOL'),
    ('F5H', 'PASSIFLORE/AUBEPINE'),
    ('YRG', 'vitamine A+vitamines B1 B2 B3'),
    ('YWB', 'vitamines A+D3+C'),
    ('7R7', 'PENICILLINE G'),
    ('9R7', 'PEFLOXACINE'),
    ('Y76', 'benzylpenicilline'),
    ('2D5', 'DIMETICONE/GAIAZULENE'),
    ('Y43', 'alginate de magnesium+hydroxyd'),
    ('1KM', 'DEXAMETHASONE/SALICYLAMIDE'),
    ('1S6', 'PEGINTERFERON ALFA-2A'),
    ('1FT', 'SERENOA REPENS'),
    ('E2E', 'DIPYRIDAMOLE'),
    ('3F0', 'BENZALKONIUM CHLORURE'),
    ('YGA', 'paracetamol+phenyledrine+chlor'),
    ('2D0', 'PHASPHATE D''ALUMINIUM'),
    ('4R7', 'METHYLENECYCLINE'),
    ('3P9', 'EXTRAIT D''AVOCAT ET DE SOJA'),
    ('YQ6', 'glucosamine'),
    ('1GQ', 'SENE/CASCARA'),
    ('2X6', 'CICLOPIROXOLAMINE'),
    ('1PI', 'TROPICAMIDE'),
    ('2D8', 'OXYDE D''ALU DE MAGNESIUM / OXE'),
    ('4R8', 'MINOCYCLINE'),
    ('3F8', 'ACIDE N-ACETYLASPARTYLGLUTAMIQ'),
    ('1P5', 'FENOPROFENE'),
    ('YOI', 'trinitrate glyceryle'),
    ('YHE', 'pioglitazone'),
    ('A8A', 'PIPOTIAZINE'),
    ('8R6', 'ACIDE PIPEMIDIQUE'),
    ('2F3', 'MEQUITAZINE'),
    ('1JV', 'TIXOCORTOL'),
    ('1QA', 'YOHIMBINE'),
    ('1QF', 'ACIDE NICOTINIQUE'),
    ('J1J', 'TRIMEBUTINE/RUSCOGENINES'),
    ('1FM', 'PROGESTERONE'),
    ('1TM', 'BENZOATE DE SODIUM/GUAIFENESIN'),
    ('2TR', 'CODEINE/GAIACOL'),
    ('1J8', 'BUDESONIDE'),
    ('1TE', 'ESSENCE D''EUCALYPTUS/TEREBENTI'),
    ('YYG', 'mesterolone'),
    ('9RE', 'PRISTINAMYCINE'),
    ('1VW', 'RHUBARBE/AC SALICYLIQUE'),
    ('F4H', 'CAMOMILLE/PASSIFLORE/GELSEMIUM'),
    ('YIC', 'rabeprazole'),
    ('1WP', 'SULFATE DE CUIVRE ET ZINC'),
    ('E5E', 'SODIUM ET MEGLUMINE AMIDOTRIZO'),
    ('YK7', 'erythropoietine'),
    ('1GE', 'BILE DE BOEUF/GELATINE/GLYCERO'),
    ('3D2', 'SIMETHICONE/HYDROXYDES D''ALU E'),
    ('D4D', 'LIPIDES/GLUCIDES/PROTIDES'),
    ('YIF', 'resperidone'),
    ('Y48', 'ambroxol+salbutamol+guaifenesi'),
    ('2I5', 'GINSENG/OLIGOELEMENTS'),
    ('1JK', 'BENZODODECINIUM'),
    ('1JY', 'ACETYLCYSTEINE/TUAMINOHEPTANE/'),
    ('3F6', 'PHENYLEPHRINE/DIMENHYDRINE/CAF'),
    ('1JZ', 'EPHEDRINE/AC BENZOIQUE'),
    ('YD2', 'chlorhydrate de naphazoline'),
    ('H2A', 'IMMUNOGLOBULINE HUMAINE ANTI D'),
    ('1UA', 'PRIFINIUM BROMURE'),
    ('Y87', 'bromure de prifinium+paracetam'),
    ('3P4', 'TRYPSINE /RIBONUCLEASE/CHYMOTR'),
    ('9RA', 'RIFAMYCINE/PREDNISOLONE'),
    ('G4G', 'CHLORURES DE SOD DE POTA ET DE'),
    ('G5G', 'SELS MINERAUX'),
    ('2F5', 'RUPATADINE'),
    ('1H5', 'ISOSORBIDE DINITRATE'),
    ('F8F', 'CLONAZEPAM'),
    ('YFE', 'paracetamol+chlorpheniramine+s'),
    ('1I3', 'ARGININE/AC MALIQUE'),
    ('2D9', 'OXYDE D''ALUMINIUM'),
    ('6R5', 'ROXITHROMYCINE'),
    ('H1B', 'VIRUS VIVANT ATTENUE'),
    ('1W3', 'LACTOPROTEINES METHYLENIQUES'),
    ('1YZ', 'MENTHOL/AC SALICYLIQUE/SOUFRE'),
    ('1C7', 'PIZOTIFENE'),
    ('2I2', 'ASPARTATE D''ARGININE/VIT C'),
    ('3C4', 'PARACETAMOL/CAFEINE/PROPYPHENA'),
    ('F3H', 'BELLADONE/CALENDULA/ACONITUM'),
    ('Y73', 'benzocaine+dodeclonium+enoxolo'),
    ('2TI', 'CLOPERASTINE FENDIZOATE'),
    ('7R5', 'PIVMECILLINAM'),
    ('ZX3', 'SULFURE DE SELENIUM'),
    ('YOH', 'trimethoprime+sulfamethoxypyri'),
    ('1WZ', 'IRGASAN DP 300'),
    ('1F1', 'OXATOMIDE'),
    ('1J3', 'FLUTICASONE/SALMETEROL'),
    ('1TS', 'FENSPIRIDE'),
    ('YKJ', 'serum antivenimeux polyvalent'),
    ('YU2', 'immunoglobuline equine rabique'),
    ('1D5', 'SIMETHICONE'),
    ('YC9', 'chlorhexidine+sulfadiazine'),
    ('1ND', 'SILYMARINE/VITAMINES'),
    ('1T1', 'ACENOCOUMAROL'),
    ('1PH', 'CYCLOPENTOLATE'),
    ('1F8', 'DEXCHLORPHENIRAMINE'),
    ('1D0', 'DIOSMECTINE'),
    ('G2G', 'SODIUM CHLORURE'),
    ('1TF', 'L CISTINE'),
    ('J48', 'vitamine C+ clou de girofle'),
    ('B2B', 'CITICOLINE'),
    ('2R8', 'NEOMYCINE/POLYMIXINE B/DEXAMET'),
    ('9RH', 'NEOMYCINE/POLYMYXINE/NYSTATINE'),
    ('3F9', 'AC SALICYLIQUE/BORATE DE NA/AC'),
    ('1GI', 'SORBITOL'),
    ('1H1', 'SOTALOL'),
    ('2C2', 'PARACETAMOL/DICLOFENAC'),
    ('1P2', 'ACIDE MEFENAMIQUE'),
    ('2MB', 'MAGNESIUM SULFATE/LEVURE'),
    ('1UE', 'DIHEXYVERINE'),
    ('1B0', 'ARNICA/ZINCUM SARCOLACTICUM/DE'),
    ('2X3', 'TOLNAFTATE'),
    ('1YD', 'ESDEPALLETHRINE/PIPERONYLE'),
    ('2B2', 'IDROCILAMIDE'),
    ('1U7', 'TIANEPTINE'),
    ('YO6', 'flucloxacilline'),
    ('7R9', 'BENZATHINE/PHENOXYMETHYLPENICI'),
    ('1LF', 'NORGESTREL/ETHINYLSETRADIOL'),
    ('2KJ', 'TRIAMCINOLONE/NEOMYCINE/NYSTAT'),
    ('2I1', 'ASPARTATE D''ARGININE'),
    ('1L5', 'METOCLOPRAMIDE'),
    ('B8B', 'NAFTIDROFURYL'),
    ('1H3', 'THEODRENALINE/CAFEDRINE'),
    ('YN4', 'fer+vitamines+oligoelements+mi'),
    ('2FI', 'MEDROXYPROGESTERONE/MEPROBAMAT'),
    ('1JL', 'EAU DE MER/CUIVRE'),
    ('1JB', 'EAU DE MER/MANGANESE'),
    ('YJ6', 'eau de mer hypertonique'),
    ('2KA', 'DEXAMETHAZONE/OXYTETRACYCLINE'),
    ('F1H', 'ZOLPIDEM'),
    ('1I9', 'MALATE DE CITRULLINE'),
    ('Y88', 'budesonide+formoterol'),
    ('F9G', 'ESCHSHOLTZIA/AUBEPINE/MAGNESIU'),
    ('1FC', 'TETRACOSACTIDE'),
    ('1FX', 'OXYTOCINE'),
    ('1B7', 'LEVOMENTHOL/RESORCINOL'),
    ('F6G', 'ETIFOXINE'),
    ('YCE', 'niclosamide+levamisole'),
    ('YYF', 'mesalazine'),
    ('YP7', 'gelatine+belladone'),
    ('1SA', 'ACETYLLEUCINE'),
    ('2S3', 'DOCETAXEL'),
    ('E1E', 'IOXITALAMATE DE MEGLUMINE'),
    ('E4E', 'IOXITALAMATE DE SODIUM'),
    ('F2G', 'LORAZEPAM'),
    ('2N6', 'ATENOLOL/CHLORTALIDONE'),
    ('2N5', 'ATENOLOL/NIFEDIPINE'),
    ('2N7', 'BENDROFLUMETHIAZIDE/RESERPINE'),
    ('Y51', 'amlodipine+atenolol'),
    ('9RL', 'TERNIDAZOLE/NEOMYCINE/NYSTATIN'),
    ('2TF', 'TERPINE/CODEINE'),
    ('1TV', 'TERPINE/EXTRAITS VEGETAUX'),
    ('H2B', 'FRAGMENTS D'' IG D''ORIGINE TETA'),
    ('4R9', 'TETRACYCLINE'),
    ('Y20', 'acide folique+fer ferreux+vita'),
    ('1F2', 'ALIMEMAZINE'),
    ('3P5', 'SODIUM CHONDROITINE SULFATE'),
    ('A5A', 'TIAPRIDE'),
    ('9RI', 'ORNIDAZOLE'),
    ('1G0', 'SULFATE FERREUX/AC ASCORBIQUE'),
    ('YID', 'racecadotril'),
    ('J2J', 'CARRAGHENATES/OXYDE DE ZINC ET'),
    ('2KB', 'DEXAMETHAZONE/TOBRAMYCINE'),
    ('Y22', 'acide glutamique'),
    ('2D2', 'ACIDE ALGINIQUE/HYDROXYDE D''AL'),
    ('1I0', 'ASCORBATE DE LYSINE ET CALCIUM'),
    ('G7G', 'AC AMINES/VITAMINES/ELECTROLYT'),
    ('1G4', 'FER/MANGANESE/CUIVRE'),
    ('C1C', 'SIBUTRAMINE'),
    ('YOF', 'tramadol+paracetamol'),
    ('F6F', 'CHLORAZEPATE DIPOTASSIQUE'),
    ('1Y1', 'TRAVOPROST'),
    ('YZ9', 'menthol+extrait de plantes'),
    ('5R4', 'TINIDAZOLE/NORFLOXACINE'),
    ('1LE', 'NORETHISTERONE/ETHINYLESTRADIO'),
    ('3F3', 'PARACETAMOL/PSEUDOEPHEDRINE/TR'),
    ('Y58', 'amoxicilline+sulbactam'),
    ('D3D', 'CYPROHEPTADINE / VITAMINES'),
    ('1H6', 'TRINITRINE'),
    ('3N3', 'RAMIPRIL/HYDROCHLOROTHIAZIDE'),
    ('B1C', 'PIRIBEDIL'),
    ('1R6', 'SPECTINOMYCINE'),
    ('2TE', 'PHOLCODINE/TENOATE DE SODIUM'),
    ('1FD', 'ESTIOL / PROGESTERONE / BACILL'),
    ('1JE', 'EUCALYPTUS/TENOATE DE SODIUM'),
    ('2C4', 'PARACETAMOL/EUCALYPTUS/TENOATE'),
    ('1Y9', 'DORZOLAMIDE'),
    ('1TR', 'CHLORPHENOXAMINE/SULFOGAIACOL'),
    ('2TQ', 'CODEINE/ETHYLMORPHINE'),
    ('1Q8', 'SUCRALFATE'),
    ('1W4', 'SACCHAROMYCES BOULARDII'),
    ('YJ9', 'eau de mer purifiee'),
    ('F7F', 'CLOBAZAM'),
    ('YED', 'pantoprazole+domperidone'),
    ('1EH', 'ACIDE URIDINE 5 TRIPHOSPHORIQU'),
    ('H9A', 'NEISSERIA MENINGITIDIS A ET C'),
    ('H9H', 'VACCIN ANTITETANIQUE ADSORBE'),
    ('H1A', 'SALMONELLA TYPHI POLYOSIDE'),
    ('H7H', 'VACCIN PNEUMOCOCCIQUE POLYVALE'),
    ('YZ6', 'meningococcal polysaccharide v'),
    ('H4A', 'VIRUS AMARIL ATTENUE'),
    ('H3A', 'PAPILLOMA VIRUS TYPE 16 ET 18'),
    ('H2H', 'ANATOXINES/VIRUS INACTIVES/ANT'),
    ('YPE', 'vaccin diphterique,tetanique,p'),
    ('H8A', 'NEISSERIA MENINGITIDIS A C W E'),
    ('H8H', 'VIRUS RABIQUE WISTAR'),
    ('H4H', 'ROTAVIRUS HUM VIV ATTENUE'),
    ('B6B', 'IFENPRODIL'),
    ('H1H', 'ANATOXINES/ANTIGENES/VIRUS INA'),
    ('YPI', 'valganciclovir'),
    ('F9F', 'DIAZEPAM'),
    ('YPB', 'vaccin de l''hepatite B recombi'),
    ('1H8', 'TRIMETAZIDINE'),
    ('H5H', 'VIRUS GRIPPAL FRAGMENTE INACTI'),
    ('J5A', 'PETIT HOUX/CASSIS/VIT C'),
    ('J6A', 'RUTOSIDE/AC ASCORBIQUE/ALPHATO'),
    ('Y74', 'benzydamine'),
    ('2KI', 'RIMEXOLONE'),
    ('1JC', 'DIMETHINDENE MALEATE/PHENYLEPH'),
    ('F6H', 'TILLEUL'),
    ('1JP', 'CAMPHRE/MENTHOL'),
    ('1VV', 'MENTHOL/EUCALYPTUS'),
    ('1JQ', 'CAMPHRE/TEREBENTHINE/LEVOMENTH'),
    ('1TW', 'PENTOXYVERINE'),
    ('F1G', 'LOFLAZEPATE D''ETHYLE'),
    ('1KW', 'FLUOCINOLONE/TETRACAINE/NEOMYC'),
    ('1UD', 'TIEMONIUM'),
    ('4F2', 'CHLORHEXIDINE/PHENYLEPHRINE'),
    ('2N1', 'PINDOLOL'),
    ('8R3', 'THIAMPHENICOL'),
    ('1PD', 'RETINOL'),
    ('7R1', 'PICLOXYDINE'),
    ('1I6', 'AC ASCORBIQUE/THIAMINE/INOSITO'),
    ('2GY', 'VIT B12 (HYDROXOCOBALAMINE)'),
    ('1MH', 'CALC/PHOS/FER/VITCEB5/ZINC/MG/'),
    ('YM8', 'fer ferrique+acide folique+vit'),
    ('2G6', 'FER ELEMENTAIRE/VIT B12'),
    ('1MJ', 'VIT B'),
    ('1HD', 'PHYTOMENADIONE'),
    ('1L7', 'METOPIMAZINE'),
    ('1Y2', 'LACTANOPROST'),
    ('1Y6', 'LACTANOPROST/TIMOLOL'),
    ('F4F', 'ALPRAZOLAM'),
    ('2FG', 'ALFUZOSINE'),
    ('2S2', 'CAPECITABINE'),
    ('C9C', 'ORLISTAT'),
    ('5R1', 'MUPIROCINE'),
    ('Y38', 'acides amines+vitamineB6+sels'),
    ('2D7', 'HYDROXYDE D''ALUM ET DE MAGN/SI'),
    ('2S5', 'SUNITINIB MALATE'),
    ('YJ0', 'dorzolamide+timolol'),
    ('1GP', 'SENE'),
    ('YR3', 'gosereline'),
    ('Y33', 'acide zoledronique'),
    ('1C8', 'ZOLMITRIPTAN/OLMITRIPTAN'),
    ('1VZ', 'FLUORURE DE SODIUM'),
    ('A3A', 'OLANZAPINE'),
    ('YMB', 'sucrose ferrique'),
    ('YII', 'rivaroxaban'),
    ('YYB', 'mepivacaine'),
    ('YAD', 'metronidazole+lidocaine+chlorh'),
    ('1J6', 'TERBUTALINE'),
    ('YH0', 'desinfectant pour aquriums tro'),
    ('YY9', 'maleate de chlorpheniramine+am'),
    ('YAI', 'dextromethorphane bromhydrate'),
    ('YCF', 'Nicotinamide+acide glutamique+'),
    ('Y02', 'acephylline piperazine+dipheny'),
    ('1EI', 'ADENOSINE TRIPHOSPHATE'),
    ('2F1', 'LEVOCETIRIZINE'),
    ('Y55', 'amlodipine+valsartan+hydrochlo'),
    ('YV1', 'iobitridol'),
    ('J62', 'Citrulline malate'),
    ('YFC', 'paracetamol+cafeine+pseudoephe'),
    ('YHH', 'polystyroldivinylbenzolsulfona'),
    ('J11', 'carbonate de calcium'),
    ('YF6', 'complexe de chlorure et d''hydr'),
    ('J29', 'gel plaies'),
    ('1TZ', 'OXOMEMAZINE'),
    ('YK3', 'enalapril+hydrochlorothiazide'),
    ('J47', 'basiliximab'),
    ('YE4', 'ciclosporine'),
    ('Y25', 'acide mycophenolique'),
    ('YQ3', 'gluconate de calcium+carbonate'),
    ('3F7', 'SALICYLAMIDE/PARACETAMOL/CAFEI'),
    ('YV2', 'iopromide'),
    ('YHJ', 'pramocaine'),
    ('J61', 'diclofenac+paracetamol+chlorzo'),
    ('Y12', 'acide alphalipoique+calcium+vi'),
    ('YRB', 'vildagliptine'),
    ('4N3', 'LERCANIDIPINE'),
    ('YK6', 'enrofloxacine'),
    ('3R5', 'CEFRADINE'),
    ('1RC', 'VALACICLOVIR'),
    ('1B3', 'ETOFENAMATE'),
    ('Y11', 'acide alendronique'),
    ('1MS', 'SULFATE DE ZINC'),
    ('YNF', 'telmisartan+hydrochlorothiazid'),
    ('YDD', 'ofloxacine+ornidazole'),
    ('2B8', 'SALICYLATE DE METHYLE/MENTHOL'),
    ('YAB', 'metronidazole+furazolidone'),
    ('YF1', 'citrate ferrique+lysine+vitami'),
    ('YX0', 'leuprolide'),
    ('YG0', 'cyanocobalamine+acide folique+'),
    ('YM2', 'fer ferrique(hydroxypolymaltos'),
    ('YWA', 'L-Aspartate de magnesium'),
    ('YX4', 'levocarnitine'),
    ('1F9', 'FEXOFENADINE'),
    ('J33', 'acetate d''hydrocortisone+allan'),
    ('YV4', 'irbesartan'),
    ('YV5', 'irbesartan+hydrochlorothiazide'),
    ('YPG', 'vaccin pneumococcique polysacc'),
    ('YOJ', 'ulipristal'),
    ('J96', 'paracetamol+phenylephedrine+ca'),
    ('YEI', 'paracetamol+butylbromure de sc'),
    ('YOE', 'torasemide'),
    ('YDB', 'nitroxoline'),
    ('YB7', 'cefepim'),
    ('YU6', 'insuline asparte'),
    ('J93', 'aiguille securisee'),
    ('Y85', 'brimonidine tartrate'),
    ('J69', 'diclofenac+parcetamil+chlorphe'),
    ('Y41', 'adepfenin+prophynazone'),
    ('YW6', 'lavande+romarin+thym(essence)+'),
    ('YKD', 'salbutamol+bromhexine+gaifenes'),
    ('YRC', 'vildagliptine+metformine'),
    ('YND', 'telmisartan'),
    ('YB8', 'cefoperazone'),
    ('YB9', 'cefoperazone+sulbactam'),
    ('T2', 'TEST GROSSESSE'),
    ('YRF', 'virus grippaux inactives'),
    ('Y82', 'bisoprolol'),
    ('YBF', 'nebivolol'),
    ('YLB', 'sitagliptin'),
    ('YL2', 'etoricoxib'),
    ('YDG', 'otilonium bromure'),
    ('YFH', 'paracetamol+dextropropoxyphene'),
    ('YO5', 'fosinopril+hydrochlorothiazide'),
    ('YD0', 'chlorhydrate d''Amyleine'),
    ('J01', 'paracetamol+lidocaine'),
    ('YGC', 'paracetamol+scopolamine'),
    ('YAE', 'metronidazole+neomycine+nystat'),
    ('J16', 'fer+lysine+zinc+ vit B9 +vit B'),
    ('1A6', 'LIDOCAINE/EPINEPHRINE'),
    ('YB2', 'carboplatin'),
    ('YMC', 'sulfadiazine+chlorhexidine'),
    ('Y72', 'benzoate de benzyle+vareniclin'),
    ('YO4', 'fluprednidene+miconazole'),
    ('YO2', 'fluorouracil+acide salicylique'),
    ('YP1', 'fumarate ferreux+cyanocobalami'),
    ('J44', 'sulfate de zinc+vit B1+B2+B6+B'),
    ('J15', 'finasteride'),
    ('Y42', 'alendronate monosodique'),
    ('YR1', 'golu kola+metronidazole+micona'),
    ('Y66', 'articaine+adrenaline'),
    ('YX8', 'lidocaine+cetrimide'),
    ('YT4', 'hydrocortisone+framycetine'),
    ('YHK', 'dexamethasone+thymol'),
    ('YH3', 'dexamethasone+gaiacol+phenol'),
    ('1TH', 'BROMHEXINE/AMOXICILLINE'),
    ('YE1', 'chlorure de sodium+chlorure de'),
    ('Y80', 'bilastine'),
    ('YIG', 'retinol+vitamine D3+cyanocobal'),
    ('YH6', 'dexpantenol'),
    ('YS5', 'Peroxyde de benzoyle'),
    ('YE6', 'cinitapride'),
    ('YF2', 'clebopride+simethicone'),
    ('Y93', 'calcium chlorure'),
    ('YPF', 'vaccin meningococcique conjugu'),
    ('Y24', 'acide mefenamique+dicyclomine'),
    ('YU1', 'ibuprofene+codeine'),
    ('YBD', 'N-acetylcysteine+ambroxol'),
    ('J95', 'NYSTATINE'),
    ('YKB', 'ratavirus humain souche RIX441'),
    ('YN3', 'fer+vitamines B1 B3 B6+ acide'),
    ('YN0', 'fer+acide folique+vitamines'),
    ('J36', 'paracetamol+chlorpheniramine'),
    ('Y23', 'acide hyaluronique+glucosamine'),
    ('YK5', 'enoxolone+lidocaine+erysimum'),
    ('YR7', 'Guarana+cafeine+mineraux+vitam'),
    ('YWC', 'vitamines B1 B2 B5 B6 B8 B9 B1'),
    ('J06', 'thiamine'),
    ('J19', 'amphotericine B'),
    ('J21', 'alginate de sodium+bicarbonate'),
    ('J32', 'tanin officinal+extrait fluide'),
    ('J00', 'dimeticone+saccharose+sorbitol'),
    ('YB5', 'carvedilol'),
    ('J97', 'povidone iodée+metronidazole'),
    ('1FP', 'LEVOTHYROXINE'),
    ('C7C', 'PRAVASTATINE'),
    ('J71', 'terazosin+hydrochlorothiazide'),
    ('J70', 'metronidazolez+clotrimazole'),
    ('J92', 'rifaximine'),
    ('J09', 'tinazole+miconazole+neomycine'),
    ('J46', 'ondosetron'),
    ('J10', 'glucosamine+chondroïtine+sulfa'),
    ('J14', 'ubidecarenone selenium+vit E'),
    ('J91', 'polymixineB+neomycine+bacitric'),
    ('J64', 'clindamycine+clotrimazole'),
    ('J34', 'metoprolol'),
    ('J20', 'gatifloxacine+dorzolamide+timo'),
    ('1F0', 'KETOTIFENE'),
    ('J99', 'sodium hyaluronate'),
    ('J40', 'methocarbomol'),
    ('J45', 'antitoxine tetanique'),
    ('DCI TEST', 'Test'),
    ('TELMISARTAN', 'TELMISARTAN'),
    ('CHLORHYDRATE DE LEVO', 'CHLORHYDRATE DE LEVOCETIRIZINE'),
    ('IODURE DE POTASSIUM', 'IODURE DE POTASSIUM'),
    ('CHLORHYDRATE DE FEXO', 'CHLORHYDRATE DE FEXOFENADINE')
ON CONFLICT DO NOTHING;
