-- Référentiel médicament (BDPM) : socle du rapprochement automatique produit ↔ DCI, dosage, forme,
-- groupe générique et substituts

CREATE FUNCTION ref_normaliser(texte text) RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS
$$
SELECT btrim(regexp_replace(
  upper(translate(replace(replace(texte, 'œ', 'oe'), 'Œ', 'OE'),
                  'àâäáãåéèêëíìîïóòôöõúùûüýÿçñÀÂÄÁÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÝŸÇÑ',
                  'aaaaaaeeeeiiiiooooouuuuyycnAAAAAAEEEEIIIIOOOOOUUUUYYCN')),
  '[^A-Z0-9]+', ' ', 'g'))
$$;

-- Groupe générique : un princeps et ses génériques, substituables entre eux.
CREATE TABLE ref_groupe_generique (
  id      integer      PRIMARY KEY,
  libelle varchar(500) NOT NULL
);

-- Substance (principe actif ou fraction thérapeutique) : code substance BDPM.
CREATE TABLE ref_substance (
  code               varchar(10)  PRIMARY KEY,
  libelle            varchar(255) NOT NULL,
  libelle_normalise  varchar(255) GENERATED ALWAYS AS (ref_normaliser(libelle)) STORED NOT NULL
);

CREATE INDEX ref_substance_libelle_normalise_idx ON ref_substance (libelle_normalise);

-- Dénomination commune : la molécule « de sortie » d'une composition (AMOXICILLINE, et non son
-- trihydrate). dci_id relie à la DCI du catalogue quand le libellé correspond.
CREATE TABLE ref_dci (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle            varchar(255) NOT NULL CONSTRAINT ref_dci_libelle_uk UNIQUE,
  libelle_normalise  varchar(255) GENERATED ALWAYS AS (ref_normaliser(libelle)) STORED NOT NULL,
  dci_id             integer REFERENCES dci (id) ON DELETE SET NULL
);

CREATE INDEX ref_dci_libelle_normalise_idx ON ref_dci (libelle_normalise);
CREATE INDEX ref_dci_dci_idx ON ref_dci (dci_id);

-- Spécialité pharmaceutique : une ligne par code CIS.
CREATE TABLE ref_specialite (
  cis                   varchar(8)   PRIMARY KEY,
  libelle               varchar(255) NOT NULL,
  libelle_normalise     varchar(255) GENERATED ALWAYS AS (ref_normaliser(libelle)) STORED NOT NULL,
  forme                 varchar(120),
  forme_normalisee      varchar(120) GENERATED ALWAYS AS (ref_normaliser(forme)) STORED,
  voies                 varchar(150),
  titulaire             varchar(100),
  commercialisee        boolean      NOT NULL DEFAULT TRUE,
  composition           text,
  groupe_generique_id   integer REFERENCES ref_groupe_generique (id),
  -- PRINCEPS, GENERIQUE, GENERIQUE_SUBSTITUABLE, GENERIQUE_COMPLEMENTARITE_POSOLOGIQUE ; NULL hors groupe.
  type_generique        varchar(40)
    CONSTRAINT ref_specialite_type_generique_check CHECK (type_generique IN
      ('PRINCEPS', 'GENERIQUE', 'GENERIQUE_SUBSTITUABLE', 'GENERIQUE_COMPLEMENTARITE_POSOLOGIQUE')),
  princeps_du_groupe    varchar(255)
);

CREATE INDEX ref_specialite_libelle_normalise_idx ON ref_specialite (libelle_normalise);
-- Rapprochement approché de la marque (premier mot) : pg_trgm est posé par V1.0.1.
CREATE INDEX ref_specialite_marque_trgm_idx ON ref_specialite USING gin ((split_part(libelle_normalise, ' ', 1)) gin_trgm_ops);
CREATE INDEX ref_specialite_groupe_idx ON ref_specialite (groupe_generique_id);
CREATE INDEX ref_specialite_forme_idx ON ref_specialite (forme_normalisee);

-- Composition : une ligne par substance et par spécialité.
-- nature = SA (substance active) ou FT (fraction thérapeutique). Le dosage porte sur la FT quand elle
-- existe : c'est lui qui sert à comparer deux spécialités. dosage_valeur / dosage_unite ne sont
-- renseignés que si le texte est un nombre suivi d'une unité simple ; sinon seul dosage_texte fait foi
-- (homéopathie « 4CH à 30CH », « qsp »…).
CREATE TABLE ref_specialite_composition (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cis              varchar(8)  NOT NULL REFERENCES ref_specialite (cis) ON DELETE CASCADE,
  substance_code   varchar(10) NOT NULL REFERENCES ref_substance (code),
  dci_id           integer REFERENCES ref_dci (id),
  nature           varchar(2)  NOT NULL CONSTRAINT ref_specialite_composition_nature_check CHECK (nature IN ('SA', 'FT')),
  dosage_texte     varchar(120),
  dosage_valeur    numeric(18, 6),
  dosage_unite     varchar(20),
  reference_dosage varchar(120),
  -- Dosage ramené à une unité commune (mg pour les masses) : 0,5 g et 500 mg se comparent.
  unite_canon      varchar(20) GENERATED ALWAYS AS (
    CASE dosage_unite WHEN 'mg' THEN 'mg' WHEN 'g' THEN 'mg' WHEN 'microgrammes' THEN 'mg' ELSE dosage_unite END) STORED,
  dosage_canon     numeric(24, 6) GENERATED ALWAYS AS (
    CASE dosage_unite WHEN 'g' THEN dosage_valeur * 1000 WHEN 'microgrammes' THEN dosage_valeur / 1000 ELSE dosage_valeur END) STORED
);

CREATE INDEX ref_specialite_composition_cis_idx ON ref_specialite_composition (cis);
CREATE INDEX ref_specialite_composition_substance_idx ON ref_specialite_composition (substance_code);
CREATE INDEX ref_specialite_composition_dci_idx ON ref_specialite_composition (dci_id);

-- Rubriques du RCP : texte libre, repris tel quel. Séparé car volumineux et rarement lu.
CREATE TABLE ref_specialite_rcp (
  cis                varchar(8) PRIMARY KEY REFERENCES ref_specialite (cis) ON DELETE CASCADE,
  indications        text,
  posologie          text,
  contre_indications text
);

-- Substituts : pour une spécialité, les autres membres de son groupe générique.
CREATE VIEW v_ref_substitut AS
SELECT a.cis       AS cis,
       b.cis       AS cis_substitut,
       b.libelle   AS libelle_substitut,
       b.type_generique,
       b.commercialisee,
       a.groupe_generique_id
FROM ref_specialite a
         JOIN ref_specialite b ON b.groupe_generique_id = a.groupe_generique_id AND b.cis <> a.cis;

COMMENT ON TABLE ref_specialite IS 'Référentiel BDPM : spécialités (CIS). Lecture seule, rechargé par scripts/referentiel-bdpm/sql.';
COMMENT ON TABLE ref_specialite_composition IS 'Référentiel BDPM : substances, nature SA/FT et dosage de chaque spécialité.';
COMMENT ON TABLE ref_groupe_generique IS 'Référentiel BDPM : groupes génériques (table de substitution).';
COMMENT ON TABLE ref_dci IS 'Référentiel BDPM : dénominations communes ; dci_id relie à la DCI du catalogue.';
