-- Objectifs mensuels du pilotage : une valeur par indicateur et par mois ; un mois sans objectif n'a pas de ligne.
CREATE TABLE IF NOT EXISTS pilotage_objectif
(
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicateur    VARCHAR(30)      NOT NULL,
  annee         INTEGER          NOT NULL,
  mois          INTEGER          NOT NULL CHECK (mois BETWEEN 1 AND 12),
  valeur        DOUBLE PRECISION NOT NULL,
  modifie_par   INTEGER REFERENCES app_user (id) ON DELETE SET NULL,
  modifie_le    TIMESTAMP        NOT NULL,
  CONSTRAINT pilotage_objectif_unique UNIQUE (indicateur, annee, mois)
);

-- Le titulaire fixe ses objectifs : droit de modification sur l'onglet (l'administrateur l'a déjà).
UPDATE nav_item_role
SET can_edit = TRUE
WHERE role_name = 'ROLE_PHARMACIEN'
  AND nav_item_id = (SELECT id FROM nav_item WHERE code = 'pilotage.objectifs');
