-- Fiche client, lot 2 : dossier de sécurité du patient (docs/PLAN-FICHE-CLIENT.md).

-- Un dossier par client, créé à la première saisie.
CREATE TABLE customer_dossier_sante (
  customer_id     integer      NOT NULL PRIMARY KEY REFERENCES customer (id) ON DELETE CASCADE,
  -- Libellés libres : diabète, hypertension, insuffisance rénale…
  pathologies     jsonb        NOT NULL DEFAULT '[]'::jsonb,
  grossesse       boolean      NOT NULL DEFAULT FALSE,
  -- Terme prévu : la grossesse n'a plus lieu d'alerter au-delà.
  date_terme      date,
  allaitement     boolean      NOT NULL DEFAULT FALSE,
  poids_kg        numeric(5, 2) CONSTRAINT customer_dossier_sante_poids_check CHECK (poids_kg > 0),
  date_pesee      date,
  note            text,
  updated_at      timestamp    NOT NULL DEFAULT now(),
  updated_by_id   integer      REFERENCES app_user (id)
);

-- Une allergie porte sur une molécule (dci) — c'est ce qui déclenche l'alerte à la vente — ou,
-- à défaut, sur un libellé libre (arachide, latex…) affiché sans rapprochement automatique.
CREATE TABLE customer_allergie (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   integer      NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  dci_id        integer      REFERENCES dci (id),
  libelle       varchar(150),
  reaction      varchar(255),
  created_at    timestamp    NOT NULL DEFAULT now(),
  CONSTRAINT customer_allergie_objet_check CHECK (dci_id IS NOT NULL OR libelle IS NOT NULL),
  CONSTRAINT customer_allergie_dci_uk UNIQUE (customer_id, dci_id)
);

CREATE INDEX customer_allergie_customer_idx ON customer_allergie (customer_id);

-- Trace des délivrances faites malgré une alerte : qui a délivré, qui a autorisé, pourquoi.
CREATE TABLE alerte_sante_derogation (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      integer      NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  produit_id       integer      NOT NULL REFERENCES produit (id),
  alertes          text         NOT NULL,
  motif            varchar(255) NOT NULL,
  user_id          integer      NOT NULL REFERENCES app_user (id),
  autorise_par_id  integer      NOT NULL REFERENCES app_user (id),
  created_at       timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX alerte_sante_derogation_customer_idx ON alerte_sante_derogation (customer_id);

-- Délivrer malgré une allergie connue : droit du pharmacien. Les autres profils passent par sa clé.
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-forcer-alerte-sante',
       'Délivrer malgré une alerte santé (allergie)',
       NULL,
       NULL,
       id,
       0,
       3,
       'ACTION',
       TRUE
FROM nav_item
WHERE code = 'ventes'
ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete,
                           can_export, can_execute)
SELECT n.id, r.role_name, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE
FROM nav_item n
       CROSS JOIN (VALUES ('ROLE_ADMIN'), ('ROLE_PHARMACIEN')) AS r(role_name)
WHERE n.code = 'pr-forcer-alerte-sante'
  AND EXISTS (SELECT 1 FROM authority a WHERE a.name = r.role_name)
ON CONFLICT (nav_item_id, role_name) DO UPDATE SET can_execute = TRUE;
