-- Grille de produits favoris du comptoir (docs/PLAN-ANALYSE-COMPARATIVE-INTERFACE-VENTE-COMPTOIR.md §3)
-- et substitution en rupture (§4).

-- Produits épinglés pour la vente au comptoir, par magasin : une tuile cliquable par produit, dans l'ordre choisi.
-- Supprimer un produit retire son épingle ; supprimer un magasin n'est pas prévu (aucune cascade).
CREATE TABLE produit_favori (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  magasin_id  integer   NOT NULL REFERENCES magasin (id),
  produit_id  integer   NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
  ordre       integer   NOT NULL DEFAULT 0,
  created_at  timestamp NOT NULL DEFAULT now(),
  CONSTRAINT produit_favori_magasin_produit_uk UNIQUE (magasin_id, produit_id)
);

CREATE INDEX produit_favori_magasin_ordre_idx ON produit_favori (magasin_id, ordre);

-- Les mêmes résultats que search_produits_json (mêmes colonnes, même JSON, donc le même `ProduitSearch` côté serveur et
-- côté écran), pour une liste d'identifiants au lieu d'un texte : la grille des favoris et les substituts proposés en
-- rupture n'ont pas à rechercher un produit qu'ils connaissent déjà. L'ordre des identifiants reçus est conservé ; un
-- identifiant inconnu est ignoré. Le stock est celui du magasin, comme pour la recherche.
create or replace function search_produits_by_ids_json(p_ids integer[], magasin integer DEFAULT 1) returns jsonb
  language plpgsql
as
$$
BEGIN
  RETURN (SELECT jsonb_agg(result)
          FROM (SELECT p.id,
                       p.fournisseur_produit_principal_id AS codecipprincipalid,
                       p.libelle,
                       p.code_ean_labo                    AS codeeanlabo,
                       p.parent_id                        AS parentid,
                       p.item_qty                         AS itemqty,
                       p.deconditionnable,
                       t.taux                             AS vatrate,
                       p.regular_unit_price               AS regularunitprice,
                       p.cost_amount                      AS costamount,
                       jsonb_agg(
                         jsonb_build_object(
                           'id', pf.id,
                           'codeCip', pf.code_cip,
                           'codeEan', pf.code_ean,
                           'prixUni', pf.prix_uni,
                           'prixAchat', pf.prix_achat
                         )
                       )                                  AS fournisseurs,
                       -- rayons
                       (SELECT jsonb_agg(
                                 jsonb_build_object(
                                   'code', r.code,
                                   'libelle', r.libelle
                                 )
                                 ORDER BY r.libelle
                               )
                        FROM rayon_produit rp
                               JOIN rayon r ON rp.rayon_id = r.id
                        WHERE rp.produit_id = p.id)       AS rayons,
                       -- stocks
                       (SELECT jsonb_agg(
                                 jsonb_build_object(
                                   'quantite', sp.qty_stock,
                                   'qteUg', sp.qty_ug,
                                   'storage', sp.storage_id,
                                   'storageType', s.storage_type,
                                   'stockReassort', sp.stock_reassort,
                                   'seuilMini', sp.seuil_mini
                                 )
                                 ORDER BY sp.id
                               )
                        FROM stock_produit sp
                               join storage s on sp.storage_id = s.id
                        WHERE sp.produit_id = p.id
                          AND s.magasin_id = magasin)     AS stocks,
                       -- forme galénique, molécules (DCI) et dosages
                       (SELECT fm.libelle FROM form_produit fm WHERE fm.id = p.forme_id)                       AS forme,
                       (SELECT string_agg(d.libelle, ' + ' ORDER BY pd.rang)
                        FROM produit_dci pd
                               JOIN dci d ON d.id = pd.dci_id
                        WHERE pd.produit_id = p.id)                                                          AS dci,
                       (SELECT string_agg(trim_scale(pd.dosage_valeur)::text || ' ' || pd.dosage_unite, ' + ' ORDER BY pd.rang)
                        FROM produit_dci pd
                        WHERE pd.produit_id = p.id
                          AND pd.dosage_valeur IS NOT NULL)                                                  AS dosage,
                       -- princeps ou générique, d'après le rapprochement avec le référentiel (accepté d'office ou validé)
                       (SELECT s.type_generique
                        FROM produit_ref_specialite r
                               JOIN ref_specialite s ON s.cis = r.cis
                        WHERE r.produit_id = p.id
                          AND r.decision IN ('AUTO', 'VALIDE')
                          AND s.type_generique IS NOT NULL)                                                  AS typegenerique,
                       p.statut_legal                                                                        AS statutlegal,
                       -- lot en stock le plus proche de sa péremption, s'il est périmé ou proche de l'être
                       (SELECT l.num_lot
                        FROM lot l
                        WHERE l.produit_id = p.id
                          AND l.current_quantity > 0
                          AND l.statut = 'AVAILABLE'
                          AND l.expiry_date <= CURRENT_DATE + COALESCE(
                            (SELECT NULLIF(c.value, '')::int FROM app_configuration c
                             WHERE c.name = 'APP_EXPIRY_ALERT_DAYS_BEFORE'), 90)
                        ORDER BY l.expiry_date, l.id
                        LIMIT 1)                                          AS peremptionlot,
                       (SELECT to_char(l.expiry_date, 'YYYY-MM-DD')
                        FROM lot l
                        WHERE l.produit_id = p.id
                          AND l.current_quantity > 0
                          AND l.statut = 'AVAILABLE'
                          AND l.expiry_date <= CURRENT_DATE + COALESCE(
                            (SELECT NULLIF(c.value, '')::int FROM app_configuration c
                             WHERE c.name = 'APP_EXPIRY_ALERT_DAYS_BEFORE'), 90)
                        ORDER BY l.expiry_date, l.id
                        LIMIT 1)               AS peremptiondate
                FROM produit p
                       LEFT JOIN fournisseur_produit pf ON pf.produit_id = p.id
                       LEFT JOIN tva t ON p.tva_id = t.id
                WHERE p.id = ANY (p_ids)
                GROUP BY p.id, p.libelle, p.code_ean_labo, p.fournisseur_produit_principal_id,
                         t.taux, p.regular_unit_price, p.cost_amount
                ORDER BY array_position(p_ids, p.id)) result);
END;
$$;
