-- Référentiel d'interactions et de contre-indications .
--
-- Clé : ref_dci.id (référentiel BDPM), non la DCI du catalogue : un produit y accède par produit_dci
-- ou par sa spécialité retenue. Les tables sont VERSIONNÉES et SOURCÉES : une version non relue n'est
-- jamais publiée, et seules les lignes d'une version publiée alimentent le contrôle.

CREATE TABLE referentiel_interaction_version (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source      varchar(120) NOT NULL,
  version     varchar(40)  NOT NULL,
  importe_le  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  importe_par varchar(100),
  -- Publication = relecture humaine faite.
  publie      boolean      NOT NULL DEFAULT FALSE,
  publie_le   timestamp,
  publie_par  varchar(100),
  commentaire varchar(500),
  CONSTRAINT referentiel_interaction_version_uk UNIQUE (source, version)
);

CREATE TABLE classe_interaction (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id integer      NOT NULL REFERENCES referentiel_interaction_version (id) ON DELETE CASCADE,
  libelle varchar(255) NOT NULL,
  CONSTRAINT classe_interaction_version_libelle_uk UNIQUE (version_id, libelle)
);

CREATE TABLE dci_classe (
  classe_id  integer NOT NULL REFERENCES classe_interaction (id) ON DELETE CASCADE,
  ref_dci_id integer NOT NULL REFERENCES ref_dci (id),
  PRIMARY KEY (classe_id, ref_dci_id)
);

CREATE INDEX dci_classe_ref_dci_idx ON dci_classe (ref_dci_id);

-- Chaque côté du couple vise une molécule OU une classe (exactement une des deux colonnes).
-- CI : contre-indication ; AD : association déconseillée ; PE : précaution d'emploi ;
-- APEC : à prendre en compte (vocabulaire du thésaurus de l'ANSM).
CREATE TABLE interaction (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id    integer      NOT NULL REFERENCES referentiel_interaction_version (id) ON DELETE CASCADE,
  a_ref_dci_id  integer REFERENCES ref_dci (id),
  a_classe_id   integer REFERENCES classe_interaction (id) ON DELETE CASCADE,
  b_ref_dci_id  integer REFERENCES ref_dci (id),
  b_classe_id   integer REFERENCES classe_interaction (id) ON DELETE CASCADE,
  niveau        varchar(4)   NOT NULL CONSTRAINT interaction_niveau_check CHECK (niveau IN ('CI', 'AD', 'PE', 'APEC')),
  mecanisme     varchar(1000),
  conduite      varchar(1000),
  CONSTRAINT interaction_cote_a_check CHECK ((a_ref_dci_id IS NULL) <> (a_classe_id IS NULL)),
  CONSTRAINT interaction_cote_b_check CHECK ((b_ref_dci_id IS NULL) <> (b_classe_id IS NULL))
);

CREATE INDEX interaction_version_idx ON interaction (version_id);
CREATE INDEX interaction_a_dci_idx ON interaction (a_ref_dci_id) WHERE a_ref_dci_id IS NOT NULL;
CREATE INDEX interaction_b_dci_idx ON interaction (b_ref_dci_id) WHERE b_ref_dci_id IS NOT NULL;
CREATE INDEX interaction_a_classe_idx ON interaction (a_classe_id) WHERE a_classe_id IS NOT NULL;
CREATE INDEX interaction_b_classe_idx ON interaction (b_classe_id) WHERE b_classe_id IS NOT NULL;

-- Molécule x critère du patient. critere : AGE_MIN (âge minimal d'emploi : contre-indiqué en dessous de
-- valeur_num ans), AGE_MAX (contre-indiqué au-delà), SEXE (valeur_texte = M | F : contre-indiqué à
-- ce sexe), GROSSESSE, ALLAITEMENT.
CREATE TABLE contre_indication (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id   integer      NOT NULL REFERENCES referentiel_interaction_version (id) ON DELETE CASCADE,
  ref_dci_id   integer      NOT NULL REFERENCES ref_dci (id),
  critere      varchar(12)  NOT NULL
    CONSTRAINT contre_indication_critere_check CHECK (critere IN ('AGE_MIN', 'AGE_MAX', 'SEXE', 'GROSSESSE', 'ALLAITEMENT')),
  valeur_num   numeric(6, 2),
  valeur_texte varchar(20),
  niveau       varchar(4)   NOT NULL CONSTRAINT contre_indication_niveau_check CHECK (niveau IN ('CI', 'AD', 'PE', 'APEC')),
  motif        varchar(1000),
  conduite     varchar(1000)
);

CREATE INDEX contre_indication_dci_idx ON contre_indication (ref_dci_id);
CREATE INDEX contre_indication_version_idx ON contre_indication (version_id);
