
CREATE TABLE IF NOT EXISTS pilotage_vente_ligne_jour
(
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jour              DATE        NOT NULL,
  produit_id        INTEGER     NOT NULL,
  magasin_id        INTEGER     NOT NULL,
  vendeur_id        INTEGER,
  nature_vente      VARCHAR(20),
  type_prescription VARCHAR(20),
  categorie_ca      VARCHAR(20) NOT NULL,
  quantite_demandee BIGINT      NOT NULL,
  quantite_servie   BIGINT      NOT NULL,
  quantite_avoir    BIGINT      NOT NULL,
  montant_ttc       BIGINT      NOT NULL,
  montant_ht        BIGINT      NOT NULL,
  remise            BIGINT      NOT NULL,
  cout_ttc          BIGINT      NOT NULL,
  cout_ht           BIGINT      NOT NULL,
  nb_lignes         BIGINT      NOT NULL
);
CREATE INDEX IF NOT EXISTS pilotage_vente_ligne_jour_jour_idx ON pilotage_vente_ligne_jour (jour);
CREATE INDEX IF NOT EXISTS pilotage_vente_ligne_jour_produit_idx ON pilotage_vente_ligne_jour (produit_id, jour);

-- En-têtes de vente clôturées (annulées comprises, marquées), par jour × heure × magasin × vendeur × caissier × nature ×
-- prescription × catégorie : fréquentation, taux d'annulation, part tiers payant.
CREATE TABLE IF NOT EXISTS pilotage_vente_jour
(
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jour                    DATE        NOT NULL,
  heure                   SMALLINT    NOT NULL,
  magasin_id              INTEGER     NOT NULL,
  vendeur_id              INTEGER,
  caissier_id             INTEGER,
  nature_vente            VARCHAR(20),
  type_prescription       VARCHAR(20),
  categorie_ca            VARCHAR(20) NOT NULL,
  annulee                 BOOLEAN     NOT NULL,
  nb_ventes               BIGINT      NOT NULL,
  montant_ttc             BIGINT      NOT NULL,
  montant_ht              BIGINT      NOT NULL,
  montant_net             BIGINT      NOT NULL,
  remise                  BIGINT      NOT NULL,
  part_tiers_payant       BIGINT      NOT NULL,
  nb_ventes_client_connu  BIGINT      NOT NULL
);
CREATE INDEX IF NOT EXISTS pilotage_vente_jour_jour_idx ON pilotage_vente_jour (jour);

-- Commandes reçues, datées à la réception (décision du 2026-10-09), par jour × produit × fournisseur. Le prix d'achat est TTC :
-- le HT retire la taxe portée par la ligne (`order_line.tax_amount`).
CREATE TABLE IF NOT EXISTS pilotage_achat_jour
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jour               DATE    NOT NULL,
  produit_id         INTEGER NOT NULL,
  fournisseur_id     INTEGER NOT NULL,
  nb_bons            BIGINT  NOT NULL,
  quantite_commandee BIGINT  NOT NULL,
  quantite_recue     BIGINT  NOT NULL,
  quantite_gratuite  BIGINT  NOT NULL,
  montant_ht         BIGINT  NOT NULL,
  montant_ttc        BIGINT  NOT NULL
);
CREATE INDEX IF NOT EXISTS pilotage_achat_jour_jour_idx ON pilotage_achat_jour (jour);

-- Encaissements, par jour × type de transaction × mode × caissier × catégorie.
CREATE TABLE IF NOT EXISTS pilotage_encaissement_jour
(
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jour             DATE         NOT NULL,
  type_transaction VARCHAR(50)  NOT NULL,
  mode_paiement    VARCHAR(50),
  caissier_id      INTEGER,
  categorie_ca     VARCHAR(20),
  montant          BIGINT       NOT NULL,
  nb_transactions  BIGINT       NOT NULL
);
CREATE INDEX IF NOT EXISTS pilotage_encaissement_jour_jour_idx ON pilotage_encaissement_jour (jour);

-- Stock en fin de mois (stock + UG), par produit × magasin, valorisé à la date par fn_stock_valuation_bulk (V2.1.33) :
-- les mois passés se reconstituent depuis le journal des mouvements.
CREATE TABLE IF NOT EXISTS pilotage_stock_mensuel
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mois         DATE    NOT NULL,
  produit_id   INTEGER NOT NULL,
  magasin_id   INTEGER NOT NULL,
  quantite     BIGINT  NOT NULL,
  valeur_achat BIGINT  NOT NULL,
  valeur_vente BIGINT  NOT NULL,
  CONSTRAINT pilotage_stock_mensuel_unique UNIQUE (mois, produit_id, magasin_id)
);

-- ─── Paramètres ───────────────────────────────────────────────────────────────────────────────────────────────────

INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES ('APP_PILOTAGE_SEUIL_STOCK_DORMANT', '90',
        'Nombre de jours sans vente au-delà duquel un produit en stock est dit dormant (défaut : 90).',
        NOW(), NOW(), 'NUMBER')
ON CONFLICT (name) DO NOTHING;

-- ─── Recalcul ───────────────────────────────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION pilotage_recalculer_ventes(p_du DATE, p_au DATE) RETURNS VOID
  LANGUAGE plpgsql AS
$$
BEGIN
  DELETE FROM pilotage_vente_ligne_jour WHERE jour BETWEEN p_du AND p_au;
  INSERT INTO pilotage_vente_ligne_jour (jour, produit_id, magasin_id, vendeur_id, nature_vente, type_prescription, categorie_ca,
                                         quantite_demandee, quantite_servie, quantite_avoir, montant_ttc, montant_ht, remise, cout_ttc,
                                         cout_ht, nb_lignes)
  SELECT s.sale_date,
         sl.produit_id,
         s.magasin_id,
         s.seller_id,
         s.nature_vente,
         s.type_prescription,
         s.ca,
         SUM(sl.quantity_requested),
         SUM(sl.quantity_sold),
         SUM(COALESCE(sl.quantity_avoir, 0)),
         SUM(sl.sales_amount),
         SUM(ROUND(sl.sales_amount * 100.0 / (100 + COALESCE(sl.tax_value, 0)))),
         SUM(COALESCE(sl.discount_amount, 0)),
         SUM(COALESCE(sl.cost_amount, 0)::BIGINT * sl.quantity_requested),
         SUM(ROUND(COALESCE(sl.cost_amount, 0)::BIGINT * sl.quantity_requested * 100.0 / (100 + COALESCE(sl.tax_value, 0)))),
         COUNT(*)
  FROM sales s
         JOIN sales_line sl ON sl.sales_id = s.id AND sl.sales_sale_date = s.sale_date
  WHERE s.sale_date BETWEEN p_du AND p_au
    AND s.statut = 'CLOSED'
    AND NOT s.canceled
  GROUP BY s.sale_date, sl.produit_id, s.magasin_id, s.seller_id, s.nature_vente, s.type_prescription, s.ca;

  DELETE FROM pilotage_vente_jour WHERE jour BETWEEN p_du AND p_au;
  INSERT INTO pilotage_vente_jour (jour, heure, magasin_id, vendeur_id, caissier_id, nature_vente, type_prescription, categorie_ca,
                                   annulee, nb_ventes, montant_ttc, montant_ht, montant_net, remise, part_tiers_payant,
                                   nb_ventes_client_connu)
  SELECT s.sale_date,
         EXTRACT(HOUR FROM s.created_at)::SMALLINT,
         s.magasin_id,
         s.seller_id,
         s.caissier_id,
         s.nature_vente,
         s.type_prescription,
         s.ca,
         s.canceled,
         COUNT(*),
         SUM(s.sales_amount),
         SUM(COALESCE(s.ht_amount, 0)),
         SUM(COALESCE(s.net_amount, 0)),
         SUM(COALESCE(s.discount_amount, 0)),
         SUM(COALESCE(s.part_tiers_payant, 0)),
         COUNT(s.customer_id)
  FROM sales s
  WHERE s.sale_date BETWEEN p_du AND p_au
    AND s.statut = 'CLOSED'
  GROUP BY s.sale_date, EXTRACT(HOUR FROM s.created_at), s.magasin_id, s.seller_id, s.caissier_id, s.nature_vente,
           s.type_prescription, s.ca, s.canceled;
END;
$$;

CREATE OR REPLACE FUNCTION pilotage_recalculer_achats(p_du DATE, p_au DATE) RETURNS VOID
  LANGUAGE plpgsql AS
$$
BEGIN
  DELETE FROM pilotage_achat_jour WHERE jour BETWEEN p_du AND p_au;
  INSERT INTO pilotage_achat_jour (jour, produit_id, fournisseur_id, nb_bons, quantite_commandee, quantite_recue, quantite_gratuite,
                                   montant_ht, montant_ttc)
  SELECT c.receipt_date,
         fp.produit_id,
         c.fournisseur_id,
         COUNT(DISTINCT c.id),
         SUM(COALESCE(ol.quantity_requested, 0)),
         SUM(COALESCE(ol.quantity_received, 0)),
         SUM(COALESCE(ol.free_qty, 0)),
         SUM(COALESCE(ol.order_cost_amount, 0)::BIGINT * COALESCE(ol.quantity_received, 0) - COALESCE(ol.tax_amount, 0)),
         SUM(COALESCE(ol.order_cost_amount, 0)::BIGINT * COALESCE(ol.quantity_received, 0))
  FROM commande c
         JOIN order_line ol ON ol.commande_id = c.id AND ol.commande_order_date = c.order_date
         JOIN fournisseur_produit fp ON fp.id = ol.fournisseur_produit_id
  WHERE c.receipt_date BETWEEN p_du AND p_au
    AND c.order_status IN ('RECEIVED', 'CLOSED')
  GROUP BY c.receipt_date, fp.produit_id, c.fournisseur_id;
END;
$$;

CREATE OR REPLACE FUNCTION pilotage_recalculer_encaissements(p_du DATE, p_au DATE) RETURNS VOID
  LANGUAGE plpgsql AS
$$
BEGIN
  DELETE FROM pilotage_encaissement_jour WHERE jour BETWEEN p_du AND p_au;
  INSERT INTO pilotage_encaissement_jour (jour, type_transaction, mode_paiement, caissier_id, categorie_ca, montant, nb_transactions)
  SELECT pt.transaction_date,
         pt.dtype,
         pt.payment_mode_code,
         cr.user_id,
         pt.categorie_ca,
         SUM(COALESCE(pt.paid_amount, 0)),
         COUNT(*)
  FROM payment_transaction pt
         LEFT JOIN cash_register cr ON cr.id = pt.cash_register_id
  WHERE pt.transaction_date BETWEEN p_du AND p_au
  GROUP BY pt.transaction_date, pt.dtype, pt.payment_mode_code, cr.user_id, pt.categorie_ca;
END;
$$;

CREATE OR REPLACE FUNCTION pilotage_recalculer(p_du DATE, p_au DATE) RETURNS VOID
  LANGUAGE plpgsql AS
$$
BEGIN
  -- Un seul recalcul à la fois (tâche planifiée, rattrapage, demande de l'administrateur) : sinon deux DELETE + INSERT
  -- concurrents du même jour dupliqueraient ses lignes.
  PERFORM pg_advisory_xact_lock(hashtext('pilotage_recalculer'));
  PERFORM pilotage_recalculer_ventes(p_du, p_au);
  PERFORM pilotage_recalculer_achats(p_du, p_au);
  PERFORM pilotage_recalculer_encaissements(p_du, p_au);
END;
$$;

-- Stock du mois de p_jour, rangé à son dernier jour : valorisé à la fin du mois, ou maintenant si le mois est en cours.
CREATE OR REPLACE FUNCTION pilotage_photographier_stock(p_jour DATE) RETURNS VOID
  LANGUAGE plpgsql AS
$$
DECLARE
  v_mois    DATE        := (DATE_TRUNC('month', p_jour) + INTERVAL '1 month - 1 day')::DATE;
  v_instant TIMESTAMPTZ := LEAST(NOW(), (v_mois + 1)::TIMESTAMPTZ);
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('pilotage_photographier_stock'));
  DELETE FROM pilotage_stock_mensuel WHERE mois = v_mois;
  INSERT INTO pilotage_stock_mensuel (mois, produit_id, magasin_id, quantite, valeur_achat, valeur_vente)
  SELECT v_mois,
         v.produit_id,
         st.magasin_id,
         SUM(v.qty_stock + v.qty_ug),
         SUM(v.valeur_achat),
         SUM(v.valeur_vente)
  FROM fn_stock_valuation_bulk(NULL, NULL, v_instant) v
         JOIN storage st ON st.id = v.storage_id
  GROUP BY v.produit_id, st.magasin_id;
END;
$$;

-- ─── Chargement initial ─────────────────────────────────────────────────────────────────────────────────────────────

SELECT pilotage_recalculer(
         LEAST(COALESCE((SELECT MIN(sale_date) FROM sales), CURRENT_DATE),
               COALESCE((SELECT MIN(receipt_date) FROM commande), CURRENT_DATE),
               COALESCE((SELECT MIN(transaction_date) FROM payment_transaction), CURRENT_DATE)),
         CURRENT_DATE);

-- Un mois par ligne, depuis le premier mouvement de stock : le stock N-1 est disponible tout de suite.
SELECT pilotage_photographier_stock(mois::DATE)
FROM generate_series(DATE_TRUNC('month', COALESCE((SELECT MIN(created_at) FROM inventory_transaction), NOW())),
                     DATE_TRUNC('month', NOW()),
                     INTERVAL '1 month') AS mois;
