-- Plafond non absolu : la facture définitive remet la consommation à zéro. On garde ce qu'elle a
-- effacé, pour le rendre si la facture est annulée (règle du 2026-09-29).
-- Pas de clé étrangère vers la facture : l'annulation la supprime, ces lignes sont lues juste avant.
CREATE TABLE reinitialisation_consommation (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facture_id             bigint    NOT NULL,
  facture_date           date      NOT NULL,
  client_tiers_payant_id integer REFERENCES client_tiers_payant (id) ON DELETE CASCADE,
  tiers_payant_id        integer REFERENCES tiers_payant (id) ON DELETE CASCADE,
  montant                bigint    NOT NULL,
  created_at             timestamp NOT NULL DEFAULT now(),
  CHECK ((client_tiers_payant_id IS NULL) <> (tiers_payant_id IS NULL))
);

CREATE INDEX reinitialisation_consommation_facture_idx ON reinitialisation_consommation (facture_id, facture_date);
