-- Fiche client, lot 3 : couverture et crédit (docs/PLAN-FICHE-CLIENT.md).

-- Validité de la carte d'assuré, par organisme : une carte expirée est signalée à la vente.
ALTER TABLE client_tiers_payant ADD COLUMN date_fin_validite date;

-- Limite de crédit : une seule, pour toute l'officine (décision du 2026-09-29), sur l'encours des
-- ventes différées. 0 = aucune limite, pour ne rien changer tant qu'elle n'est pas réglée.
INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES ('APP_LIMITE_CREDIT_CLIENT', '0',
        'Encours maximal de ventes différées par client, en montant (0 = aucune limite). Au-delà, la vente à crédit est refusée sauf autorisation.',
        NOW(), NOW(), 'NUMBER')
ON CONFLICT (name) DO NOTHING;

-- Vente à crédit au-delà de la limite : autorisée pour une vente donnée, et tracée.
CREATE TABLE limite_credit_derogation (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      integer      NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  sale_id          bigint       NOT NULL,
  sale_date        date         NOT NULL,
  montant          integer      NOT NULL,
  encours          integer      NOT NULL,
  limite           integer      NOT NULL,
  motif            varchar(255) NOT NULL,
  user_id          integer      NOT NULL REFERENCES app_user (id),
  autorise_par_id  integer      NOT NULL REFERENCES app_user (id),
  created_at       timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX limite_credit_derogation_sale_idx ON limite_credit_derogation (sale_id, sale_date);

-- Relances des différés par SMS : ce qui a été envoyé, à qui, par qui.
CREATE TABLE relance_differe (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer      NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  telephone   varchar(30)  NOT NULL,
  montant     integer      NOT NULL,
  message     text         NOT NULL,
  user_id     integer      NOT NULL REFERENCES app_user (id),
  created_at  timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX relance_differe_customer_idx ON relance_differe (customer_id);

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-depasser-limite-credit',
       'Vendre à crédit au-delà de la limite',
       NULL,
       NULL,
       id,
       0,
       3,
       'ACTION',
       TRUE
FROM nav_item
WHERE code = 'ventes'
ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete,
                           can_export, can_execute)
SELECT n.id, r.role_name, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE
FROM nav_item n
       CROSS JOIN (VALUES ('ROLE_ADMIN'), ('ROLE_PHARMACIEN')) AS r(role_name)
WHERE n.code = 'pr-depasser-limite-credit'
  AND EXISTS (SELECT 1 FROM authority a WHERE a.name = r.role_name)
ON CONFLICT (nav_item_id, role_name) DO UPDATE SET can_execute = TRUE;
