-- Menu « Exports »  : catalogue, fichiers générés en tâche de fond et leur historique,
-- modèles rejouables et programmables.

CREATE TABLE IF NOT EXISTS export_modele
(
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle             VARCHAR(100) NOT NULL,
  export              VARCHAR(40)  NOT NULL,
  format              VARCHAR(10)  NOT NULL,
  periode             VARCHAR(30),
  proprietaire_id     INTEGER      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  partage             BOOLEAN      NOT NULL DEFAULT FALSE,
  frequence           VARCHAR(15),
  heure               TIME,
  jour                INTEGER,
  prochaine_execution TIMESTAMP
);
CREATE INDEX IF NOT EXISTS export_modele_proprietaire_idx ON export_modele (proprietaire_id);
CREATE INDEX IF NOT EXISTS export_modele_programme_idx ON export_modele (prochaine_execution) WHERE frequence IS NOT NULL;

-- L'historique survit au fichier : à expiration, seul le fichier est supprimé. Un utilisateur supprimé garde sa trace.
CREATE TABLE IF NOT EXISTS export_fichier
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  export         VARCHAR(40) NOT NULL,
  format         VARCHAR(10) NOT NULL,
  du             DATE,
  au             DATE,
  statut         VARCHAR(20) NOT NULL,
  nombre_lignes  BIGINT,
  taille         BIGINT,
  fichier        VARCHAR(150),
  erreur         VARCHAR(500),
  demande_par_id INTEGER     NOT NULL REFERENCES app_user (id),
  demande_le     TIMESTAMP   NOT NULL,
  termine_le     TIMESTAMP,
  expire_le      TIMESTAMP,
  modele_id      BIGINT REFERENCES export_modele (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS export_fichier_demande_par_idx ON export_fichier (demande_par_id, demande_le DESC);
CREATE INDEX IF NOT EXISTS export_fichier_expiration_idx ON export_fichier (expire_le) WHERE statut = 'TERMINE';

INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES ('APP_EXPORT_RETENTION_JOURS', '7', 'Nombre de jours pendant lesquels un fichier exporté reste téléchargeable (défaut : 7).',
        NOW(), NOW(), 'NUMBER')
ON CONFLICT (name) DO NOTHING;

-- Entrée de premier niveau, juste après le pilotage.
UPDATE nav_item
SET ordre = ordre + 1
WHERE parent_id IS NULL
  AND ordre >= 2
  AND NOT EXISTS (SELECT 1 FROM nav_item p WHERE p.code = 'exports');

INSERT INTO nav_item (code, libelle, titre_long, icon, router_link, parent_id, ordre, niveau, target_type, actif)
VALUES ('exports', 'Exports', 'Exports de données', 'pi pi-download', '/exports', NULL, 2, 1, 'ROUTE', TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, titre_long, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT s.code, s.libelle, s.titre_long, s.icon, NULL, p.id, s.ordre, 3, 'SECTION', TRUE
FROM nav_item p
       CROSS JOIN (VALUES ('exports.catalogue', 'Catalogue', 'Que puis-je exporter ?', 'pi pi-th-large', 10),
                          ('exports.historique', 'Historique', 'Mes fichiers et qui a exporté quoi', 'pi pi-history', 20),
                          ('exports.modeles', 'Modèles', 'Exports enregistrés et programmés', 'pi pi-bookmark', 30))
  AS s(code, libelle, titre_long, icon, ordre)
WHERE p.code = 'exports'
ON CONFLICT (code) DO NOTHING;

-- Un droit par rubrique ; les données nominatives (clients) ont le leur.
INSERT INTO nav_item (code, libelle, titre_long, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT s.code, s.libelle, NULL, NULL, NULL, p.id, s.ordre, 4, 'ACTION', TRUE
FROM nav_item p
       CROSS JOIN (VALUES ('exports.donnees', 'Exporter les données (ventes, achats, stock…)', 10),
                          ('exports.nominatif', 'Exporter les données nominatives (clients)', 20),
                          ('exports.bi', 'Exporter le fichier pour un outil de BI', 30))
  AS s(code, libelle, ordre)
WHERE p.code = 'exports.catalogue'
ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
FROM nav_item
WHERE code = 'exports'
   OR code LIKE 'exports.%'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Le titulaire exporte tout, sauf les données nominatives : l'administrateur les ouvre s'il le décide.
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
FROM nav_item
WHERE (code = 'exports' OR code LIKE 'exports.%')
  AND code <> 'exports.nominatif'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;
