-- Rapprochement produit du catalogue ↔ spécialité du référentiel BDPM (voir V2.1.19).
--
-- Tout le calcul vit dans PostgreSQL : une seule requête ensembliste rapproche des milliers de
-- produits (jointures par hachage, index trigramme, fonctions de fenêtre), dans une seule
-- transaction. Java ne fait qu'appeler les fonctions ci-dessous — du batch de nuit comme de
-- l'ajout d'une DCI.
--
-- Le résultat est d'abord une PROPOSITION (EN_ATTENTE). ref_appliquer_rapprochements() accepte
-- d'office les propositions SUR et PAR_DCI (decision = AUTO, tracée, datée) et pose les DCI du
-- référentiel sur les produits qui n'en ont aucune : l'humain ne relit que le reste (A_VERIFIER, et
-- les PAR_DCI dont une molécule n'est pas encore au catalogue). Un produit déjà doté de DCI n'est
-- jamais modifié. Une décision AUTO, VALIDE ou REJETE n'est jamais recalculée.

CREATE TABLE produit_ref_specialite (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produit_id  integer      NOT NULL REFERENCES produit (id) ON DELETE CASCADE
    CONSTRAINT produit_ref_specialite_produit_uk UNIQUE,
  -- NULL quand statut = NON_TROUVE : la tentative est mémorisée pour ne pas être refaite chaque nuit.
  cis         varchar(8) REFERENCES ref_specialite (cis) ON DELETE SET NULL,
  -- SUR : même nom, même dosage, un seul candidat de ce score, sans conflit de DCI.
  -- A_VERIFIER : nom (exact ou approché) retrouvé, dosage ou forme à relire.
  -- PAR_DCI : rattaché par la molécule (déclarée sur le produit, ou lue dans son libellé) et le dosage.
  -- NON_TROUVE : aucun candidat suffisant.
  statut      varchar(12)  NOT NULL
    CONSTRAINT produit_ref_specialite_statut_check CHECK (statut IN ('SUR', 'A_VERIFIER', 'PAR_DCI', 'NON_TROUVE')),
  score       smallint     NOT NULL DEFAULT 0 CONSTRAINT produit_ref_specialite_score_check CHECK (score BETWEEN 0 AND 100),
  motif       varchar(255),
  decision    varchar(10)  NOT NULL DEFAULT 'EN_ATTENTE'
    -- AUTO : acceptée par règle (SUR, PAR_DCI) ; VALIDE / REJETE : décision d'une personne.
    CONSTRAINT produit_ref_specialite_decision_check CHECK (decision IN ('EN_ATTENTE', 'AUTO', 'VALIDE', 'REJETE')),
  calcule_le  timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  decide_le   timestamp,
  -- TRUE quand l'acceptation automatique a posé les DCI du produit (il n'en avait aucune) : c'est ce
  -- qui justifie le badge « DCI posée automatiquement » sur la fiche produit.
  dci_posee   boolean      NOT NULL DEFAULT FALSE
);

CREATE INDEX produit_ref_specialite_cis_idx ON produit_ref_specialite (cis);
CREATE INDEX produit_ref_specialite_a_traiter_idx ON produit_ref_specialite (statut, score DESC) WHERE decision = 'EN_ATTENTE';

-- ---------------------------------------------------------------------------------------------
-- Lien ref_dci -> dci du catalogue, par libellé normalisé.
-- Sans argument : toutes les DCI. Une DCI du catalogue déjà liée, ou un libellé ambigu, n'est
-- jamais relié (le lien est 1-1 : rien n'est deviné).
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION ref_lier_dci(p_dci_ids integer[] DEFAULT NULL) RETURNS integer
  LANGUAGE plpgsql
AS
$$
DECLARE
  v_nb integer;
BEGIN
  WITH candidats AS (
    SELECT rd.id AS ref_dci_id, min(d.id) AS dci_id
    FROM ref_dci rd
             JOIN dci d ON ref_normaliser(d.libelle) = rd.libelle_normalise
    WHERE rd.dci_id IS NULL
      AND (p_dci_ids IS NULL OR d.id = ANY (p_dci_ids))
      AND NOT EXISTS (SELECT 1 FROM ref_dci x WHERE x.dci_id = d.id)
    GROUP BY rd.id
    HAVING count(*) = 1
  ), uniques AS (
    SELECT min(ref_dci_id) AS ref_dci_id, dci_id
    FROM candidats
    GROUP BY dci_id
    HAVING count(*) = 1
  )
  UPDATE ref_dci rd
  SET dci_id = u.dci_id
  FROM uniques u
  WHERE rd.id = u.ref_dci_id;
  GET DIAGNOSTICS v_nb = ROW_COUNT;
  RETURN v_nb;
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Rapprochement ensembliste.
--   p_produit_ids : restreint aux produits donnés ; NULL = tout le catalogue actif ; tableau vide = rien.
--   p_forcer      : FALSE = seulement les produits sans proposition ; TRUE = recalcule aussi les
--                   propositions EN_ATTENTE (après rechargement du référentiel, nouvelle DCI…).
-- Retourne le nombre de propositions écrites.
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION ref_rapprocher_produits(p_produit_ids integer[] DEFAULT NULL, p_forcer boolean DEFAULT FALSE)
  RETURNS integer
  LANGUAGE plpgsql
  -- Statistiques absentes sur une table fraîchement vidée : le planificateur y voit « 1 ligne » et
  -- choisit des boucles imbriquées qui rejouent tout le pipeline par produit (90 s pour 600 produits).
  -- Jointures par hachage ou par fusion uniquement ; les LATERAL restent possibles.
  SET enable_nestloop = off
AS
$$
DECLARE
  v_nb integer;
BEGIN
  -- Référentiel pas encore chargé : ne rien écrire. Sinon chaque produit serait mémorisé NON_TROUVE
  -- et ne serait plus repris par le passage de nuit.
  IF NOT EXISTS (SELECT 1 FROM ref_specialite) THEN
    RETURN 0;
  END IF;

  -- Seuil de l'opérateur % : en deçà de 0,7, « VENTOLINE » ramène la moitié du référentiel.
  PERFORM set_config('pg_trgm.similarity_threshold', '0.7', TRUE);

  WITH
    cible AS MATERIALIZED (
      SELECT p.id AS produit_id, p.libelle, ref_normaliser(p.libelle) AS norm, lower(p.libelle) AS brut
      FROM produit p
               LEFT JOIN produit_ref_specialite r ON r.produit_id = p.id
      WHERE p.status = 'ENABLE'
        AND p.type_produit = 'PACKAGE'
        AND (p_produit_ids IS NULL OR p.id = ANY (p_produit_ids))
        AND (r.id IS NULL OR (p_forcer AND r.decision = 'EN_ATTENTE'))
    ),
    -- Le « nom » : le libellé jusqu'au premier mot qui commence par un chiffre (« DOLIPRANE 500MG B/16 » -> DOLIPRANE).
    cible_nom AS (
      SELECT c.*, btrim(regexp_replace(c.norm, '\s*\m\d.*$', '')) AS nom
      FROM cible c
    ),
    -- Dosages lus dans le libellé, ramenés à l'unité commune de ref_specialite_composition.
    dosage_produit AS (
      SELECT DISTINCT c.produit_id,
                      CASE m.g[2] WHEN 'ui' THEN 'UI' WHEN 'ml' THEN 'mL' WHEN '%' THEN '%' ELSE 'mg' END AS unite,
                      round(replace(m.g[1], ',', '.')::numeric
                              * CASE m.g[2] WHEN 'g' THEN 1000 WHEN 'µg' THEN 0.001 WHEN 'mcg' THEN 0.001 WHEN 'ug' THEN 0.001 ELSE 1 END,
                            4) AS valeur
      FROM cible c
               CROSS JOIN LATERAL regexp_matches(c.brut, '(\d+(?:[.,]\d+)?)\s*(mg|g|µg|mcg|ug|ui|ml|%)(?![a-zµ])', 'g') AS m(g)
    ),
    produit_dosage AS (
      SELECT produit_id, count(*) AS nb FROM dosage_produit GROUP BY produit_id
    ),
    -- Formes reconnues dans le libellé (abréviations d'officine) et leur écriture dans la BDPM.
    forme_ref(cle, motif_produit, motif_specialite) AS (
      VALUES ('COMPRIME', '\m(CPR|COMP|COMPRIME|CP)\M', 'COMPRIME'),
             ('GELULE', '\m(GELULE|GLE|GELULES)\M', 'GELULE'),
             ('BUVABLE', '\m(SIROP|SIR|BUV|BUVABLE)\M', 'BUVABLE|SIROP'),
             ('SUPPOSITOIRE', '\m(SUPPO|SUPP|SUPPOSITOIRE)\M', 'SUPPOSITOIRE'),
             ('INJECTABLE', '\m(INJ|INJECTABLE|AMP)\M', 'INJECTABLE'),
             ('CREME', '\m(CREME|CR)\M', 'CREME'),
             ('POMMADE', '\m(POMMADE|POM)\M', 'POMMADE'),
             ('COLLYRE', '\m(COLLYRE|COLL)\M', 'COLLYRE'),
             ('SACHET', '\m(SACHET|SACH)\M', 'SACHET|POUDRE')
    ),
    produit_forme AS (
      SELECT c.produit_id, array_agg(f.motif_specialite) AS motifs
      FROM cible c
               JOIN forme_ref f ON c.norm ~ f.motif_produit
      GROUP BY c.produit_id
    ),
    -- Molécules de référence d'une spécialité : la fraction thérapeutique si elle existe, sinon la substance active.
    ref_mol AS (
      SELECT c.id, c.cis, c.dci_id, c.dosage_canon, c.unite_canon
      FROM ref_specialite_composition c
      WHERE c.nature = 'FT'
         OR NOT EXISTS (SELECT 1 FROM ref_specialite_composition f WHERE f.cis = c.cis AND f.nature = 'FT')
    ),
    spec_dci AS (
      SELECT cis, array_agg(DISTINCT dci_id ORDER BY dci_id) AS arr
      FROM ref_mol
      WHERE dci_id IS NOT NULL
      GROUP BY cis
    ),
    spec_dosee AS (
      SELECT cis, count(*) AS nb FROM ref_mol WHERE dosage_canon IS NOT NULL GROUP BY cis
    ),
    -- DCI du produit : celles du catalogue (déclarées par une personne, ou posées par un passage précédent) ;
    -- à défaut, celle lue en tête de libellé. non_reliees compte les DCI du catalogue que le référentiel ne
    -- connaît pas : on ne peut alors rien confirmer, et le produit ne sera jamais SUR (voir conflit_dci).
    dci_catalogue AS (
      SELECT pd.produit_id,
             array_agg(DISTINCT rd.id ORDER BY rd.id) FILTER (WHERE rd.id IS NOT NULL) AS arr,
             count(*) FILTER (WHERE rd.id IS NULL)                                      AS non_reliees
      FROM produit_dci pd
               JOIN cible c ON c.produit_id = pd.produit_id
               LEFT JOIN ref_dci rd ON rd.dci_id = pd.dci_id
      GROUP BY pd.produit_id
    ),
    dci_lue AS (
      SELECT DISTINCT ON (c.produit_id) c.produit_id, rd.id AS ref_dci_id
      FROM cible_nom c
               JOIN ref_dci rd ON split_part(rd.libelle_normalise, ' ', 1) = split_part(c.norm, ' ', 1)
          AND (c.norm = rd.libelle_normalise OR c.norm LIKE rd.libelle_normalise || ' %')
      ORDER BY c.produit_id, length(rd.libelle_normalise) DESC
    ),
    dci_produit AS (
      SELECT c.produit_id,
             CASE WHEN dc.produit_id IS NOT NULL THEN dc.arr ELSE ARRAY [dl.ref_dci_id] END AS arr,
             dc.produit_id IS NOT NULL                                                       AS declaree,
             COALESCE(dc.non_reliees, 0)                                                     AS non_reliees
      FROM cible c
               LEFT JOIN dci_catalogue dc ON dc.produit_id = c.produit_id
               LEFT JOIN dci_lue dl ON dl.produit_id = c.produit_id
      WHERE dc.produit_id IS NOT NULL OR dl.ref_dci_id IS NOT NULL
    ),
    -- Candidats : trois voies, qui se font concurrence par leur score.
    cand_nom AS (
      SELECT c.produit_id, s.cis, 'NOM' AS origine
      FROM cible_nom c
               JOIN ref_specialite s ON split_part(s.libelle_normalise, ' ', 1) = split_part(c.nom, ' ', 1)
          AND (s.libelle_normalise = c.nom OR s.libelle_normalise LIKE c.nom || ' %')
      WHERE length(c.nom) >= 4
    ),
    cand_dci AS (
      SELECT dp.produit_id, sd.cis, 'DCI' AS origine
      FROM dci_produit dp
               JOIN spec_dci sd ON sd.arr = dp.arr
      WHERE dp.non_reliees = 0
    ),
    -- Nom approché (faute de frappe, singulier/pluriel) : similarité trigramme sur la marque, le premier mot du nom.
    cand_approche AS (
      SELECT c.produit_id, x.cis, 'APPROCHE' AS origine
      FROM cible_nom c
               CROSS JOIN LATERAL (
        SELECT s.cis
        FROM ref_specialite s
        WHERE split_part(s.libelle_normalise, ' ', 1) % split_part(c.nom, ' ', 1)
        ORDER BY similarity(split_part(s.libelle_normalise, ' ', 1), split_part(c.nom, ' ', 1)) DESC
        LIMIT 50
      ) x
      WHERE length(split_part(c.nom, ' ', 1)) >= 5
        AND NOT EXISTS (SELECT 1 FROM cand_nom n WHERE n.produit_id = c.produit_id)
    ),
    cand AS (
      SELECT * FROM cand_nom
      UNION
      SELECT * FROM cand_dci
      UNION
      SELECT * FROM cand_approche
    ),
    -- Pour chaque couple candidat : combien de molécules dosées de la spécialité retrouvent leur dosage dans le libellé.
    dosage_concordant AS (
      SELECT k.produit_id, k.cis, count(*) AS nb
      FROM (SELECT DISTINCT produit_id, cis FROM cand) k
               JOIN ref_mol m ON m.cis = k.cis
               JOIN dosage_produit d ON d.produit_id = k.produit_id AND d.unite = m.unite_canon AND d.valeur = round(m.dosage_canon, 4)
      GROUP BY k.produit_id, k.cis
    ),
    -- Mesures par couple (produit, spécialité).
    mesure AS MATERIALIZED (
      SELECT k.produit_id, k.cis, k.origine, s.commercialisee, s.type_generique,
             COALESCE(pdo.nb, 0) > 0 AS produit_dose,
             COALESCE(sdo.nb, 0) > 0 AS spec_dosee,
             COALESCE(sdo.nb, 0) > 0 AND COALESCE(dco.nb, 0) = sdo.nb AS dosage_ok,
             pf.motifs IS NOT NULL AS forme_connue,
             COALESCE(s.forme_normalisee ~ ANY (pf.motifs), FALSE) AS forme_ok,
             COALESCE(dp.declaree AND sd.arr IS NOT NULL AND (dp.non_reliees > 0 OR sd.arr IS DISTINCT FROM dp.arr), FALSE) AS conflit_dci
      FROM cand k
               JOIN ref_specialite s ON s.cis = k.cis
               LEFT JOIN produit_dosage pdo ON pdo.produit_id = k.produit_id
               LEFT JOIN spec_dosee sdo ON sdo.cis = k.cis
               LEFT JOIN dosage_concordant dco ON dco.produit_id = k.produit_id AND dco.cis = k.cis
               LEFT JOIN produit_forme pf ON pf.produit_id = k.produit_id
               LEFT JOIN dci_produit dp ON dp.produit_id = k.produit_id
               LEFT JOIN spec_dci sd ON sd.cis = k.cis
    ),
    note AS (
      SELECT m.*,
             greatest(0, least(100,
                 CASE m.origine WHEN 'NOM' THEN 50 WHEN 'DCI' THEN 40 ELSE 30 END
                 + CASE WHEN m.produit_dose AND m.spec_dosee THEN (CASE WHEN m.dosage_ok THEN 30 ELSE -20 END) ELSE 0 END
                 + CASE WHEN m.forme_ok THEN 20 WHEN m.forme_connue THEN -10 ELSE 0 END
                 - CASE WHEN m.conflit_dci THEN 25 ELSE 0 END
             )) AS score
      FROM mesure m
    ),
    classe AS (
      SELECT n.*,
             row_number() OVER (PARTITION BY n.produit_id
                                ORDER BY n.score DESC, n.commercialisee DESC, (n.type_generique = 'PRINCEPS') DESC NULLS LAST, n.cis) AS rang,
             count(*) OVER (PARTITION BY n.produit_id, n.score) AS ex_aequo
      FROM note n
    ),
    retenu AS MATERIALIZED (
      SELECT c.produit_id, c.cis, c.score,
             CASE
               WHEN c.origine = 'NOM' AND c.dosage_ok AND NOT c.conflit_dci AND c.ex_aequo = 1 THEN 'SUR'
               WHEN c.origine = 'DCI' AND c.score >= 40 THEN 'PAR_DCI'
               ELSE 'A_VERIFIER'
             END AS statut,
             concat_ws('; ',
                       CASE c.origine WHEN 'NOM' THEN 'nom retrouvé' WHEN 'DCI' THEN 'rattaché par la molécule' ELSE 'nom approché' END,
                       CASE WHEN NOT c.produit_dose THEN 'dosage absent du libellé'
                            WHEN NOT c.spec_dosee THEN 'dosage du référentiel inconnu'
                            WHEN c.dosage_ok THEN 'dosage identique' ELSE 'dosage différent' END,
                       CASE WHEN c.forme_ok THEN 'forme concordante' WHEN c.forme_connue THEN 'forme différente' END,
                       CASE WHEN c.conflit_dci THEN 'DCI du produit absente ou différente de celle du référentiel' END,
                       CASE WHEN c.ex_aequo > 1 THEN c.ex_aequo || ' candidats de même score' END) AS motif
      FROM classe c
      WHERE c.rang = 1 AND c.score >= 40
    ),
    resultat AS (
      SELECT c.produit_id, r.cis,
             COALESCE(r.statut, 'NON_TROUVE')                  AS statut,
             COALESCE(r.score, 0)                              AS score,
             COALESCE(r.motif, 'aucun candidat suffisant')     AS motif
      FROM cible c
               LEFT JOIN retenu r ON r.produit_id = c.produit_id
    )
  INSERT INTO produit_ref_specialite AS t (produit_id, cis, statut, score, motif, decision, calcule_le)
  SELECT produit_id, cis, statut, score, left(motif, 255), 'EN_ATTENTE', now() AT TIME ZONE 'UTC'
  FROM resultat
  ON CONFLICT (produit_id) DO UPDATE
    SET cis        = EXCLUDED.cis,
        statut     = EXCLUDED.statut,
        score      = EXCLUDED.score,
        motif      = EXCLUDED.motif,
        calcule_le = EXCLUDED.calcule_le
  WHERE t.decision = 'EN_ATTENTE';

  GET DIAGNOSTICS v_nb = ROW_COUNT;
  RETURN v_nb;
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Application des propositions sûres.
--   * Éligibles : EN_ATTENTE, statut SUR ou PAR_DCI, spécialité connue.
--   * Un produit SANS DCI reçoit celles de la spécialité (fraction thérapeutique, sinon substance
--     active), rang 1 = première molécule, dosage ramené à l'unité commune ; produit.dci_id est
--     alignée sur le rang 1 (transition de V2.1.11). Tout ou rien : si une molécule n'est pas encore
--     reliée au catalogue (ref_dci.dci_id), la proposition reste EN_ATTENTE et sera reprise dès que
--     la DCI manquante sera importée.
--   * Un produit déjà doté de DCI n'est pas modifié ; sa proposition est simplement acceptée.
-- Retourne le nombre de propositions acceptées.
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION ref_appliquer_rapprochements(p_produit_ids integer[] DEFAULT NULL) RETURNS integer
  LANGUAGE plpgsql
AS
$$
DECLARE
  v_nb integer;
BEGIN
  -- Une seule instruction : les CTE qui écrivent s'exécutent toutes, sur le même instantané.
  WITH eligibles AS (
    SELECT r.id AS rapprochement_id, r.produit_id, r.cis
    FROM produit_ref_specialite r
    WHERE r.decision = 'EN_ATTENTE'
      AND r.statut IN ('SUR', 'PAR_DCI')
      AND r.cis IS NOT NULL
      AND (p_produit_ids IS NULL OR r.produit_id = ANY (p_produit_ids))
  ),
  -- Molécules de référence de chaque spécialité éligible, avec leur DCI du catalogue (NULL si non reliée).
  mol AS (
    SELECT e.rapprochement_id, e.produit_id, c.id AS comp_id, rd.dci_id, c.dosage_canon, c.unite_canon
    FROM eligibles e
             JOIN ref_specialite_composition c ON c.cis = e.cis
             LEFT JOIN ref_dci rd ON rd.id = c.dci_id
    WHERE c.nature = 'FT'
       OR NOT EXISTS (SELECT 1 FROM ref_specialite_composition f WHERE f.cis = c.cis AND f.nature = 'FT')
  ),
  completes AS (
    SELECT rapprochement_id
    FROM mol
    GROUP BY rapprochement_id
    HAVING bool_and(dci_id IS NOT NULL)
  ),
  acceptes AS MATERIALIZED (
    SELECT e.rapprochement_id, e.produit_id
    FROM eligibles e
    WHERE EXISTS (SELECT 1 FROM produit_dci pd WHERE pd.produit_id = e.produit_id)
       OR e.rapprochement_id IN (SELECT rapprochement_id FROM completes)
  ),
  -- DCI à poser : uniquement pour les produits qui n'en ont aucune.
  a_poser AS (
    SELECT DISTINCT ON (m.produit_id, m.dci_id) m.produit_id, m.dci_id, m.comp_id, m.dosage_canon, m.unite_canon
    FROM mol m
             JOIN acceptes a ON a.rapprochement_id = m.rapprochement_id
    WHERE m.dci_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM produit_dci pd WHERE pd.produit_id = m.produit_id)
    ORDER BY m.produit_id, m.dci_id, m.comp_id
  ),
  rangees AS (
    SELECT p.*, row_number() OVER (PARTITION BY p.produit_id ORDER BY p.comp_id) AS rang FROM a_poser p
  ),
  inseres AS (
    INSERT INTO produit_dci (produit_id, dci_id, rang, dosage_valeur, dosage_unite)
      SELECT produit_id, dci_id, rang,
             CASE WHEN dosage_canon BETWEEN 0 AND 99999999 THEN round(dosage_canon, 4) END,
             CASE WHEN dosage_canon BETWEEN 0 AND 99999999 THEN left(unite_canon, 10) END
      FROM rangees
      RETURNING produit_id
  ),
  alignes AS (
    UPDATE produit p
      SET dci_id = r.dci_id
      FROM rangees r
      WHERE r.rang = 1 AND r.produit_id = p.id AND p.dci_id IS NULL
      RETURNING p.id
  ),
  maj AS (
    UPDATE produit_ref_specialite r
      SET decision = 'AUTO', decide_le = now() AT TIME ZONE 'UTC',
          dci_posee = EXISTS (SELECT 1 FROM inseres i WHERE i.produit_id = r.produit_id)
      FROM acceptes a
      WHERE a.rapprochement_id = r.id
      RETURNING r.id
  )
  SELECT count(*) INTO v_nb FROM maj;
  RETURN v_nb;
END
$$;

-- Rapproche puis applique : le point d'entrée du batch de nuit. Retourne les propositions acceptées d'office.
CREATE FUNCTION ref_automatiser_rapprochement(p_produit_ids integer[] DEFAULT NULL, p_forcer boolean DEFAULT FALSE)
  RETURNS integer
  LANGUAGE plpgsql
AS
$$
BEGIN
  PERFORM ref_rapprocher_produits(p_produit_ids, p_forcer);
  RETURN ref_appliquer_rapprochements(p_produit_ids);
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Après l'ajout de DCI au catalogue : relie les DCI au référentiel, recalcule les propositions
-- EN_ATTENTE des produits dont le libellé commence par l'une de ces DCI (c'est ainsi que le
-- rapprochement lit la molécule dans un libellé).
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION ref_rapprocher_apres_nouvelles_dci(p_dci_ids integer[]) RETURNS integer
  LANGUAGE plpgsql
AS
$$
DECLARE
  v_ids integer[];
BEGIN
  PERFORM ref_lier_dci(p_dci_ids);

  SELECT COALESCE(array_agg(DISTINCT p.id), ARRAY []::integer[])
  INTO v_ids
  FROM produit p
           JOIN dci d ON d.id = ANY (p_dci_ids)
  WHERE p.status = 'ENABLE'
    AND p.type_produit = 'PACKAGE'
    AND (ref_normaliser(p.libelle) = ref_normaliser(d.libelle)
      OR ref_normaliser(p.libelle) LIKE ref_normaliser(d.libelle) || ' %');

  PERFORM ref_rapprocher_produits(v_ids, TRUE);
  -- Sans restriction : une proposition SUR/PAR_DCI restée EN_ATTENTE faute de cette DCI devient applicable.
  RETURN ref_appliquer_rapprochements(NULL);
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Dissociation : retirer une DCI d'un produit (fiche produit, rattachement en lot, fusion…) contredit le
-- rapprochement qui l'avait posée. La proposition passe à REJETE — elle n'est donc plus jamais
-- recalculée ni réappliquée — pour peu que la DCI retirée appartienne à la spécialité retenue.
-- Un déclencheur, et non du code applicatif : il couvre tous les chemins d'écriture.
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION produit_dci_dissociation() RETURNS trigger
  LANGUAGE plpgsql
AS
$$
BEGIN
  UPDATE produit_ref_specialite r
  SET decision  = 'REJETE',
      decide_le = now() AT TIME ZONE 'UTC',
      motif     = left(concat_ws('; ', r.motif, 'DCI dissociée du produit'), 255)
  WHERE r.produit_id = OLD.produit_id
    AND r.decision IN ('EN_ATTENTE', 'AUTO', 'VALIDE')
    AND r.cis IS NOT NULL
    AND EXISTS (SELECT 1
                FROM ref_specialite_composition c
                         JOIN ref_dci rd ON rd.id = c.dci_id
                WHERE c.cis = r.cis
                  AND rd.dci_id = OLD.dci_id);
  RETURN NULL;
END
$$;

CREATE TRIGGER produit_dci_apres_suppression
  AFTER DELETE ON produit_dci
  FOR EACH ROW EXECUTE FUNCTION produit_dci_dissociation();
