-- Suivi d'ordonnance .
--
-- L'ordonnance est un objet d'en-tête qui SURVIT à la vente : reste à délivrer, renouvellement.
-- Elle alimente le panier sans le remplacer. Aucune colonne dupliquée dans `sales` (table
-- partitionnée) : prescripteur et date se lisent par jointure.

-- Référentiel local, constitué par l'usage (création à la volée). Jamais supprimé : `actif`.
CREATE TABLE prescripteur (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom           varchar(100) NOT NULL,
  prenom        varchar(100),
  specialite    varchar(100),
  -- Facultatif ; unique s'il est renseigné (anti-doublon, clé d'un éventuel import d'annuaire).
  numero_ordre  varchar(30),
  structure     varchar(150),
  telephone     varchar(30),
  actif         boolean      NOT NULL DEFAULT TRUE,
  recherche     varchar(255) GENERATED ALWAYS AS (ref_normaliser(nom || ' ' || coalesce(prenom, ''))) STORED NOT NULL,
  created_at    timestamp    NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by_id integer REFERENCES app_user (id)
);

CREATE UNIQUE INDEX prescripteur_numero_ordre_uk ON prescripteur (numero_ordre) WHERE numero_ordre IS NOT NULL;
CREATE INDEX prescripteur_recherche_trgm_idx ON prescripteur USING gin (recherche gin_trgm_ops);

CREATE TABLE ordonnance (
  id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Obligatoire : le suivi et le contrôle d'historique supposent un client (question 11 du plan).
  customer_id              integer     NOT NULL REFERENCES customer (id),
  prescripteur_id          integer REFERENCES prescripteur (id),
  date_prescription        date        NOT NULL,
  source                   varchar(10) NOT NULL DEFAULT 'MANUELLE'
    CONSTRAINT ordonnance_source_check CHECK (source IN ('MANUELLE', 'SCAN', 'PDF')),
  -- Nombre de renouvellements autorisés : la capacité de chaque ligne est quantite_prescrite x (renouvellements + 1).
  renouvellements          smallint    NOT NULL DEFAULT 0 CONSTRAINT ordonnance_renouvellements_check CHECK (renouvellements >= 0),
  date_fin_validite        date,
  -- Clôture décidée par une personne (ordonnance soldée à la main, annulée par le médecin). Le statut
  -- EN_COURS / TERMINEE / EXPIREE est DÉRIVÉ à la lecture (reste à délivrer, date de fin) : il ne
  -- peut donc pas être périmé.
  cloturee                 boolean     NOT NULL DEFAULT FALSE,
  note                     varchar(500),
  created_at               timestamp   NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by_id            integer REFERENCES app_user (id)
);

CREATE INDEX ordonnance_customer_idx ON ordonnance (customer_id);
CREATE INDEX ordonnance_prescripteur_idx ON ordonnance (prescripteur_id);

-- Pas de colonne DCI : les molécules se déduisent du produit, elles ne sont pas dupliquées.
CREATE TABLE ordonnance_ligne (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ordonnance_id       integer      NOT NULL REFERENCES ordonnance (id) ON DELETE CASCADE,
  rang                smallint     NOT NULL,
  -- Texte tel que lu ou saisi ; la confiance n'existe que pour une ligne proposée par l'OCR (lot 4).
  texte_lu            varchar(255),
  confiance           smallint CONSTRAINT ordonnance_ligne_confiance_check CHECK (confiance BETWEEN 0 AND 100),
  -- Produit PRESCRIT (ou celui qui s'en approche) ; le produit réellement délivré est sur la délivrance.
  produit_id          integer REFERENCES produit (id),
  posologie           varchar(150),
  duree_jours         integer CONSTRAINT ordonnance_ligne_duree_check CHECK (duree_jours > 0),
  quantite_prescrite  integer      NOT NULL CONSTRAINT ordonnance_ligne_quantite_check CHECK (quantite_prescrite > 0),
  CONSTRAINT ordonnance_ligne_rang_uk UNIQUE (ordonnance_id, rang),
  CONSTRAINT ordonnance_ligne_designation_check CHECK (produit_id IS NOT NULL OR texte_lu IS NOT NULL)
);

-- Source de vérité du reste à délivrer. La ligne de vente porte la quantité réellement vendue ; la
-- délivrance ne compte QUE si sa vente est clôturée et non annulée (jointure à la lecture) : une
-- vente abandonnée, en attente ou annulée ne consomme donc pas l'ordonnance, sans rien à défaire.
CREATE TABLE ordonnance_delivrance (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ligne_id        integer NOT NULL REFERENCES ordonnance_ligne (id) ON DELETE CASCADE,
  sales_line_id   bigint  NOT NULL,
  sales_line_date date    NOT NULL,
  created_at      timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
  CONSTRAINT ordonnance_delivrance_sales_line_fk FOREIGN KEY (sales_line_id, sales_line_date)
    REFERENCES sales_line (id, sale_date) ON DELETE CASCADE,
  CONSTRAINT ordonnance_delivrance_uk UNIQUE (ligne_id, sales_line_id, sales_line_date)
);

CREATE INDEX ordonnance_delivrance_sales_line_idx ON ordonnance_delivrance (sales_line_id, sales_line_date);

-- Index d'en-tête : « cette vente a servi l'ordonnance du Dr X du 12/09 ».
CREATE TABLE ordonnance_vente (
  ordonnance_id integer NOT NULL REFERENCES ordonnance (id) ON DELETE CASCADE,
  sales_id      bigint  NOT NULL,
  sales_date    date    NOT NULL,
  PRIMARY KEY (ordonnance_id, sales_id, sales_date),
  CONSTRAINT ordonnance_vente_sales_fk FOREIGN KEY (sales_id, sales_date)
    REFERENCES sales (id, sale_date) ON DELETE CASCADE
);

CREATE INDEX ordonnance_vente_sales_idx ON ordonnance_vente (sales_id, sales_date);
