-- PLAN-PRODUIT-DCI-N-N : un produit porte plusieurs molécules (associations).
-- produit.dci_id est conservée pendant la transition, alignée sur la molécule principale (rang 1).

CREATE TABLE produit_dci (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produit_id    integer      NOT NULL REFERENCES produit (id) ON DELETE CASCADE,
  dci_id        integer      NOT NULL REFERENCES dci (id),
  rang          smallint     NOT NULL DEFAULT 1 CONSTRAINT produit_dci_rang_check CHECK (rang >= 1),
  dosage_valeur numeric(12, 4),
  dosage_unite  varchar(10),
  -- Différées : réordonner ou remplacer les molécules d'un produit passe par des états intermédiaires.
  CONSTRAINT produit_dci_produit_dci_uk UNIQUE (produit_id, dci_id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT produit_dci_produit_rang_uk UNIQUE (produit_id, rang) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX produit_dci_dci_idx ON produit_dci (dci_id);

INSERT INTO produit_dci (produit_id, dci_id, rang)
SELECT id, dci_id, 1
FROM produit
WHERE dci_id IS NOT NULL;

-- Les associations saisies comme une seule DCI (« A/B », « A+B ») : marquées, pas encore décomposées.
ALTER TABLE dci
  ADD COLUMN statut varchar(10) NOT NULL DEFAULT 'ACTIVE'
    CONSTRAINT dci_statut_check CHECK (statut IN ('ACTIVE', 'COMPOSEE', 'ARCHIVEE'));

UPDATE dci
SET statut = 'COMPOSEE'
WHERE libelle ~ '[/+]';
