-- Vues enregistrées de l'onglet Analyser du pilotage .
-- Sans propriétaire : livrée d'office, ni modifiable ni supprimable. La période vient de la barre de la page, pas de la vue.
CREATE TABLE IF NOT EXISTS pilotage_vue
(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle         VARCHAR(100) NOT NULL,
  indicateurs     VARCHAR(255) NOT NULL,
  axe             VARCHAR(30)  NOT NULL,
  axe_croise      VARCHAR(30),
  nombre_elements INTEGER      NOT NULL,
  tri             VARCHAR(20)  NOT NULL,
  affichage       VARCHAR(20)  NOT NULL,
  proprietaire_id INTEGER REFERENCES app_user (id) ON DELETE CASCADE,
  partagee        BOOLEAN      NOT NULL DEFAULT FALSE,
  ordre           INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS pilotage_vue_proprietaire_idx ON pilotage_vue (proprietaire_id);

-- « Génériques » (plan) devient « CA par DCI » : aucun indicateur de part générique n'existe encore.
INSERT INTO pilotage_vue (libelle, indicateurs, axe, axe_croise, nombre_elements, tri, affichage, ordre)
SELECT v.libelle, v.indicateurs, v.axe, v.axe_croise, v.nombre_elements, v.tri, v.affichage, v.ordre
FROM (VALUES ('CA par famille', 'CA_TTC', 'FAMILLE', NULL, 0, 'VALEUR', 'BARRES', 1),
             ('Meilleures ventes', 'CA_TTC,QUANTITES_VENDUES', 'PRODUIT', NULL, 50, 'VALEUR', 'TABLEAU', 2),
             ('Hit-parade par laboratoire', 'CA_TTC,MARGE_BRUTE', 'LABORATOIRE', NULL, 20, 'VALEUR', 'BARRES', 3),
             ('Ventes par taux de TVA', 'CA_HT,CA_TTC', 'TVA', NULL, 0, 'VALEUR', 'TABLEAU', 4),
             ('Ordonnance / conseil', 'CA_TTC,PANIER_MOYEN,NB_VENTES', 'TYPE_PRESCRIPTION', NULL, 0, 'VALEUR', 'TABLEAU', 5),
             ('Comptant / assurance / carnet', 'CA_TTC,PANIER_MOYEN,PART_TIERS_PAYANT', 'NATURE_VENTE', NULL, 0, 'VALEUR', 'TABLEAU', 6),
             ('Fréquentation horaire', 'NB_VENTES', 'HEURE', 'JOUR_SEMAINE', 0, 'VALEUR', 'CROISE', 7),
             ('CA par DCI', 'CA_TTC', 'DCI', NULL, 50, 'VALEUR', 'TABLEAU', 8),
             ('Produits en recul', 'CA_TTC', 'PRODUIT', NULL, 50, 'ECART_BAISSE', 'TABLEAU', 9)) AS v (libelle, indicateurs, axe, axe_croise, nombre_elements, tri, affichage, ordre)
WHERE NOT EXISTS (SELECT 1 FROM pilotage_vue WHERE proprietaire_id IS NULL);
