-- Fiche client, lot 4 : suivi et communication (docs/PLAN-FICHE-CLIENT.md).

-- Traitement chronique : déclaré par molécule, pour que génériques et princeps comptent pareil ;
-- un produit imposé le restreint à ce seul produit (patient non substituable).
CREATE TABLE customer_traitement_chronique (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id         integer      NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  dci_id              integer REFERENCES dci (id),
  produit_id          integer REFERENCES produit (id),
  dosage              varchar(50),
  posologie           varchar(150),
  duree_jours         integer      NOT NULL CHECK (duree_jours > 0),
  date_ordonnance     date,
  date_fin_ordonnance date,
  note                text,
  actif               boolean      NOT NULL DEFAULT TRUE,
  created_at          timestamp    NOT NULL DEFAULT now(),
  updated_at          timestamp    NOT NULL DEFAULT now(),
  updated_by_id       integer REFERENCES app_user (id),
  CONSTRAINT traitement_chronique_cible_check CHECK (dci_id IS NOT NULL OR produit_id IS NOT NULL)
);

CREATE INDEX traitement_chronique_customer_idx ON customer_traitement_chronique (customer_id);

-- Consentement aux messages, par canal : chaque changement est une ligne, la dernière fait foi.
CREATE TABLE customer_consentement (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer     NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
  canal       varchar(10) NOT NULL CHECK (canal IN ('SMS', 'WHATSAPP', 'EMAIL')),
  accorde     boolean     NOT NULL,
  user_id     integer     NOT NULL REFERENCES app_user (id),
  created_at  timestamp   NOT NULL DEFAULT now()
);

CREATE INDEX customer_consentement_customer_idx ON customer_consentement (customer_id, canal, created_at);

-- Renouvellement exceptionnel d'un traitement chronique quand l'ordonnance a expiré (inspiré de
-- l'article L. 5125-23-1 du code de la santé publique français) : désactivé tant que l'officine ne
-- l'a pas validé pour sa réglementation.
INSERT INTO app_configuration (name, value, description, created, updated, value_type)
VALUES ('APP_RENOUVELLEMENT_EXCEPTIONNEL', '0',
        'Signaler qu''un traitement chronique dont l''ordonnance a expiré peut être renouvelé à titre exceptionnel (hors stupéfiants, ordonnance d''au moins trois mois, première délivrance dans le mois qui suit l''expiration).',
        NOW(), NOW(), 'BOOLEAN'),
       ('APP_RENOUVELLEMENT_EXCEPTIONNEL_MOIS', '3',
        'Durée maximale, en mois après l''expiration de l''ordonnance, du renouvellement exceptionnel d''un traitement chronique (délivrances d''un mois).',
        NOW(), NOW(), 'NUMBER'),
       ('APP_RAPPEL_RENOUVELLEMENT_JOURS', '5',
        'Nombre de jours avant la date de renouvellement d''un traitement chronique à partir duquel le patient est signalé à relancer.',
        NOW(), NOW(), 'NUMBER')
ON CONFLICT (name) DO NOTHING;
