DELETE FROM rayon where storage_id=2;
DELETE FROM storage WHERE id=2;
UPDATE storage SET name='Stock rayon' WHERE id=1;



create table suggestion_reassort
(
  id              integer generated by default as identity
    primary key,
  created_at      timestamp(6) not null,
  reference       varchar(20)  not null,
  statut          varchar(15)
    constraint suggestion_reassort_statut_check
      check ((statut)::text = ANY ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying])::text[])),
  type_reassort   varchar(10)
    constraint suggestion_reassort_type_reassort_check
      check ((type_reassort)::text = ANY
             ((ARRAY ['RAYON'::character varying, 'RESERVE'::character varying])::text[])),
  updated_at      timestamp(6) not null,
  last_user_edit_id integer
    constraint fkpfycr16qblf3q4a6p0ghiiq5r
      references app_user,
  magasin_id      integer      not null
    constraint fkeno8b569afxgqg48nxijh1b99
      references magasin
);



create index type_reassort_index
  on suggestion_reassort (type_reassort);

create index suggestion_reassort_statut_index
  on suggestion_reassort (statut);



create table ligne_reassort
(
  id               integer generated by default as identity
    primary key,
  quantity         integer,
  updated_at       timestamp(6) not null,
  reassort_id      integer      not null
    constraint fkrqiky1hkt9d011gtkwsycr14v
      references suggestion_reassort,
  stock_produit_id integer      not null
    constraint fkil10dduqkuyuf02jffy0rrrfi
      references stock_produit,
  constraint ukstab1qvr0o4q9fiesjrvl6vie
    unique (reassort_id, stock_produit_id)
);

DROP TABLE IF EXISTS  repartition_stock_produit ;
create table repartition_stock_produit
(
  id                           integer generated by default as identity
    primary key,
  created_at                   timestamp(6) not null,
  dest_final_stock             integer      not null,
  dest_init_stock              integer      not null,
  qty_mvt                      integer      not null,
  source_final_stock           integer,
  source_init_stock            integer,
  type_repartition             smallint     not null
    constraint repartition_stock_produit_type_repartition_check
      check ((type_repartition >= 0) AND (type_repartition <= 1)),
  stock_produit_destination_id integer      not null
    constraint fkrxga8j2mjur3aw43h3bq6l909
      references stock_produit,
  stock_produit_source_id      integer
    constraint fkgyu4w5fylq30wrdc1n284yuqg
      references stock_produit,
  user_id                      integer      not null
    constraint fk9lxmafennj6krja8nqnkrd50
      references app_user
);



create index type_repartition_index
  on repartition_stock_produit (type_repartition);



