

create table IF NOT EXISTS inventory_lot
(
    id                   bigint generated by default as identity
        primary key,
    gap                  integer,
    inventory_value_cost integer,
    last_unit_price      integer,
    quantity_init        integer,
    quantity_on_hand     integer,
    updated              boolean      not null,
    updated_at           timestamp(6) not null,
    lot_id               integer      not null
        constraint fk3uxvn5otdy1biefw2v03ylpfh
            references lot,
    store_inventory_id   bigint       not null
        constraint fkcme6qro2ek4b0hwd29wh2tk3w
            references store_inventory,
    constraint ukfqtp7jyosytdyc3jbpubgu636
        unique (lot_id, store_inventory_id)
);

ALTER TABLE store_inventory
  ADD COLUMN IF NOT EXISTS category VARCHAR(20) NOT NULL;

ALTER TABLE store_inventory
  ADD CONSTRAINT  s_inventory_category_check
CHECK (category IN ('STOCK_TOTAL', 'PAR_LOT'));


ALTER TABLE lot
  ADD COLUMN IF NOT EXISTS produit_id INTEGER NOT NULL;

ALTER TABLE lot
  ADD CONSTRAINT  fkrqxepb1nx0y6syip91743n5pa0
  FOREIGN KEY (produit_id) REFERENCES produit(id);

