
create table classification_config
(
  id                          integer generated by default as identity
    primary key,
  auto_classification_enabled boolean       not null default true,
  changement_min_score        integer       not null default 10
    constraint classification_config_changement_min_score_check
      check ((changement_min_score <= 50) AND (changement_min_score >= 0)),
  nb_mois_analyse             integer       not null default 12
    constraint classification_config_nb_mois_analyse_check
      check ((nb_mois_analyse >= 6) AND (nb_mois_analyse <= 24)),
  nb_mois_min_nouveau_produit integer       not null default 6
    constraint classification_config_nb_mois_min_nouveau_produit_check
      check ((nb_mois_min_nouveau_produit >= 1) AND (nb_mois_min_nouveau_produit <= 12)),
  poids_ca                    numeric(3, 2) not null default 0.50,
  poids_frequence             numeric(3, 2) not null default 0.20,
  poids_rotation              numeric(3, 2) not null default  0.30,
  rotation_a                  numeric(5, 2) not null default 8.0,
  rotation_a_plus             numeric(5, 2) not null default 12.0,
  rotation_b                  numeric(5, 2) not null default 4.0,
  rotation_c                  numeric(5, 2) not null default 2.0,
  seuil_a                     integer       not null DEFAULT 80
    constraint classification_config_seuil_a_check
      check ((seuil_a <= 100) AND (seuil_a >= 0)),
  seuil_a_plus                integer       not null default 90
    constraint classification_config_seuil_a_plus_check
      check ((seuil_a_plus <= 100) AND (seuil_a_plus >= 0)),
  seuil_b                     integer       not null default 60
    constraint classification_config_seuil_b_check
      check ((seuil_b <= 100) AND (seuil_b >= 0)),
  seuil_c                     integer       not null default 40
    constraint classification_config_seuil_c_check
      check ((seuil_c <= 100) AND (seuil_c >= 0)),
  updated_at                  timestamp(6)  not null default now(),
  updated_by                  integer
    constraint fkogdh3vnqy20an3yowt4fep8ju
      references app_user
);



create table classification_criticite_log
(
  id                   integer generated by default as identity
    primary key,
  ancienne_classe      varchar(3)
    constraint classification_criticite_log_ancienne_classe_check
      check ((ancienne_classe)::text = ANY
             ((ARRAY ['A_PLUS'::character varying, 'A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying])::text[])),
  ca_12_mois           bigint,
  classification_type  varchar(20)  not null default 'AUTO'
    constraint classification_criticite_log_classification_type_check
      check ((classification_type)::text = ANY
             ((ARRAY ['AUTO'::character varying, 'MANUAL'::character varying, 'INITIAL'::character varying])::text[])),
  created_at           timestamp(6) not null default now(),
  frequence_vente_mois integer,
  nouvelle_classe      varchar(3)   not null
    constraint classification_criticite_log_nouvelle_classe_check
      check ((nouvelle_classe)::text = ANY
             ((ARRAY ['A_PLUS'::character varying, 'A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying])::text[])),
  raison_changement    varchar(255),
  rotation_annuelle    numeric(6, 2),
  score_total          numeric(5, 2),
  vmm_12_mois          integer,
  produit_id           integer      not null
    constraint fknkycq2bf9g8iboogwgj5myoas
      references produit,
  user_id              integer
    constraint fk87qxskfgjgx2xov8d04g96h0c
      references app_user
);


create index idx_classif_log_produit
  on classification_criticite_log (produit_id);

create index idx_classif_log_date
  on classification_criticite_log (created_at);

create index idx_classif_log_type
  on classification_criticite_log (classification_type);









COMMENT ON TABLE classification_criticite_log IS 'Historique des changements de classe de criticité des produits';
COMMENT ON COLUMN classification_criticite_log.classification_type IS 'AUTO=reclassification automatique, MANUAL=override admin, INITIAL=classification initiale';

-- Insérer configuration par défaut
INSERT INTO classification_config (poids_ca, poids_rotation, poids_frequence)
VALUES (0.50, 0.30, 0.20);

COMMENT ON TABLE classification_config IS 'Configuration des paramètres de classification dynamique (singleton)';
COMMENT ON COLUMN classification_config.changement_min_score IS 'Écart minimum de score requis pour changer de classe (hysteresis)';

-- ============================================================================
DROP TABLE IF EXISTS v_produit_metriques_classification;
-- Vue analytique des métriques de classification par produit
-- Note: Filtre sur magasin_id = 1 (magasin par défaut) pour le calcul du stock
CREATE OR REPLACE VIEW v_produit_metriques_classification AS
SELECT
    p.id AS produit_id,
    p.libelle,
    p.classe_criticite AS classe_actuelle,

    -- VMM sur 12 mois
    COALESCE(
        (SELECT AVG(quantite_vendue)
         FROM ventes_mensuelles_agregees vma
         WHERE vma.produit_id = p.id
           AND vma.annee_mois >= TO_CHAR(NOW() - INTERVAL '12 months', 'YYYY-MM')
           AND vma.is_frozen = TRUE
        ), 0
    )::INTEGER AS vmm_12_mois,

    -- CA total sur 12 mois (en centimes)
    COALESCE(
        (SELECT SUM(montant_ca)
         FROM ventes_mensuelles_agregees vma
         WHERE vma.produit_id = p.id
           AND vma.annee_mois >= TO_CHAR(NOW() - INTERVAL '12 months', 'YYYY-MM')
           AND vma.is_frozen = TRUE
        ), 0
    )::BIGINT AS ca_12_mois,

    -- Quantité vendue totale sur 12 mois
    COALESCE(
        (SELECT SUM(quantite_vendue)
         FROM ventes_mensuelles_agregees vma
         WHERE vma.produit_id = p.id
           AND vma.annee_mois >= TO_CHAR(NOW() - INTERVAL '12 months', 'YYYY-MM')
           AND vma.is_frozen = TRUE
        ), 0
    )::INTEGER AS qte_vendue_12_mois,

    -- Fréquence de vente (nb de mois avec ventes)
    COALESCE(
        (SELECT COUNT(*)
         FROM ventes_mensuelles_agregees vma
         WHERE vma.produit_id = p.id
           AND vma.annee_mois >= TO_CHAR(NOW() - INTERVAL '12 months', 'YYYY-MM')
           AND vma.is_frozen = TRUE
           AND vma.quantite_vendue > 0
        ), 0
    )::INTEGER AS frequence_vente_mois,

    -- Stock actuel (filtré sur magasin par défaut id=1)
    COALESCE(
        (SELECT SUM(sp.qty_stock + sp.qty_ug)
         FROM stock_produit sp
         JOIN storage s ON sp.storage_id = s.id
         WHERE sp.produit_id = p.id
           AND s.magasin_id = 1
        ), 0
    )::INTEGER AS stock_actuel,

    -- Rotation annuelle = Ventes annuelles / Stock moyen
    CASE
        WHEN COALESCE(
            (SELECT SUM(sp.qty_stock + sp.qty_ug)
             FROM stock_produit sp
             JOIN storage s ON sp.storage_id = s.id
             WHERE sp.produit_id = p.id
               AND s.magasin_id = 1
            ), 0) > 0
        THEN
            COALESCE(
                (SELECT SUM(quantite_vendue)
                 FROM ventes_mensuelles_agregees vma
                 WHERE vma.produit_id = p.id
                   AND vma.annee_mois >= TO_CHAR(NOW() - INTERVAL '12 months', 'YYYY-MM')
                   AND vma.is_frozen = TRUE
                ), 0
            )::DECIMAL / COALESCE(
                (SELECT SUM(sp.qty_stock + sp.qty_ug)
                 FROM stock_produit sp
                 JOIN storage s ON sp.storage_id = s.id
                 WHERE sp.produit_id = p.id
                   AND s.magasin_id = 1
                ), 1)
        ELSE 0
    END AS rotation_annuelle,

    -- Ancienneté du produit (en mois)
    (EXTRACT(YEAR FROM AGE(NOW(), p.created_at)) * 12 +
     EXTRACT(MONTH FROM AGE(NOW(), p.created_at)))::INTEGER AS anciennete_mois,

    -- Flag nouveau produit (basé sur config par défaut 6 mois)
    CASE
        WHEN EXTRACT(YEAR FROM AGE(NOW(), p.created_at)) * 12 +
             EXTRACT(MONTH FROM AGE(NOW(), p.created_at)) < 6
        THEN TRUE
        ELSE FALSE
    END AS est_nouveau_produit,

    p.created_at AS date_creation_produit

FROM produit p
WHERE p.status = 'ENABLE'
  AND p.type_produit != 'DETAIL';

COMMENT ON VIEW v_produit_metriques_classification IS 'Vue des métriques de classification pour chaque produit actif (stock filtré sur magasin par défaut id=1)';

-- ============================================================================

-- Ajouter colonne is_classification_overridden sur produit (optionnel)
ALTER TABLE produit ADD COLUMN IF NOT EXISTS is_classification_overridden BOOLEAN DEFAULT FALSE;

COMMENT ON COLUMN produit.is_classification_overridden IS 'Si TRUE, la classe ne sera pas modifiée par la reclassification automatique';

-- ============================================================================

-- Trigger pour mettre à jour updated_at sur classification_config
CREATE OR REPLACE FUNCTION update_classification_config_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_classification_config_updated_at
    BEFORE UPDATE ON classification_config
    FOR EACH ROW
    EXECUTE FUNCTION update_classification_config_updated_at();


