create table dashboard_layout
(
  id            integer generated by default as identity
    primary key,
  created_at    timestamp(6),
  description   varchar(255),
  is_default    boolean,
  layout_config jsonb,
  name          varchar(255) not null,
  scope         varchar(10)  not null
    constraint dashboard_layout_scope_check
            check ((scope)::text = ANY
                   ((ARRAY ['PRIVATE'::character varying, 'SHARED'::character varying, 'PUBLIC'::character varying])::text[])),
  updated_at    timestamp(6),
  user_id       integer
    constraint fk8ccq7fqjxyyrp4oququtxjs8f
            references app_user
);

-- Indexes
CREATE INDEX idx_dashboard_layout_user_id ON dashboard_layout(user_id);
CREATE INDEX idx_dashboard_layout_scope ON dashboard_layout(scope);
CREATE INDEX idx_dashboard_layout_is_default ON dashboard_layout(is_default);
CREATE INDEX idx_dashboard_layout_updated_at ON dashboard_layout(updated_at DESC);

-- GIN index on JSONB for fast querying of layout configuration
CREATE INDEX idx_dashboard_layout_config ON dashboard_layout USING GIN (layout_config);

-- Ensure only one default per user
CREATE UNIQUE INDEX idx_dashboard_layout_user_default ON dashboard_layout(user_id) WHERE is_default = TRUE;

COMMENT ON TABLE dashboard_layout IS 'Customizable dashboard layouts for users';
COMMENT ON COLUMN dashboard_layout.scope IS 'PRIVATE, SHARED, or PUBLIC';
COMMENT ON COLUMN dashboard_layout.layout_config IS 'JSONB configuration for GridStack layout and widgets. Allows native PostgreSQL JSON queries.';
