
CREATE TABLE IF NOT EXISTS  user_device
(
  id                    integer generated by default as identity
    primary key,
  app_version           varchar(20),
  device_model          varchar(100),
  device_name           varchar(100),
  fcm_token             varchar(512)                not null
    constraint ukmhlsk593ok8p9chicoicy95ji
            unique,
  last_active_at        timestamp(6) with time zone,
  notifications_enabled boolean                     not null,
  os_version            varchar(50),
  registered_at         timestamp(6) with time zone not null,
  user_id               integer                     not null
    constraint fkkqb6jmrvjmkv4a4x0315816wq
            references app_user
);




-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_device_user_id ON user_device(user_id);
CREATE INDEX IF NOT EXISTS idx_user_device_fcm_token ON user_device(fcm_token);
CREATE INDEX IF NOT EXISTS idx_user_device_notifications_enabled ON user_device(notifications_enabled);
CREATE INDEX IF NOT EXISTS idx_user_device_last_active ON user_device(last_active_at);

-- Add comments
COMMENT ON TABLE user_device IS 'Stores user mobile devices for push notifications';
COMMENT ON COLUMN user_device.fcm_token IS 'Firebase Cloud Messaging token (unique per device)';
COMMENT ON COLUMN user_device.user_id IS 'Reference to app_user table';
COMMENT ON COLUMN user_device.device_name IS 'User-friendly device name (e.g., "Samsung Galaxy S21")';
COMMENT ON COLUMN user_device.device_model IS 'Device model identifier';
COMMENT ON COLUMN user_device.os_version IS 'Android OS version (e.g., "13")';
COMMENT ON COLUMN user_device.app_version IS 'Application version (e.g., "1.0.0")';
COMMENT ON COLUMN user_device.notifications_enabled IS 'Whether notifications are enabled for this device';
COMMENT ON COLUMN user_device.registered_at IS 'When the device was first registered';
COMMENT ON COLUMN user_device.last_active_at IS 'Last time the device was active';

ALTER TABLE stock_produit ADD COLUMN IF NOT EXISTS seuil_mini integer null  ;
ALTER TABLE stock_produit ADD COLUMN IF NOT EXISTS stock_reassort integer null ;

ALTER  TABLE  stock_produit add CONSTRAINT  stock_produit_seuil_mini_check CHECK (seuil_mini >= 0);
ALTER  TABLE  stock_produit add CONSTRAINT  stock_produit_stock_reassort_check CHECK (stock_reassort >= 0);

ALTER TABLE  produit DROP COLUMN IF EXISTS seuil_reassort;


