-- Scheduled Reports - Automatic Report Generation and Email Delivery
-- Description: Table for configuring automatic report generation on schedule

create table scheduled_report
(
  id               integer generated by default as identity
    primary key,
  active           boolean      not null,
  created_at       timestamp(6),
  day_of_month     integer,
  day_of_week      integer,
  email_recipients jsonb,
  execution_time   time(0),
  filter_params    jsonb,
  frequency        varchar(15)  not null
    constraint scheduled_report_frequency_check
            check ((frequency)::text = ANY
                   ((ARRAY ['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'CUSTOM'::character varying])::text[])),
  include_excel    boolean      not null,
  include_pdf      boolean      not null,
  last_execution   timestamp(6),
  next_execution   timestamp(6),
  report_name      varchar(255) not null,
  report_type      varchar(50)  not null
    constraint scheduled_report_report_type_check
            check ((report_type)::text = ANY
                   ((ARRAY ['DASHBOARD_CA'::character varying, 'SALES_SUMMARY'::character varying, 'TOP_PRODUCTS'::character varying, 'STOCK_ALERTS'::character varying, 'STOCK_VALUATION'::character varying, 'STOCK_ROTATION'::character varying, 'CASH_REGISTER'::character varying, 'TIERS_PAYANT_CREANCES'::character varying, 'CUSTOMER_SEGMENTATION'::character varying, 'SUPPLIER_PERFORMANCE'::character varying, 'PROFITABILITY_ANALYSIS'::character varying, 'ABC_PARETO'::character varying, 'COMPARATIVE_ANALYSIS'::character varying])::text[])),
  updated_at       timestamp(6),
  created_by_id    integer
    constraint fkah6vwin17uuwcus7rbyqupjp8
            references app_user
);

-- Indexes
CREATE INDEX idx_scheduled_report_active ON scheduled_report(active);
CREATE INDEX idx_scheduled_report_next_execution ON scheduled_report(next_execution) WHERE active = TRUE;
CREATE INDEX idx_scheduled_report_type ON scheduled_report(report_type);
CREATE INDEX idx_scheduled_report_frequency ON scheduled_report(frequency);



-- Insert default scheduled reports (examples)
INSERT INTO scheduled_report (
    report_name,
    report_type,
    frequency,
    execution_time,
    day_of_week,
    email_recipients,
    active,
    next_execution,
    include_pdf,
    include_excel
) VALUES
(
    'Rapport Quotidien - Alertes Stock',
    'STOCK_ALERTS',
    'DAILY',
    '08:00:00',
    NULL,
    '["badoukobena@gmail.com"]'::jsonb,
    FALSE, -- Disabled by default
    CURRENT_TIMESTAMP + INTERVAL '1 day',
    TRUE,TRUE
),
(
    'Rapport Hebdomadaire - CA',
    'DASHBOARD_CA',
    'WEEKLY',
    '09:00:00',
    1, -- Monday
    '["badoukobena@gmail.com"]'::jsonb,
    FALSE,
    CURRENT_TIMESTAMP + INTERVAL '1 week',
    TRUE,TRUE
),
(
    'Rapport Mensuel - Créances Tiers-Payants',
    'TIERS_PAYANT_CREANCES',
    'MONTHLY',
    '10:00:00',
    NULL,
    '["badoukobena@gmail.com"]'::jsonb,
    FALSE,
    CURRENT_TIMESTAMP + INTERVAL '1 month',
    TRUE,TRUE
);

-- Comments
COMMENT ON TABLE scheduled_report IS 'Configuration for automatic scheduled report generation and email delivery';
COMMENT ON COLUMN scheduled_report.report_type IS 'Type of report: DASHBOARD_CA, STOCK_ALERTS, TIERS_PAYANT_CREANCES, etc.';
COMMENT ON COLUMN scheduled_report.frequency IS 'Execution frequency: DAILY, WEEKLY, MONTHLY';
COMMENT ON COLUMN scheduled_report.execution_time IS 'Time of day to execute the report';
COMMENT ON COLUMN scheduled_report.day_of_week IS 'Day of week for WEEKLY frequency (1=Monday, 7=Sunday)';
COMMENT ON COLUMN scheduled_report.day_of_month IS 'Day of month for MONTHLY frequency (1-31)';
COMMENT ON COLUMN scheduled_report.filter_params IS 'JSON string containing report-specific filter parameters';

