
CREATE TABLE planning_inventaire_tournant
(
  id integer   generated by default as identity primary key,
  libelle                VARCHAR(200) NOT NULL,
  frequence              VARCHAR(20)  NOT NULL,
  critere                VARCHAR(30)  NOT NULL,
  storage_id             INT REFERENCES storage (id),

  user_id                INT REFERENCES app_user (id),
  prochaine_execution    DATE         NOT NULL,
  actif                  BOOLEAN      NOT NULL DEFAULT true,
  critere_index_courant  INT          NOT NULL DEFAULT 0, -- index de rotation dans la liste des critères
  classe_pareto_courante VARCHAR(1)   NULL,               -- Pour critère ABC : 'A', 'B' ou 'C'
  nb_executions          INT          NOT NULL DEFAULT 0,
  derniere_execution     DATE         NULL,
  created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_pit_storage_actif ON planning_inventaire_tournant (storage_id, actif);
CREATE INDEX idx_pit_prochaine_exec ON planning_inventaire_tournant (prochaine_execution) WHERE actif = true;
CREATE INDEX idx_pit_user_id ON planning_inventaire_tournant (user_id);


ALTER TABLE store_inventory
  DROP CONSTRAINT store_inventory_inventory_category_check;

ALTER TABLE store_inventory
  ADD CONSTRAINT store_inventory_inventory_category_check
    CHECK (
      inventory_category IN (
                             'MAGASIN',
                             'STORAGE',
                             'RAYON',
                             'FAMILLY',
                             'PERIME',
                             'ALERTE_PEREMPTION',
                             'VENDU',
                             'INVENDU',
                             'SOUS_SEUIL',
                             'EN_RUPTURE',
                             'GROSSISTE',
                             'SELECTION_PRODUIT',
                             'ABC'
        )
      );

CREATE TABLE inventory_gap_analysis
(
  id                      bigint generated by default as identity primary key,
  store_inventory_line_id BIGINT      NOT NULL REFERENCES store_inventory_line (id) ON DELETE CASCADE,
  cause                   VARCHAR(30) NOT NULL,
  quantity                INT         NOT NULL,
  commentaire             TEXT,
  created_at              TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_iga_line_id ON inventory_gap_analysis (store_inventory_line_id);
CREATE INDEX idx_iga_inventory ON inventory_gap_analysis (store_inventory_line_id, cause);
CREATE TABLE IF NOT EXISTS stock_produit_snapshot
(
  id                  BIGINT generated by default as identity primary key,
  produit_id          INT         NOT NULL REFERENCES produit (id),
  storage_id          INT         NOT NULL REFERENCES storage (id),
  snapshot_date       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  qty_stock           INT         NOT NULL,
  source_type         VARCHAR(30) NOT NULL, -- 'INVENTAIRE_CLOTURE' | 'BATCH_QUOTIDIEN' | 'INITIAL'
  source_inventory_id BIGINT REFERENCES store_inventory (id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE stock_produit_snapshot
  ADD CONSTRAINT uq_snapshot_produit_storage_date
    UNIQUE (produit_id, storage_id, snapshot_date);

CREATE INDEX IF NOT EXISTS idx_snapshot_storage_produit
  ON stock_produit_snapshot (storage_id, produit_id, snapshot_date DESC);
ALTER TABLE stock_produit
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
