
CREATE TABLE IF NOT EXISTS  nav_item (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(60)  NOT NULL UNIQUE,
    libelle      VARCHAR(100) NOT NULL,
    icon         VARCHAR(80),
    router_link  VARCHAR(150),
    parent_id    INTEGER      REFERENCES nav_item(id) ON DELETE CASCADE,
    ordre        INTEGER      NOT NULL DEFAULT 0,
    niveau       SMALLINT     NOT NULL DEFAULT 1,
    badge_type   VARCHAR(20)  DEFAULT 'NONE',
    target_type  VARCHAR(20)  DEFAULT 'ROUTE',
    actif        BOOLEAN      NOT NULL DEFAULT TRUE,
    created      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated      TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Permissions fines sur chaque item
CREATE TABLE IF NOT EXISTS  nav_permission (
    id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nav_item_id INTEGER     NOT NULL REFERENCES nav_item(id) ON DELETE CASCADE,
    action      VARCHAR(20) NOT NULL,
    UNIQUE (nav_item_id, action)
);

-- Association item ↔ rôle (avec permissions)
CREATE TABLE IF NOT EXISTS  nav_item_role (
    id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nav_item_id     INTEGER     NOT NULL REFERENCES nav_item(id) ON DELETE CASCADE,
    role_name       VARCHAR(60) NOT NULL,
    can_display     BOOLEAN     NOT NULL DEFAULT TRUE,
    can_access      BOOLEAN     NOT NULL DEFAULT TRUE,
    can_create      BOOLEAN     NOT NULL DEFAULT FALSE,
    can_edit        BOOLEAN     NOT NULL DEFAULT FALSE,
    can_delete      BOOLEAN     NOT NULL DEFAULT FALSE,
    can_export      BOOLEAN     NOT NULL DEFAULT FALSE,
    UNIQUE (nav_item_id, role_name)
);

-- Préférences de réorganisation par utilisateur
CREATE TABLE IF NOT EXISTS  nav_item_user_order (
    id          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login  VARCHAR(50) NOT NULL,
    nav_item_id INTEGER     NOT NULL REFERENCES nav_item(id) ON DELETE CASCADE,
    ordre       INTEGER     NOT NULL DEFAULT 0,
    UNIQUE (user_login, nav_item_id)
);

-- Index
CREATE INDEX idx_nav_item_parent    ON nav_item(parent_id);
CREATE INDEX idx_nav_item_role_role ON nav_item_role(role_name);
CREATE INDEX idx_nav_perm_item      ON nav_permission(nav_item_id);
CREATE INDEX idx_nav_user_order     ON nav_item_user_order(user_login);

-- ─── Données initiales ───────────────────────────────────────────────────────
-- Niveau 1 : groupes fonctionnels (roots)
INSERT INTO nav_item (code, libelle, icon, router_link, ordre, niveau, target_type) VALUES
  ('nouvelle-vente',      'Nouvelle Vente',         'pi pi-shopping-bag',    '/sales-home',         0,  1, 'ROUTE'),
  ('nouvelle-prevente',      'Nouvelle Prévente',         'pi pi-bookmark',    '/sales-home/prevente',         0,  1, 'ROUTE'),
  ('gestion-courante',    'Gestion Courante',        'pi pi-list',            NULL,                  1,  1, 'GROUP'),
  ('gestion-stock',       'Gestion Stock',           'pi pi-truck',           NULL,                  2,  1, 'GROUP'),
  ('facturation',         'Facturation',             'pi pi-wallet',          NULL,                  3,  1, 'GROUP'),
  ('referentiel',         'Référentiel',             'pi pi-book',            NULL,                  4,  1, 'GROUP'),
  ('rapports',            'Rapports & Statistiques', 'pi pi-chart-bar',       NULL,                  5,  1, 'GROUP'),
  ('administration',      'Administration',          'pi pi-cog',             NULL,                  6,  1, 'GROUP');

-- Niveau 2 : enfants de gestion-courante
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'ventes', 'Ventes', 'pi pi-shopping-bag', '/sales-home/gestion', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-courante';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'mvt-caisse', 'Mouvements Caisse', 'pi pi-coins', '/mvt-caisse', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-courante';

-- Niveau 2 : enfants de gestion-stock
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'catalogue', 'Catalogue produits', 'pi pi-box', '/produits', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'commande', 'Commandes', 'pi pi-send', '/commande', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'peremptions', 'Péremptions', 'pi pi-calendar-times', '/gestion-peremption', id, 2, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'ajustements', 'Ajustements', 'pi pi-sliders-h', '/features-ajustement', id, 3, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'inventaire', 'Inventaire', 'pi pi-clipboard', '/inventaire', id, 4, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock';

-- Niveau 2 : enfants de facturation
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'factures', 'Factures', 'pi pi-file-pdf', '/facturation', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'facturation';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'tiers-payant', 'Tiers payant', 'pi pi-users', '/tiers-payant', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'facturation';

-- Niveau 2 : enfants de referentiel
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'clients', 'Clients', 'pi pi-user', '/customer', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'fournisseurs', 'Fournisseurs', 'pi pi-building', '/fournisseur', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel';

-- Niveau 2 : enfants de rapports
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'rapport-ventes', 'Rapport Ventes', 'pi pi-chart-line', '/rapport-ventes', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'rapports';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'rapport-stock', 'Rapport Stock', 'pi pi-chart-bar', '/rapport-stock', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'rapports';

-- Niveau 2 : enfants de administration
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'utilisateurs', 'Utilisateurs', 'pi pi-users', '/admin/user-management', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'administration';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'parametres', 'Paramètres', 'pi pi-sliders-h', '/parametre', id, 1, 2, 'ROUTE'
  FROM nav_item WHERE code = 'administration';

-- Assignation par défaut ROLE_ADMIN (accès tout)
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export)
  SELECT id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE FROM nav_item;




ALTER TABLE nav_item_role
  ADD COLUMN IF NOT EXISTS can_execute BOOLEAN NOT NULL DEFAULT FALSE;

-- 2. ROLE_ADMIN : activer can_execute sur tous les items existants
UPDATE nav_item_role
SET can_execute = TRUE
WHERE role_name = 'ROLE_ADMIN';

-- 3. Ajouter l'item "nav-manager" à l'administration si absent
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
SELECT 'nav-manager', 'Rôles & Autorisations', 'pi pi-sitemap', '/admin/access-management', id, 2, 2, 'ROUTE'
FROM nav_item
WHERE code = 'administration'
  AND NOT EXISTS (SELECT 1 FROM nav_item WHERE code = 'nav-manager');

-- Assigner nav-manager à ROLE_ADMIN
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
FROM nav_item
WHERE code = 'nav-manager'
  AND NOT EXISTS (SELECT 1 FROM nav_item_role WHERE nav_item_id = (SELECT id FROM nav_item WHERE code = 'nav-manager') AND role_name = 'ROLE_ADMIN');

--  Items PR_* (actions métier) — enfants de "ventes"
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-force-stock', 'Forcer le stock à la vente', NULL, NULL, id, 0, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-modifier-prix', 'Modifier le prix à la vente', NULL, NULL, id, 1, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-remise-vente', 'Appliquer une remise à la vente', NULL, NULL, id, 2, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-supprimer-ligne-vente', 'Supprimer une ligne vente', NULL, NULL, id, 3, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-modifier-vente', 'Modifier une vente déjà clôturée', NULL, NULL, id, 4, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-annuler-vente', 'Annuler une vente', NULL, NULL, id, 5, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'vente-validation-definitive', 'Validation définitive d'' vente', NULL, NULL, id, 6, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'ventes'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'pr-voir-stock-inventaire', 'Voir stock lors de l''inventaire', NULL, NULL, id, 7, 3, 'ACTION', TRUE
FROM nav_item WHERE code = 'inventaire'
  ON CONFLICT (code) DO NOTHING;

-- 6. ROLE_ADMIN : can_execute = TRUE sur tous les items PR_*
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_ADMIN', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE
FROM nav_item
WHERE code IN (
               'pr-force-stock', 'pr-modifier-prix', 'pr-remise-vente', 'pr-supprimer-ligne-vente',
               'pr-modifier-vente', 'pr-annuler-vente', 'vente-validation-definitive', 'pr-voir-stock-inventaire'
  )
  ON CONFLICT (nav_item_id, role_name) DO UPDATE SET can_execute = TRUE;

--  ROLE_CAISSIER : validation définitive + force stock + remise
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_CAISSIER', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE
FROM nav_item
WHERE code IN ('vente-validation-definitive', 'pr-force-stock', 'pr-remise-vente')
  ON CONFLICT (nav_item_id, role_name) DO UPDATE SET can_execute = TRUE;


-- ═══════════════════════════════════════════════════════════════════════════════
-- Complétion — items manquants identifiés dans navigation.service.ts
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─── gestion-stock : Dépôt ────────────────────────────────────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'depot', 'Dépôt', 'pi pi-building', '/depot', id, 5, 2, 'ROUTE'
  FROM nav_item WHERE code = 'gestion-stock'
  ON CONFLICT (code) DO NOTHING;

-- ─── facturation : Différés (ordre 2) + Client (ordre 4) ─────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'differes', 'Différés', 'pi pi-clock', '/differes', id, 2, 2, 'ROUTE'
  FROM nav_item WHERE code = 'facturation'
  ON CONFLICT (code) DO NOTHING;

-- tiers-payant décalé à l'ordre 3 après insertion de differes
UPDATE nav_item SET ordre = 3 WHERE code = 'tiers-payant';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'facturation-client', 'Clients', 'pi pi-users', '/customer', id, 4, 2, 'ROUTE'
  FROM nav_item WHERE code = 'facturation'
  ON CONFLICT (code) DO NOTHING;

-- ─── referentiel : Groupe Produits (ordres 2–6) ───────────────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'rayon', 'Rayon', 'pi pi-align-justify', '/rayon', id, 2, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'forme-produit', 'Forme Produit', 'pi pi-tags', '/forme-produit', id, 3, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'famille-produit', 'Famille Produit', 'pi pi-th-large', '/famille-produit', id, 4, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'gamme-produit', 'Gamme Produit', 'pi pi-sitemap', '/gamme-produit', id, 5, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'laboratoire', 'Laboratoire', 'pi pi-building', '/laboratoire', id, 6, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

-- ─── referentiel : Groupe Commercial (ordres 7–10) ────────────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'remises', 'Remises', 'pi pi-percentage', '/remises', id, 7, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'tableaux', 'Tableaux', 'pi pi-table', '/tableaux', id, 8, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'tva', 'TVA', 'pi pi-percentage', '/tva', id, 9, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'mode-payments', 'Modes de paiement', 'pi pi-credit-card', '/mode-payments', id, 10, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

-- ─── referentiel : Groupe Organisation (ordres 11–13) ────────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'motif-ajustement', 'Motif Ajustement', 'pi pi-exclamation-triangle', '/motif-ajustement', id, 11, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'motif-retour-produit', 'Motif Retour Produit', 'pi pi-replay', '/motif-retour-produit', id, 12, 2, 'ROUTE'
  FROM nav_item WHERE code = 'referentiel'
  ON CONFLICT (code) DO NOTHING;



-- ─── rapports : correction routes + Clients & Fournisseurs ────────────────────
UPDATE nav_item
  SET libelle      = 'Chiffre d''Affaires',
      router_link  = '/reports/sales',
      icon         = 'pi pi-money-bill'
  WHERE code = 'rapport-ventes';

UPDATE nav_item
  SET libelle      = 'Stock & Inventaire',
      router_link  = '/reports/stock'
  WHERE code = 'rapport-stock';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'rapport-partners', 'Clients & Fournisseurs', 'pi pi-users', '/reports/partners', id, 2, 2, 'ROUTE'
  FROM nav_item WHERE code = 'rapports'
  ON CONFLICT (code) DO NOTHING;

-- ─── administration : Magasin (0), Poste (2), Menu (3) ───────────────────────
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'magasin', 'Magasin', 'pi pi-shop', '/magasin', id, 0, 2, 'ROUTE'
  FROM nav_item WHERE code = 'administration'
  ON CONFLICT (code) DO NOTHING;

-- utilisateurs décalé à l'ordre 1
UPDATE nav_item SET ordre = 1 WHERE code = 'utilisateurs';

INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type)
  SELECT 'poste', 'Poste de Travail', 'pi pi-desktop', '/poste', id, 2, 2, 'ROUTE'
  FROM nav_item WHERE code = 'administration'
  ON CONFLICT (code) DO NOTHING;



-- nav-manager décalé à l'ordre 4, parametres à l'ordre 5
UPDATE nav_item SET ordre = 4 WHERE code = 'nav-manager';
UPDATE nav_item SET ordre = 5 WHERE code = 'parametres';

-- ─── Rôles pour tous les nouveaux items ──────────────────────────────────────
-- ROLE_ADMIN : accès total
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
  FROM nav_item
  WHERE code IN (
    'depot',
    'differes', 'facturation-client',
    'rayon', 'forme-produit', 'famille-produit', 'gamme-produit', 'laboratoire',
    'remises', 'tableaux', 'tva', 'mode-payments',
    'motif-ajustement', 'motif-retour-produit', 'parametre',
    'rapport-partners',
    'magasin', 'poste', 'menu'
  )
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ─── ROLE_VENDEUR : prévente uniquement ──────────────────────────────────────
-- Accès : saisir et gérer des préventes, consulter le catalogue
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_VENDEUR', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE
  FROM nav_item
  WHERE code IN ('nouvelle-prevente')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_VENDEUR', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-courante', 'ventes')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_VENDEUR', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-stock', 'catalogue')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Actions métier ROLE_VENDEUR : remise et modification de prix sur prévente
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_VENDEUR', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE
  FROM nav_item
  WHERE code IN ('pr-remise-vente', 'pr-modifier-prix', 'pr-force-stock', 'pr-supprimer-ligne-vente')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ─── ROLE_CAISSIER : vente comptant + prévente + encaissement ────────────────
-- Accès : vente, prévente, mouvements de caisse, facturation, catalogue
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_CAISSIER', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE
  FROM nav_item
  WHERE code IN ('nouvelle-vente', 'nouvelle-prevente')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_CAISSIER', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-courante', 'ventes', 'mvt-caisse')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_CAISSIER', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('facturation', 'factures', 'differes', 'tiers-payant', 'facturation-client')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_CAISSIER', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-stock', 'catalogue')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ─── ROLE_RESPONSABLE_COMMANDE : stock + référentiel + rapports (pas de vente) ──
-- Accès : gestion stock complète, référentiel produits/fournisseurs, rapports
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE
  FROM nav_item
  WHERE code IN ('commande', 'inventaire')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('ajustements')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN (
    'gestion-stock', 'catalogue', 'peremptions', 'depot'
  )
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN (
    'referentiel', 'fournisseurs',
    'rayon', 'forme-produit', 'famille-produit', 'gamme-produit', 'laboratoire'
  )
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('rapports', 'rapport-ventes', 'rapport-stock', 'rapport-partners')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════════
-- ROLE_PHARMACIEN — création du rôle + menus
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO authority (name, libelle)
VALUES ('ROLE_PHARMACIEN', 'Pharmacien titulaire')
ON CONFLICT (name) DO NOTHING;

-- Gestion courante : supervision des ventes et du tableau de caisse (lecture)
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-courante', 'ventes', 'mvt-caisse')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Gestion stock : lecture + péremptions + inventaire (exécution)
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('gestion-stock', 'catalogue', 'commande', 'depot')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE
  FROM nav_item
  WHERE code IN ('peremptions', 'inventaire')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Facturation : lecture + export
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('facturation', 'factures', 'differes', 'tiers-payant', 'facturation-client')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Référentiel : accès complet (le pharmacien est maître du formulaire)
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE
  FROM nav_item
  WHERE code IN (
    'referentiel',
    'clients', 'fournisseurs',
    'rayon', 'forme-produit', 'famille-produit', 'gamme-produit', 'laboratoire',
    'remises', 'tableaux', 'tva', 'mode-payments',
    'motif-ajustement', 'motif-retour-produit', 'parametre'
  )
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- Rapports : lecture + export complets
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
  SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
  FROM nav_item
  WHERE code IN ('rapports', 'rapport-ventes', 'rapport-stock', 'rapport-partners')
  ON CONFLICT (nav_item_id, role_name) DO NOTHING;

