

CREATE TABLE reconciliation_facture_fournisseur
(
    id                    integer generated by default as identity PRIMARY KEY,
    facture_reference    VARCHAR(100),
    facture_date         DATE,
    facture_montant_ht   INTEGER,
    facture_tva          INTEGER,
    bl_montant_ht        INTEGER,
    bl_tva               INTEGER,
    ecart_ht             INTEGER,
    ecart_tva            INTEGER,
    statut               VARCHAR(20)  NOT NULL DEFAULT 'EN_ATTENTE',
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP,
    avoir_fournisseur_id INTEGER
);

ALTER TABLE commande
    ADD COLUMN reconciliation_id INTEGER,
    ADD CONSTRAINT fk_commande_reconciliation
        FOREIGN KEY (reconciliation_id)
            REFERENCES reconciliation_facture_fournisseur (id);
