-- Table des avoirs fournisseur (générés automatiquement à la saisie d'une réponse retour)
CREATE TABLE IF NOT EXISTS avoir_fournisseur (
    id                    integer generated by default as identity PRIMARY KEY,
    reference             VARCHAR(30) UNIQUE,
    date_mtv              TIMESTAMP NOT NULL DEFAULT NOW(),
    montant               integer NOT NULL DEFAULT 0,
    statut                VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE',
    commentaire           VARCHAR(200),
    user_id               integer NOT NULL REFERENCES app_user(id),
    reponse_retour_bon_id INTEGER NOT NULL UNIQUE REFERENCES reponse_retour_bon(id),
    fournisseur_id        INTEGER NOT NULL REFERENCES fournisseur(id),

    CONSTRAINT avoir_fournisseur_statut_check
        CHECK (statut IN ('EN_ATTENTE', 'REMBOURSE', 'IMPUTE'))
);

CREATE INDEX IF NOT EXISTS idx_avoir_fournisseur_statut     ON avoir_fournisseur (statut);
CREATE INDEX IF NOT EXISTS idx_avoir_fournisseur_fournisseur ON avoir_fournisseur (fournisseur_id);
CREATE INDEX IF NOT EXISTS idx_avoir_fournisseur_date       ON avoir_fournisseur (date_mtv);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Navigation : onglet "Avoirs fournisseurs" dans la page Retours fournisseurs
-- ═══════════════════════════════════════════════════════════════════════════════

-- Onglet niveau 4 sous commande.retour-fournisseur
INSERT INTO nav_item (code, libelle, icon, router_link, parent_id, ordre, niveau, target_type, actif)
SELECT 'commande.retour-fournisseur.avoirs', 'Avoirs fournisseurs', 'pi pi-wallet', NULL, id, 50, 4, 'SECTION', TRUE
FROM nav_item WHERE code = 'commande.retour-fournisseur'
ON CONFLICT (code) DO NOTHING;

-- ROLE_ADMIN : accès complet
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_ADMIN', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE
FROM nav_item WHERE code = 'commande.retour-fournisseur.avoirs'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ROLE_RESPONSABLE_COMMANDE : accès complet (idem retour-fournisseur)
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_RESPONSABLE_COMMANDE', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE
FROM nav_item WHERE code = 'commande.retour-fournisseur.avoirs'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;

-- ROLE_PHARMACIEN : lecture + export seulement
INSERT INTO nav_item_role (nav_item_id, role_name, can_display, can_access, can_create, can_edit, can_delete, can_export, can_execute)
SELECT id, 'ROLE_PHARMACIEN', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE
FROM nav_item WHERE code = 'commande.retour-fournisseur.avoirs'
ON CONFLICT (nav_item_id, role_name) DO NOTHING;
