CREATE TABLE retour_client (
    id                  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(30)   NOT NULL UNIQUE,
    created_at          TIMESTAMP     NOT NULL DEFAULT NOW(),
    validated_at        TIMESTAMP,
    motif               VARCHAR(30)   NOT NULL,
    mode_reglement      VARCHAR(30),
    commentaire         VARCHAR(500),
    montant_total       INTEGER       NOT NULL DEFAULT 0,
    original_sale_id    BIGINT,
    original_sale_date  DATE,
    original_sale_ref   VARCHAR(50),
    customer_id         INTEGER       REFERENCES customer(id),
    created_by_id       INTEGER       NOT NULL REFERENCES app_user(id),
    validated_by_id     INTEGER       REFERENCES app_user(id)
);

CREATE TABLE retour_client_line (
    id                          INTEGER    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retour_client_id            INTEGER   NOT NULL REFERENCES retour_client(id),
    produit_id                  INTEGER   NOT NULL REFERENCES produit(id),
    quantite                    INTEGER   NOT NULL,
    prix_unitaire               INTEGER   NOT NULL,
    montant                     INTEGER   NOT NULL,
    original_sales_line_id      BIGINT,
    original_sales_line_date    DATE
);

CREATE INDEX idx_retour_client_customer ON retour_client (customer_id);
CREATE INDEX idx_retour_client_sale     ON retour_client (original_sale_id, original_sale_date);
CREATE INDEX idx_retour_client_line_rc  ON retour_client_line (retour_client_id);
