
ALTER TABLE poste DROP COLUMN IF EXISTS customer_display;
ALTER TABLE poste DROP COLUMN IF EXISTS customer_display_port;
--  Table poste_device : gestion multi-périphériques par poste (douchette, afficheur, imprimante)
-- Un seul périphérique actif par type et par poste.

CREATE TABLE IF NOT EXISTS poste_device (
 id              integer generated by default as identity PRIMARY KEY,
                                          poste_id        INTEGER NOT NULL REFERENCES poste(id) ON DELETE CASCADE,
  device_type     VARCHAR(20) NOT NULL,  -- SCANNER, DISPLAY, PRINTER
  port_name       VARCHAR(20) NOT NULL,  -- COM3, COM5, etc.
  label           VARCHAR(100),          -- Nom lisible (ex: "Honeywell Voyager 1200g")
  baud_rate       INTEGER DEFAULT 9600,
  vid             INTEGER,               -- USB Vendor ID
  pid             INTEGER,               -- USB Product ID
  manufacturer    VARCHAR(100),
  product_name    VARCHAR(100),
  serial_number   VARCHAR(100),
  active          BOOLEAN NOT NULL DEFAULT false,
  last_connected_at TIMESTAMP,
  created_at      TIMESTAMP NOT NULL DEFAULT now()
  );

-- Contrainte unique : un seul enregistrement par (poste, type, port)
ALTER TABLE poste_device
  ADD CONSTRAINT uq_poste_device_poste_type_port
    UNIQUE (poste_id, device_type, port_name);

-- Index pour recherche rapide du périphérique actif par type et poste
CREATE INDEX IF NOT EXISTS idx_poste_device_active
  ON poste_device (poste_id, device_type, active)
  WHERE active = true;

